"use client";
import * as React from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { brl, num, dateBR, dateTimeBR } from "@/lib/utils";
import { Button, Confirm } from "@/components/ui";
import { DetailShell, KV, SimpleTable, useDoc, LoadingOr, StatusBadge, type Row } from "./shared";
export function StockDocDetail({ id, endpoint, base, title, perm, dateKey, extraKV, cancelLabel = "Cancelar documento" }: { id: string; endpoint: string; base: string; title: string; perm: string; dateKey: string; extraKV?: (d: Row) => [string, React.ReactNode][]; cancelLabel?: string }) {
  const { can } = useAuth(); const qc = useQueryClient(); const [c, setC] = React.useState(false);
  const q = useDoc<Row & { items: Row[]; movements: Row[]; titles?: Row[]; apportionments?: Row[]; provider?: Row }>(`${endpoint}/${id}`);
  const cancel = useMutation({ mutationFn: () => api(`${endpoint}/${id}/cancel`, { method: "POST", body: {} }), onSuccess: () => { toast.success("Cancelado"); setC(false); void qc.invalidateQueries(); }, onError: (e) => toast.error((e as Error).message) });
  const d = q.data;
  return <LoadingOr q={q}>{d && <DetailShell title={`${title} ${d["code"] ?? ""}`} back={base} status={String(d["status"])} actions={d["status"] !== "cancelled" && can(`${perm}.delete`) && <Button size="sm" variant="danger" onClick={() => setC(true)}>{cancelLabel}</Button>}>
    <KV items={[["Código", String(d["code"] ?? "")], ["Data", dateBR(d[dateKey] as string)], ["Fazenda", String(d["farm_name"] ?? "")], ["Responsável", String(d["created_by_name"] ?? "")], ...(d["number"] ? [["Documento", `${d["number"]}/${d["series"] ?? ""}`] as [string, React.ReactNode]] : []), ...(d["provider"] ? [["Fornecedor", String((d["provider"] as Row)["name"])] as [string, React.ReactNode]] : []), ...(d["warehouse_name"] ? [["Armazém", String(d["warehouse_name"])] as [string, React.ReactNode]] : []), ...(d["reason"] ? [["Motivo", String(d["reason"])] as [string, React.ReactNode]] : []), ...(d["justification"] ? [["Justificativa", String(d["justification"])] as [string, React.ReactNode]] : []), ...(d["note"] ? [["Observação", String(d["note"])] as [string, React.ReactNode]] : []), ["Total", brl((d["total_amount"] ?? d["total"] ?? d["total_value"]) as string)], ...(extraKV?.(d) ?? [])]} />
    <h3 className="text-xs font-semibold uppercase text-brand-700">Itens</h3>
    <SimpleTable rows={d.items} cols={[{ key: "product_code", label: "Código" }, { key: "product_name", label: "Produto" }, { key: "warehouse_name", label: "Armazém" }, { key: "quantity", label: "Qtd.", align: "right", render: (r) => `${num(r["quantity"] as string, 4)} ${r["unit"] ?? ""}` }, { key: "unit_value", label: "Vl. Unit.", align: "right", render: (r) => brl((r["unit_value"] ?? r["unit_cost"]) as string) }, { key: "total_value", label: "Total", align: "right", render: (r) => brl((r["total_value"] ?? r["total"] ?? r["total_cost"]) as string) }, { key: "provider_lot", label: "Lote" }, { key: "cost_center_name", label: "Centro de Custo" }, { key: "generate_stock", label: "Gera estoque", render: (r) => (r["generate_stock"] === false ? "Não" : "Sim") }]} />
    {d.apportionments && d.apportionments.length > 0 && <><h3 className="text-xs font-semibold uppercase text-brand-700">Rateio financeiro</h3><SimpleTable rows={d.apportionments} cols={[{ key: "category_name", label: "Categoria" }, { key: "cost_center_name", label: "Centro de Custo" }, { key: "percentage", label: "%", align: "right", render: (r) => num(r["percentage"] as string) }, { key: "amount", label: "Valor", align: "right", render: (r) => brl(r["amount"] as string) }]} /></>}
    {d.titles && d.titles.length > 0 && <><h3 className="text-xs font-semibold uppercase text-brand-700">Títulos financeiros gerados</h3><SimpleTable rows={d.titles} cols={[{ key: "code", label: "Código" }, { key: "number", label: "Nº Título" }, { key: "direction", label: "Natureza", render: (r) => (r["direction"] === "payable" ? "A pagar" : "A receber") }, { key: "due_date", label: "Vencimento", render: (r) => dateBR(r["due_date"] as string) }, { key: "amount", label: "Valor", align: "right", render: (r) => brl(r["amount"] as string) }, { key: "balance", label: "Saldo", align: "right", render: (r) => brl(r["balance"] as string) }, { key: "status", label: "Status", render: (r) => <StatusBadge s={String(r["status"])} /> }]} /></>}
    <h3 className="text-xs font-semibold uppercase text-brand-700">Movimentações de estoque (ledger)</h3>
    <SimpleTable rows={d.movements} cols={[{ key: "movement_date", label: "Data", render: (r) => dateBR(r["movement_date"] as string) }, { key: "movement_type", label: "Tipo" }, { key: "direction", label: "E/S", render: (r) => (r["direction"] === 1 ? "Entrada" : "Saída") }, { key: "quantity", label: "Qtd.", align: "right", render: (r) => num(r["quantity"] as string, 4) }, { key: "unit_cost", label: "Custo unit.", align: "right", render: (r) => brl(r["unit_cost"] as string) }, { key: "total_cost", label: "Total", align: "right", render: (r) => brl(r["total_cost"] as string) }, { key: "balance_after", label: "Saldo após", align: "right", render: (r) => num(r["balance_after"] as string, 4) }]} />
    <p className="text-[11px] text-slate-400">Criado em {dateTimeBR(d["created_at"] as string)}</p>
    <Confirm open={c} onOpenChange={setC} title={cancelLabel} text="Estorna todos os lançamentos vinculados. Continuar?" danger loading={cancel.isPending} onConfirm={() => cancel.mutate()} />
  </DetailShell>}</LoadingOr>;
}
