"use client";
import * as React from "react";
import { useQuery } from "@tanstack/react-query";
import { api, qs } from "@/lib/api";
import { brl, num, pct, dateBR, yearStartISO, todayISO } from "@/lib/utils";
import { Card, CardHeader, CardBody, Input, Stat, LoadingState, ErrorState, PageHeader } from "@/components/ui";
import { Bars, Lines, Donut } from "@/components/charts";
import { SimpleTable, type Row } from "@/features/docs/shared";
import { COPY, enumLabel, statusLabel } from "@/lib/copy";
type Any = Record<string, unknown>;
const CFG: Record<string, { title: string; path: string; period?: boolean; year?: boolean }> = {
  financeiro: { title: "Indicadores Financeiros", path: "financial", period: true }, "livro-caixa": { title: "Livro Caixa", path: "cash-book", period: true }, suprimentos: { title: "Suprimentos", path: "supply", period: true }, pecuaria: { title: "Pecuária de Corte", path: "livestock", period: true },
  depreciacoes: { title: "Depreciações", path: "depreciation", year: true }, ativos: { title: "Bens e frota", path: "assets" }, usuarios: { title: "Análise de Usuários", path: "user-analysis", period: true }, pluviometria: { title: "Pluviometria", path: "rainfall", year: true },
  confinamento: { title: "Lotação de Currais", path: "feedlot" }, "confinamento-custos": { title: "Custos do Confinamento", path: "feedlot-cost", period: true }, "confinamento-desempenho": { title: "Desempenho de Lotes", path: "feedlot-performance" }, "estoque-nutricao": { title: "Estoque de Nutrição", path: "nutrition-stock" }, "consumo-racao": { title: "Consumo de Ração", path: "feed-consumption", period: true }
};
const M = ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"];
/** Painel de indicadores de um módulo (antes: /dashboards/[key]); embutido na aba "Visão Geral" de cada área. */
export function Dashboard({ k: key, title }: { k: string; title?: string }) {
  const cfg = CFG[key];
  const [start, setStart] = React.useState(yearStartISO()); const [end, setEnd] = React.useState(todayISO()); const [year, setYear] = React.useState(new Date().getFullYear());
  const q = useQuery({ queryKey: ["dash", key, start, end, year], queryFn: () => api<Any>(`/api/dashboards/${cfg!.path}${qs(cfg!.period ? { start_date: start, end_date: end } : cfg!.year ? { year } : {})}`), enabled: Boolean(cfg) });
  if (!cfg) return <ErrorState message="Painel não encontrado." variant="block" />;
  const d = q.data;
  return <div className="ws-scroll space-y-4">
    <PageHeader title={title ?? cfg.title} actions={<>{cfg.period && <><div><label className="text-[11px] text-slate-500">Início</label><Input type="date" value={start} onChange={(e) => setStart(e.target.value)} /></div><div><label className="text-[11px] text-slate-500">Fim</label><Input type="date" value={end} onChange={(e) => setEnd(e.target.value)} /></div></>}{cfg.year && <div><label className="text-[11px] text-slate-500">Ano</label><Input type="number" value={year} onChange={(e) => setYear(Number(e.target.value))} className="w-28" /></div>}</>} />
    {q.isLoading && <LoadingState />}{q.error && <ErrorState error={q.error} onRetry={() => void q.refetch()} />}
    {d && <Body k={key} d={d} />}
  </div>;
}
const rows = (v: unknown) => (Array.isArray(v) ? (v as Row[]) : []);
const T = ({ title, data, cols }: { title: string; data: unknown; cols: { key: string; label: string; money?: boolean; qty?: boolean; render?: (r: Row) => React.ReactNode }[] }) => <Card><CardHeader title={title} /><CardBody><SimpleTable rows={rows(data)} cols={cols.map((c) => ({ key: c.key, label: c.label, align: c.money || c.qty ? "right" : undefined, render: c.render ?? ((r) => (c.money ? brl(r[c.key] as string) : c.qty ? num(r[c.key] as string, 2) : String(r[c.key] ?? ""))) }))} /></CardBody></Card>;
function Body({ k, d }: { k: string; d: Any }) {
  switch (k) {
    case "financeiro": { const ov = rows(d["overdue"]); const up = rows(d["upcoming_30d"]); const g = (arr: Row[], dir: string) => arr.find((x) => x["direction"] === dir); return <>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="A pagar vencido" value={brl((g(ov, "payable")?.["balance"] as string) ?? 0)} hint={`${g(ov, "payable")?.["n"] ?? 0} títulos`} tone="red" /><Stat label="A receber vencido" value={brl((g(ov, "receivable")?.["balance"] as string) ?? 0)} hint={`${g(ov, "receivable")?.["n"] ?? 0} títulos`} tone="amber" /><Stat label="A pagar 30 dias" value={brl((g(up, "payable")?.["balance"] as string) ?? 0)} /><Stat label="A receber 30 dias" value={brl((g(up, "receivable")?.["balance"] as string) ?? 0)} tone="green" /></div>
      <div className="grid gap-3 lg:grid-cols-2"><Card><CardHeader title="Receitas x Despesas realizadas (mês)" /><CardBody><Bars data={rows(d["monthly_realized"]).map((r) => ({ ...r, income: Number(r["income"]), expense: Number(r["expense"]) }))} x="month" series={[{ key: "income", label: "Receitas", color: "#2b6f3a" }, { key: "expense", label: "Despesas", color: "#c0392b" }]} /></CardBody></Card><Card><CardHeader title="Investimentos (CAPEX) por categoria" /><CardBody>{rows(d["investment_by_category"]).length ? <Donut data={rows(d["investment_by_category"])} nameKey="category" valueKey="investment" /> : <p className="text-sm text-slate-400">Sem investimentos no período.</p>}</CardBody></Card></div>
      <T title="Resultado por centro de custo" data={d["by_cost_center"]} cols={[{ key: "cost_center", label: "Centro de custo" }, { key: "income", label: "Receita", money: true }, { key: "expense", label: "Despesa", money: true }, { key: "investment", label: "Investimento", money: true }, { key: "result", label: "Resultado", money: true }]} />
      <T title="Saldos bancários" data={d["bank_balances"]} cols={[{ key: "code", label: "Código" }, { key: "description", label: "Conta" }, { key: "balance", label: "Saldo", money: true }]} /></>; }
    case "livro-caixa": return <><Card><CardBody><Bars data={rows(d["monthly"]).map((r) => ({ ...r, income: Number(r["income"]), expense: Number(r["expense"]) }))} x="month" series={[{ key: "income", label: "Entradas", color: "#2b6f3a" }, { key: "expense", label: "Saídas", color: "#c0392b" }]} /></CardBody></Card><T title="Livro caixa por mês (contas marcadas como livro caixa)" data={d["monthly"]} cols={[{ key: "month", label: "Mês" }, { key: "income", label: "Entradas", money: true }, { key: "expense", label: "Saídas", money: true }, { key: "movements", label: "Movimentos" }, { key: "deductible", label: "Dedutíveis" }]} /></>;
    case "suprimentos": return <><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Tempo médio de atendimento (h)" value={String(d["avg_lead_time_hours"] ?? "—")} hint="Da criação até finalização" /><Stat label="Solicitações" value={rows(d["by_status"]).reduce((a, r) => a + Number(r["n"]), 0)} /><Stat label="Aprovado (R$)" value={brl(rows(d["by_status"]).reduce((a, r) => a + Number(r["approved"]), 0))} tone="green" /><Stat label="SLA estourado" value={rows(d["sla"]).reduce((a, r) => a + Number(r["breached"]), 0)} tone="red" /></div>
      <div className="grid gap-3 lg:grid-cols-2"><T title="Por situação" data={d["by_status"]} cols={[{ key: "status", label: COPY.situacao, render: (r) => enumLabel("purchase_status", r["status"]) }, { key: "n", label: "Quantidade" }, { key: "estimated", label: "Estimado", money: true }, { key: "approved", label: "Aprovado", money: true }]} /><T title="Por tipo" data={d["by_type"]} cols={[{ key: "request_type", label: "Tipo", render: (r) => enumLabel("request_type", r["request_type"]) }, { key: "n", label: "Quantidade" }, { key: "total", label: "Total", money: true }]} /></div>
      <T title="Principais fornecedores (cotações vencedoras)" data={d["top_providers"]} cols={[{ key: "provider", label: "Fornecedor" }, { key: "quotations", label: "Cotações" }, { key: "won", label: "Vencidas" }, { key: "total", label: "Total", money: true }]} /><T title="SLA por situação (em andamento)" data={d["sla"]} cols={[{ key: "status", label: COPY.situacao, render: (r) => enumLabel("purchase_status", r["status"]) }, { key: "n", label: "Quantidade" }, { key: "breached", label: "Fora do SLA" }]} /></>;
    case "pecuaria": { const repro = d["reproduction"] as Any; const costs = d["costs"] as Any; return <><div className="grid grid-cols-2 gap-3 md:grid-cols-5"><Stat label="Cabeças ativas" value={String(d["total_heads"])} /><Stat label="GMD médio (kg/dia)" value={d["avg_gmd"] ? num(d["avg_gmd"] as string, 3) : "—"} hint={`${d["animals_weighed"]} animais pesados`} tone="green" /><Stat label="Taxa de prenhez" value={pct(repro?.["rate"] as string)} hint={`${repro?.["pregnant"] ?? 0}/${repro?.["matings"] ?? 0}`} /><Stat label="Custo manejo" value={brl((costs?.["handling"] as string) ?? 0)} tone="amber" /><Stat label="Custo alimentação" value={brl((costs?.["feed"] as string) ?? 0)} tone="amber" /></div>
      <div className="grid gap-3 lg:grid-cols-2"><Card><CardHeader title="Composição do rebanho" /><CardBody>{rows(d["herd"]).length ? <Donut data={rows(d["herd"]).map((r) => ({ ...r, heads: Number(r["identified"]) + Number(r["unidentified"]) }))} nameKey="category" valueKey="heads" /> : <p className="text-sm text-slate-400">Sem animais.</p>}</CardBody></Card><T title="Rebanho por categoria" data={d["herd"]} cols={[{ key: "category", label: "Categoria" }, { key: "identified", label: "Identificados" }, { key: "unidentified", label: "Por contagem" }, { key: "avg_weight", label: "Peso médio" }, { key: "value", label: "Valor", money: true }]} /></div>
      <T title="Movimentações no período" data={d["movements"]} cols={[{ key: "movement_type", label: "Tipo", render: (r) => enumLabel("animal_movement_type", r["movement_type"]) }, { key: "n", label: "Documentos" }, { key: "heads", label: "Cabeças" }, { key: "weight", label: "Peso (kg)", qty: true }, { key: "value", label: "Valor", money: true }]} /></>; }
    case "depreciacoes": return <><Card><CardBody><Bars data={rows(d["monthly"]).map((r) => ({ ...r, amount: Number(r["amount"]) }))} x="month" series={[{ key: "amount", label: "Depreciação", color: "#7c3aed" }]} /></CardBody></Card><T title="Por família de equipamentos" data={d["by_family"]} cols={[{ key: "family", label: "Família" }, { key: "assets", label: "Bens" }, { key: "acquisition", label: "Aquisição", money: true }, { key: "depreciated", label: "Depreciado", money: true }, { key: "current_value", label: "Valor atual", money: true }]} /></>;
    case "ativos": { const s = d["summary"] as Any; const f = d["fleet_costs_ytd"] as Any; return <><div className="grid grid-cols-2 gap-3 md:grid-cols-6"><Stat label="Bens" value={String(s?.["assets"] ?? 0)} /><Stat label="Aquisição" value={brl((s?.["acquisition"] as string) ?? 0)} /><Stat label="Depreciado" value={brl((s?.["depreciated"] as string) ?? 0)} tone="amber" /><Stat label="Valor atual" value={brl((s?.["current_value"] as string) ?? 0)} tone="green" /><Stat label="Abastecimentos (ano)" value={brl((f?.["supplies"] as string) ?? 0)} /><Stat label="Manutenções (ano)" value={brl((f?.["maintenances"] as string) ?? 0)} /></div><div className="grid gap-3 lg:grid-cols-2"><T title="Por fazenda" data={d["by_farm"]} cols={[{ key: "farm", label: "Fazenda" }, { key: "assets", label: "Bens" }, { key: "current_value", label: "Valor atual", money: true }]} /><T title="Por situação" data={d["by_status"]} cols={[{ key: "status", label: COPY.situacao, render: (r) => statusLabel(r["status"]) }, { key: "n", label: "Quantidade" }]} /></div></>; }
    case "usuarios": return <><T title="Atividade por usuário (auditoria)" data={d["by_user"]} cols={[{ key: "user_name", label: "Usuário" }, { key: "logins", label: "Acessos" }, { key: "creates", label: "Criações" }, { key: "updates", label: "Alterações" }, { key: "other", label: "Outras" }, { key: "last_activity", label: "Última atividade", render: (r) => r["last_activity"] ? dateBR(String(r["last_activity"])) : "" }]} /><T title="Entidades mais movimentadas" data={d["by_entity"]} cols={[{ key: "entity", label: "Entidade" }, { key: "n", label: "Eventos" }]} /></>;
    case "pluviometria": { const cur = rows(d["monthly"]); const prev = rows(d["previous_year"]); const data = M.map((m, i) => ({ month: m, atual: cur.filter((r) => Number(r["month"]) === i + 1).reduce((a, r) => a + Number(r["mm"]), 0), anterior: Number(prev.find((r) => Number(r["month"]) === i + 1)?.["mm"] ?? 0) })); return <><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label={`Total ${d["year"]} (mm)`} value={String(d["total_mm"])} tone="green" /></div><Card><CardBody><Bars data={data} x="month" series={[{ key: "atual", label: `${d["year"]}`, color: "#2563eb" }, { key: "anterior", label: `${Number(d["year"]) - 1}`, color: "#94a3b8" }]} /></CardBody></Card><T title="Por fazenda e mês" data={d["monthly"]} cols={[{ key: "farm", label: "Fazenda" }, { key: "month", label: "Mês", render: (r) => M[Number(r["month"]) - 1] ?? "" }, { key: "mm", label: "mm", qty: true }, { key: "rainy_days", label: "Dias de chuva" }]} /></>; }
    case "confinamento": return <><div className="grid grid-cols-2 gap-3 md:grid-cols-3"><Stat label="Capacidade" value={String(d["capacity"])} /><Stat label="Ocupação" value={String(d["occupancy"])} tone="green" /><Stat label="Taxa de lotação" value={pct(d["occupancy_rate"] as string)} /></div><T title="Currais" data={d["corrals"]} cols={[{ key: "yard", label: "Pátio" }, { key: "sector", label: "Setor" }, { key: "corral", label: "Curral" }, { key: "capacity", label: "Capacidade" }, { key: "occupancy", label: "Ocupação" }]} /></>;
    case "confinamento-custos": return <T title="Custo por lote (confinamento)" data={d["batches"]} cols={[{ key: "batch", label: "Lote" }, { key: "animals", label: "Animais" }, { key: "days", label: "Dias" }, { key: "kg", label: "Kg fornecidos", qty: true }, { key: "cost", label: "Custo", money: true }, { key: "cost_per_head_day", label: "R$/cab/dia", money: true }, { key: "kg_per_head_day", label: "kg/cab/dia", qty: true }]} />;
    case "confinamento-desempenho": return <T title="Desempenho por lote" data={d["batches"]} cols={[{ key: "batch", label: "Lote" }, { key: "animals", label: "Animais" }, { key: "entry_weight", label: "Peso entrada" }, { key: "current_weight", label: "Peso atual" }, { key: "gain", label: "Ganho (kg)" }, { key: "days", label: "Dias" }, { key: "gmd", label: "GMD" }]} />;
    case "estoque-nutricao": return <T title="Estoque de produtos de nutrição" data={d["products"]} cols={[{ key: "product", label: "Produto" }, { key: "quantity", label: "Quantidade", qty: true }, { key: "value", label: "Valor", money: true }, { key: "consumed_30d", label: "Consumo 30d", qty: true }, { key: "days_of_stock", label: "Dias de estoque", render: (r) => r["days_of_stock"] == null ? "—" : String(r["days_of_stock"]) }, { key: "below_min", label: "Abaixo do mínimo", render: (r) => r["below_min"] ? "Sim" : "" }]} />;
    case "consumo-racao": return <><Card><CardBody><Lines data={rows(d["daily"]).map((r) => ({ ...r, day: dateBR(String(r["delivery_date"])), kg: Number(r["kg"]) }))} x="day" series={[{ key: "kg", label: "Kg fornecidos", color: "#2b6f3a" }]} /></CardBody></Card><T title="Por dieta" data={d["by_diet"]} cols={[{ key: "diet", label: "Dieta" }, { key: "kg", label: "kg", qty: true }, { key: "cost", label: "Custo", money: true }]} /></>;
    default: return <pre className="text-xs">{JSON.stringify(d, null, 2)}</pre>;
  }
}
