"use client";
import { use } from "react";
import { brl, num, dateBR } from "@/lib/utils";
import { Tabs } from "@/components/ui";
import { DetailShell, KV, SimpleTable, useDoc, LoadingOr, type Row } from "@/features/docs/shared";
import { enumLabel } from "@/lib/copy";
export default function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const q = useDoc<Row & { identifications: Row[]; weighings: Row[]; handlings: Row[]; movements: Row[]; matings: Row[]; children: Row[] }>(`/api/livestock/animals/${id}`); const d = q.data;
  return <LoadingOr q={q}>{d && <DetailShell title={`Ficha do Animal — ${d.identifications.map((i) => i["value"]).join(", ")}`} back="/pecuaria?tab=rebanho&sub=animais" status={String(d["status"])}>
    <KV items={[["Fazenda", String(d["farm_name"])], ["Espécie", String(d["species_name"])], ["Categoria", String(d["category_name"])], ["Raça", String(d["breed_name"] ?? "—")], ["Sexo", d["sex"] ? enumLabel("sex", d["sex"]) : "—"], ["Lote", String(d["batch_name"] ?? "—")], ["Nascimento", d["birth_date"] ? dateBR(d["birth_date"] as string) : "—"], ["Entrada", dateBR(d["entry_date"] as string)], ["Peso atual", d["current_weight"] ? `${num(d["current_weight"] as string, 1)} kg` : "—"], ["Valor", d["unit_value"] ? brl(d["unit_value"] as string) : "—"], ["Estágio reprodutivo", d["reproductive_stage"] ? enumLabel("reproductive_stage", d["reproductive_stage"]) : "—"], ["Situação reprodutiva", d["reproductive_status"] ? enumLabel("reproductive_status", d["reproductive_status"]) : "—"], ["Origem", String(d["origin_provider_name"] ?? "—")], ["Custo de manejo acumulado", brl(d["handling_cost"] as string)], ["Observação", String(d["note"] ?? "")]]} />
    <Tabs tabs={[
      { value: "ids", label: "Identificações", content: <SimpleTable rows={d.identifications} cols={[{ key: "type_name", label: "Tipo" }, { key: "value", label: "Valor" }, { key: "is_primary", label: "Principal", render: (r) => r["is_primary"] ? "Sim" : "" }]} /> },
      { value: "w", label: "Pesagens", badge: d.weighings.length, content: <SimpleTable rows={d.weighings} cols={[{ key: "weighing_date", label: "Data", render: (r) => dateBR(r["weighing_date"] as string) }, { key: "weight", label: "Peso", align: "right", render: (r) => num(r["weight"] as string, 1) }, { key: "previous_weight", label: "Peso anterior", align: "right", render: (r) => r["previous_weight"] ? num(r["previous_weight"] as string, 1) : "" }, { key: "gmd", label: "GMD (kg/dia)", align: "right", render: (r) => r["gmd"] ? num(r["gmd"] as string, 3) : "" }]} /> },
      { value: "h", label: "Manejos", badge: d.handlings.length, content: <SimpleTable rows={d.handlings} cols={[{ key: "handling_date", label: "Data", render: (r) => dateBR(r["handling_date"] as string) }, { key: "handling_type", label: "Tipo", render: (r) => enumLabel("handling_type", r["handling_type"]) }, { key: "code", label: "Código" }, { key: "product_name", label: "Produto" }, { key: "dose", label: "Dose", align: "right" }, { key: "withdrawal_until", label: "Carência até", render: (r) => r["withdrawal_until"] ? dateBR(r["withdrawal_until"] as string) : "" }]} /> },
      { value: "m", label: "Movimentos", badge: d.movements.length, content: <SimpleTable rows={d.movements} cols={[{ key: "movement_date", label: "Data", render: (r) => dateBR(r["movement_date"] as string) }, { key: "movement_type", label: "Tipo", render: (r) => enumLabel("animal_movement_type", r["movement_type"]) }, { key: "code", label: "Código" }, { key: "weight", label: "Peso", align: "right" }, { key: "unit_value", label: "Valor", align: "right", render: (r) => r["unit_value"] ? brl(r["unit_value"] as string) : "" }]} /> },
      { value: "r", label: "Reprodução", badge: d.matings.length, content: <SimpleTable rows={d.matings} cols={[{ key: "mating_date", label: "Cobertura", render: (r) => dateBR(r["mating_date"] as string) }, { key: "mating_type", label: "Tipo", render: (r) => enumLabel("mating_type", r["mating_type"]) }, { key: "sire_name", label: "Touro/sêmen" }, { key: "result", label: "Diagnóstico", render: (r) => enumLabel("diagnosis_result", r["result"]) }, { key: "diagnosis_date", label: "Data do diagnóstico", render: (r) => r["diagnosis_date"] ? dateBR(r["diagnosis_date"] as string) : "" }, { key: "expected_birth_date", label: "Parto previsto", render: (r) => r["expected_birth_date"] ? dateBR(r["expected_birth_date"] as string) : "" }]} /> },
      { value: "c", label: "Crias", badge: d.children.length, content: <SimpleTable rows={d.children} cols={[{ key: "identifications", label: "Identificação" }, { key: "birth_date", label: "Nascimento", render: (r) => r["birth_date"] ? dateBR(r["birth_date"] as string) : "" }, { key: "sex", label: "Sexo", render: (r) => r["sex"] ? enumLabel("sex", r["sex"]) : "" }, { key: "category_name", label: "Categoria" }]} /> }
    ]} />
  </DetailShell>}</LoadingOr>;
}
