import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { isISODate, todayISO } from "@agro/shared";
import { runService } from "../lib/service.js";
import { allowedFarms, type ServiceCtx } from "../lib/context.js";

const q = z.object({ start_date: z.string().refine(isISODate).optional(), end_date: z.string().refine(isISODate).optional(), farm_ids: z.union([z.string(), z.array(z.string())]).optional(), harvest_id: z.string().uuid().optional(), year: z.coerce.number().optional() });
function range(f: z.infer<typeof q>) { const end = f.end_date ?? todayISO(); const start = f.start_date ?? `${end.slice(0, 4)}-01-01`; return { start, end }; }
/** Fazendas do painel: pedido (farm_ids) ou fazenda selecionada, sempre dentro das fazendas autorizadas (member_farms); null = todas as da organização. */
function farms(ctx: ServiceCtx, f: z.infer<typeof q>): string[] | null { return allowedFarms(ctx, f.farm_ids ?? null); }

export default async function dashboardRoutes(app: FastifyInstance) {
  // Painel de controle: previsto x realizado, custo de produção por período, resultado operacional
  app.get("/dashboards/home", async (req) => runService(app, req, "dashboard.home.view", async (ctx) => {
    const f = q.parse(req.query); const { start, end } = range(f); const fs = farms(ctx, f);
    const forecast = await ctx.tx.query("select to_char(due_date,'YYYY-MM') as month, sum(case when direction='receivable' then amount-discount else 0 end) income_forecast, sum(case when direction='payable' then amount-discount else 0 end) expense_forecast, sum(case when direction='receivable' then paid_amount else 0 end) income_done, sum(case when direction='payable' then paid_amount else 0 end) expense_done from erp.financial_titles where organization_id=$1 and status<>'cancelled' and deleted_at is null and due_date between $2 and $3 and ($4::uuid[] is null or farm_id = any($4)) group by 1 order by 1", [ctx.orgId, start, end, fs]);
    const prodCost = await ctx.tx.query("select cc.name as cost_center, coalesce(sum(a.amount),0) as expense from erp.title_apportionments a join erp.financial_titles t on t.id=a.title_id join erp.cost_centers cc on cc.id=a.cost_center_id where t.organization_id=$1 and t.direction='payable' and t.status<>'cancelled' and t.emission_date between $2 and $3 and ($4::uuid[] is null or t.farm_id = any($4)) group by 1 order by 2 desc limit 12", [ctx.orgId, start, end, fs]);
    const result = await ctx.tx.query<{ income: string; expense: string; stock: string }>("select coalesce((select sum(s.net_amount) from erp.title_settlements s join erp.financial_titles t on t.id=s.title_id where t.organization_id=$1 and t.direction='receivable' and s.status='confirmed' and s.settlement_date between $2 and $3 and ($4::uuid[] is null or t.farm_id = any($4))),0) income, coalesce((select sum(s.net_amount) from erp.title_settlements s join erp.financial_titles t on t.id=s.title_id where t.organization_id=$1 and t.direction='payable' and s.status='confirmed' and s.settlement_date between $2 and $3 and ($4::uuid[] is null or t.farm_id = any($4))),0) expense, coalesce((select sum(total_cost) from erp.stock_movements m where m.organization_id=$1 and m.direction=-1 and m.movement_type<>'reversal' and m.movement_date between $2 and $3 and ($4::uuid[] is null or m.farm_id = any($4))),0) stock", [ctx.orgId, start, end, fs]);
    const alerts = await ctx.tx.query<{ overdue_payables: string; overdue_receivables: string; low_stock: string; pending_requests: string; pending_processings: string }>("select (select count(*) from erp.financial_titles where organization_id=$1 and direction='payable' and status in ('open','partially_paid') and due_date<current_date and ($2::uuid[] is null or farm_id = any($2))) overdue_payables, (select count(*) from erp.financial_titles where organization_id=$1 and direction='receivable' and status in ('open','partially_paid') and due_date<current_date and ($2::uuid[] is null or farm_id = any($2))) overdue_receivables, (select count(*) from erp.products p where p.organization_id=$1 and p.min_stock>0 and coalesce((select sum(sb.quantity) from erp.stock_balances sb join erp.warehouses w on w.id=sb.warehouse_id where sb.product_id=p.id and ($2::uuid[] is null or w.farm_id = any($2))),0)<=p.min_stock) low_stock, (select count(*) from erp.purchase_requests where organization_id=$1 and status not in ('finished','cancelled') and ($2::uuid[] is null or farm_id = any($2))) pending_requests, (select count(*) from erp.processings where organization_id=$1 and status in ('pending','in_progress') and ($2::uuid[] is null or farm_id = any($2))) pending_processings", [ctx.orgId, fs]);
    const r = result.rows[0]!;
    return { period: { start, end }, forecast_vs_actual: forecast.rows, production_cost_by_center: prodCost.rows, operational_result: { income: r.income, expense: r.expense, stock_consumption: r.stock, result: (Number(r.income) - Number(r.expense)).toFixed(2), result_with_stock: (Number(r.income) - Number(r.expense) - Number(r.stock)).toFixed(2) }, alerts: alerts.rows[0] };
  }));
  // Indicadores financeiros: por centro de custo (receita, despesa, resultado, investimento) + títulos vencidos + saldo bancário
  app.get("/dashboards/financial", async (req) => runService(app, req, "dashboard.financial.view", async (ctx) => {
    const f = q.parse(req.query); const { start, end } = range(f); const fs = farms(ctx, f);
    const byCenter = await ctx.tx.query("select cc.name as cost_center, sum(case when t.direction='receivable' then a.amount else 0 end) income, sum(case when t.direction='payable' and t.classification<>'capex' then a.amount else 0 end) expense, sum(case when t.direction='payable' and t.classification='capex' then a.amount else 0 end) investment from erp.title_apportionments a join erp.financial_titles t on t.id=a.title_id join erp.cost_centers cc on cc.id=a.cost_center_id where t.organization_id=$1 and t.status<>'cancelled' and t.deleted_at is null and t.emission_date between $2 and $3 and ($4::uuid[] is null or t.farm_id = any($4)) group by 1 order by 1", [ctx.orgId, start, end, fs]);
    const invByCat = await ctx.tx.query("select fc.name as category, sum(a.amount) investment from erp.title_apportionments a join erp.financial_titles t on t.id=a.title_id join erp.financial_categories fc on fc.id=a.financial_category_id where t.organization_id=$1 and t.direction='payable' and t.classification='capex' and t.status<>'cancelled' and t.emission_date between $2 and $3 and ($4::uuid[] is null or t.farm_id = any($4)) group by 1 order by 2 desc", [ctx.orgId, start, end, fs]);
    const overdue = await ctx.tx.query("select direction, count(*)::int n, coalesce(sum(balance),0) balance from erp.financial_titles where organization_id=$1 and status in ('open','partially_paid') and due_date<current_date and deleted_at is null and ($2::uuid[] is null or farm_id = any($2)) group by 1", [ctx.orgId, fs]);
    const upcoming = await ctx.tx.query("select direction, count(*)::int n, coalesce(sum(balance),0) balance from erp.financial_titles where organization_id=$1 and status in ('open','partially_paid') and due_date between current_date and current_date+30 and deleted_at is null and ($2::uuid[] is null or farm_id = any($2)) group by 1", [ctx.orgId, fs]);
    const banks = await ctx.tx.query("select a.code, a.description, b.balance from erp.bank_accounts a join erp.v_bank_account_balances b on b.bank_account_id=a.id where a.organization_id=$1 and a.deleted_at is null and a.is_active order by a.code", [ctx.orgId]);
    const monthly = await ctx.tx.query("select to_char(s.settlement_date,'YYYY-MM') as month, sum(case when t.direction='receivable' then s.net_amount else 0 end) income, sum(case when t.direction='payable' then s.net_amount else 0 end) expense from erp.title_settlements s join erp.financial_titles t on t.id=s.title_id where t.organization_id=$1 and s.status='confirmed' and s.settlement_date between $2 and $3 and ($4::uuid[] is null or t.farm_id = any($4)) group by 1 order by 1", [ctx.orgId, start, end, fs]);
    return { period: { start, end }, by_cost_center: byCenter.rows.map((r) => ({ ...(r as Record<string, string>), result: (Number((r as { income: string }).income) - Number((r as { expense: string }).expense)).toFixed(2) })), investment_by_category: invByCat.rows, overdue: overdue.rows, upcoming_30d: upcoming.rows, bank_balances: banks.rows, monthly_realized: monthly.rows };
  }));
  app.get("/dashboards/cash-book", async (req) => runService(app, req, "dashboard.cash_book.view", async (ctx) => { const f = q.parse(req.query); const { start, end } = range(f); const r = await ctx.tx.query("select to_char(m.movement_date,'YYYY-MM') as month, sum(case when m.type='in' then m.amount else 0 end) income, sum(case when m.type='out' then m.amount else 0 end) expense, count(*)::int movements, count(*) filter (where m.is_deductible)::int deductible from erp.bank_movements m join erp.bank_accounts ba on ba.id=m.bank_account_id where m.organization_id=$1 and ba.use_cash_book and m.status='confirmed' and m.movement_date between $2 and $3 and ($4::uuid[] is null or m.farm_id is null or m.farm_id = any($4)) group by 1 order by 1", [ctx.orgId, start, end, farms(ctx, f)]); return { period: { start, end }, monthly: r.rows }; }));
  app.get("/dashboards/supply", async (req) => runService(app, req, "dashboard.supply.view", async (ctx) => {
    const f = q.parse(req.query); const { start, end } = range(f); const fs = farms(ctx, f);
    const byStatus = await ctx.tx.query("select status, count(*)::int n, coalesce(sum(estimated_total),0) estimated, coalesce(sum(approved_total),0) approved from erp.purchase_requests where organization_id=$1 and deleted_at is null and request_date between $2 and $3 and ($4::uuid[] is null or farm_id = any($4)) group by 1", [ctx.orgId, start, end, fs]);
    const byType = await ctx.tx.query("select request_type, count(*)::int n, coalesce(sum(coalesce(approved_total,estimated_total)),0) total from erp.purchase_requests where organization_id=$1 and deleted_at is null and request_date between $2 and $3 and ($4::uuid[] is null or farm_id = any($4)) group by 1", [ctx.orgId, start, end, fs]);
    const leadTime = await ctx.tx.query<{ avg_hours: string | null }>("select round(avg(extract(epoch from (select max(created_at) from erp.purchase_request_events e where e.request_id=r.id and e.to_status='finished') - r.created_at)/3600),1) avg_hours from erp.purchase_requests r where r.organization_id=$1 and r.status='finished' and r.request_date between $2 and $3 and ($4::uuid[] is null or r.farm_id = any($4))", [ctx.orgId, start, end, fs]);
    const topProviders = await ctx.tx.query("select pe.name as provider, count(*)::int quotations, count(*) filter (where q.is_selected)::int won, coalesce(sum(q.total) filter (where q.is_selected),0) total from erp.purchase_quotations q join erp.people pe on pe.id=q.provider_id join erp.purchase_requests r on r.id=q.request_id where q.organization_id=$1 and q.quotation_date between $2 and $3 and ($4::uuid[] is null or r.farm_id = any($4)) group by 1 order by 4 desc limit 10", [ctx.orgId, start, end, fs]);
    const sla = await ctx.tx.query("select r.status, count(*)::int n, count(*) filter (where s.max_hours>0 and extract(epoch from now()-r.status_changed_at)/3600 > s.max_hours)::int breached from erp.purchase_requests r left join erp.supply_status_sla s on s.organization_id=r.organization_id and s.status=r.status where r.organization_id=$1 and r.status not in ('finished','cancelled') and ($2::uuid[] is null or r.farm_id = any($2)) group by 1", [ctx.orgId, fs]);
    return { period: { start, end }, by_status: byStatus.rows, by_type: byType.rows, avg_lead_time_hours: leadTime.rows[0]?.avg_hours, top_providers: topProviders.rows, sla: sla.rows };
  }));
  app.get("/dashboards/livestock", async (req) => runService(app, req, "dashboard.livestock.view", async (ctx) => {
    const f = q.parse(req.query); const { start, end } = range(f); const fs = farms(ctx, f);
    const herd = await ctx.tx.query("select c.name as category, count(a.id)::int identified, coalesce((select sum(h.quantity) from erp.herd_lots h where h.organization_id=$1 and h.category_id=c.id and ($2::uuid[] is null or h.farm_id = any($2))),0)::int unidentified, round(avg(a.current_weight),1) avg_weight, coalesce(sum(a.unit_value),0) value from erp.animal_categories c left join erp.animals a on a.category_id=c.id and a.organization_id=$1 and a.status='active' and a.deleted_at is null and ($2::uuid[] is null or a.farm_id = any($2)) where c.organization_id is null or c.organization_id=$1 group by c.id, c.name having count(a.id)>0 or exists (select 1 from erp.herd_lots h where h.organization_id=$1 and h.category_id=c.id) order by c.name", [ctx.orgId, fs]);
    const movements = await ctx.tx.query("select movement_type, count(*)::int n, coalesce(sum(quantity),0)::int heads, coalesce(sum(total_value),0) value, coalesce(sum(total_weight),0) weight from erp.animal_movements where organization_id=$1 and status='confirmed' and movement_date between $2 and $3 and ($4::uuid[] is null or farm_id = any($4)) group by 1", [ctx.orgId, start, end, fs]);
    const gmd = await ctx.tx.query<{ avg_gmd: string | null; weighed: string }>("select round(avg(wi.gmd),3) avg_gmd, count(distinct wi.animal_id) weighed from erp.weighing_items wi join erp.weighings w on w.id=wi.weighing_id where w.organization_id=$1 and w.weighing_date between $2 and $3 and ($4::uuid[] is null or w.farm_id = any($4))", [ctx.orgId, start, end, fs]);
    const repro = await ctx.tx.query<{ matings: string; pregnant: string }>("select count(*) matings, count(*) filter (where result='pregnant') pregnant from erp.matings m where m.organization_id=$1 and m.mating_date between $2 and $3 and ($4::uuid[] is null or exists (select 1 from erp.animals a where a.id=m.dam_id and a.farm_id = any($4)))", [ctx.orgId, start, end, fs]);
    const costs = await ctx.tx.query<{ handling: string; feed: string }>("select coalesce((select sum(total) from erp.animal_handlings h where h.organization_id=$1 and h.handling_date between $2 and $3 and ($4::uuid[] is null or h.farm_id = any($4))),0) handling, coalesce((select sum(cost) from erp.feed_deliveries d where d.organization_id=$1 and d.delivery_date between $2 and $3 and ($4::uuid[] is null or d.farm_id = any($4))),0) feed", [ctx.orgId, start, end, fs]);
    const total = herd.rows.reduce((a, r) => a + Number((r as { identified: number }).identified) + Number((r as { unidentified: number }).unidentified), 0);
    return { period: { start, end }, total_heads: total, herd: herd.rows, movements: movements.rows, avg_gmd: gmd.rows[0]?.avg_gmd, animals_weighed: Number(gmd.rows[0]?.weighed ?? 0), reproduction: { matings: Number(repro.rows[0]!.matings), pregnant: Number(repro.rows[0]!.pregnant), rate: Number(repro.rows[0]!.matings) ? (Number(repro.rows[0]!.pregnant) / Number(repro.rows[0]!.matings) * 100).toFixed(1) : null }, costs: costs.rows[0] };
  }));
  app.get("/dashboards/depreciation", async (req) => runService(app, req, "dashboard.depreciation.view", async (ctx) => { const f = q.parse(req.query); const year = f.year ?? new Date().getFullYear(); const monthly = await ctx.tx.query("select to_char(period_month,'YYYY-MM') as month, sum(amount) amount from erp.depreciations d join erp.equipments e on e.id=d.equipment_id where d.organization_id=$1 and extract(year from period_month)=$2 and ($3::uuid[] is null or e.farm_id = any($3)) group by 1 order by 1", [ctx.orgId, year, allowedFarms(ctx)]); const byFamily = await ctx.tx.query("select coalesce(ef.name,'(sem família)') family, count(*)::int assets, sum(e.acquisition_value) acquisition, sum(e.depreciated_value) depreciated, sum(e.acquisition_value-e.depreciated_value) current_value from erp.equipments e left join erp.equipment_families ef on ef.id=e.family_id where e.organization_id=$1 and e.deleted_at is null and e.status='active' and ($2::uuid[] is null or e.farm_id = any($2)) group by 1 order by 3 desc", [ctx.orgId, allowedFarms(ctx)]); return { year, monthly: monthly.rows, by_family: byFamily.rows }; }));
  app.get("/dashboards/assets", async (req) => runService(app, req, "dashboard.assets.view", async (ctx) => { const r = await ctx.tx.query<{ assets: string; acquisition: string; depreciated: string; current_value: string }>("select count(*) assets, coalesce(sum(acquisition_value),0) acquisition, coalesce(sum(depreciated_value),0) depreciated, coalesce(sum(acquisition_value-depreciated_value),0) current_value from erp.equipments where organization_id=$1 and deleted_at is null and status='active' and ($2::uuid[] is null or farm_id = any($2))", [ctx.orgId, allowedFarms(ctx)]); const byFarm = await ctx.tx.query("select fa.name as farm, count(*)::int assets, sum(e.acquisition_value-e.depreciated_value) current_value from erp.equipments e join erp.farms fa on fa.id=e.farm_id where e.organization_id=$1 and e.deleted_at is null and e.status='active' and ($2::uuid[] is null or e.farm_id = any($2)) group by 1 order by 3 desc", [ctx.orgId, allowedFarms(ctx)]); const byStatus = await ctx.tx.query("select status, count(*)::int n from erp.equipments where organization_id=$1 and deleted_at is null and ($2::uuid[] is null or farm_id = any($2)) group by 1", [ctx.orgId, allowedFarms(ctx)]); const fleet = await ctx.tx.query<{ supplies: string; maintenances: string }>("select coalesce((select sum(total) from erp.fuel_supplies where organization_id=$1 and status='confirmed' and supply_date >= date_trunc('year',current_date) and ($2::uuid[] is null or farm_id = any($2))),0) supplies, coalesce((select sum(total_parts+total_services) from erp.maintenances where organization_id=$1 and status='confirmed' and maintenance_date >= date_trunc('year',current_date) and ($2::uuid[] is null or farm_id = any($2))),0) maintenances", [ctx.orgId, allowedFarms(ctx)]); return { summary: r.rows[0], by_farm: byFarm.rows, by_status: byStatus.rows, fleet_costs_ytd: fleet.rows[0] }; }));
  app.get("/dashboards/user-analysis", async (req) => runService(app, req, "dashboard.user_analysis.view", async (ctx) => { const f = q.parse(req.query); const { start, end } = range(f); const r = await ctx.tx.query("select u.name as user_name, count(*) filter (where a.action='login')::int logins, count(*) filter (where a.action='create')::int creates, count(*) filter (where a.action='update')::int updates, count(*) filter (where a.action not in ('login','create','update'))::int other, max(a.created_at) last_activity from erp.audit_logs a join erp.users u on u.id=a.user_id where (a.organization_id=$1 or (a.organization_id is null and a.user_id in (select user_id from erp.organization_members where organization_id=$1))) and a.created_at::date between $2 and $3 group by 1 order by 2 desc", [ctx.orgId, start, end]); const byEntity = await ctx.tx.query("select entity, count(*)::int n from erp.audit_logs where organization_id=$1 and created_at::date between $2 and $3 group by 1 order by 2 desc limit 15", [ctx.orgId, start, end]); return { period: { start, end }, by_user: r.rows, by_entity: byEntity.rows }; }));
  app.get("/dashboards/rainfall", async (req) => runService(app, req, "dashboard.rainfall.view", async (ctx) => { const f = q.parse(req.query); const year = f.year ?? new Date().getFullYear(); const r = await ctx.tx.query("select fa.name as farm, extract(month from r.date)::int as month, sum(r.millimeters) mm, count(*) filter (where r.millimeters>0)::int rainy_days from erp.rainfalls r join erp.farms fa on fa.id=r.farm_id where r.organization_id=$1 and extract(year from r.date)=$2 and ($3::uuid[] is null or r.farm_id = any($3)) group by 1,2 order by 1,2", [ctx.orgId, year, allowedFarms(ctx)]); const prev = await ctx.tx.query("select extract(month from r.date)::int as month, sum(r.millimeters) mm from erp.rainfalls r where r.organization_id=$1 and extract(year from r.date)=$2 and ($3::uuid[] is null or r.farm_id = any($3)) group by 1 order by 1", [ctx.orgId, year - 1, allowedFarms(ctx)]); return { year, monthly: r.rows, previous_year: prev.rows, total_mm: r.rows.reduce((a, x) => a + Number((x as { mm: string }).mm), 0).toFixed(1) }; }));
  app.get("/dashboards/feedlot", async (req) => runService(app, req, "dashboard.feedlot.view", async (ctx) => { const r = await ctx.tx.query("select y.name as yard, s.name as sector, c.name as corral, c.capacity, (select count(*) from erp.animals a join erp.batches b on b.id=a.batch_id where b.corral_id=c.id and a.status='active')::int occupancy from erp.feedlot_corrals c join erp.feedlot_sectors s on s.id=c.sector_id join erp.feedlot_yards y on y.id=s.yard_id where c.organization_id=$1 and c.deleted_at is null and ($2::uuid[] is null or y.farm_id = any($2)) order by 1,2,3", [ctx.orgId, allowedFarms(ctx)]); const cap = r.rows.reduce((a, x) => a + Number((x as { capacity: number }).capacity), 0); const occ = r.rows.reduce((a, x) => a + Number((x as { occupancy: number }).occupancy), 0); return { corrals: r.rows, capacity: cap, occupancy: occ, occupancy_rate: cap ? (occ / cap * 100).toFixed(1) : null }; }));
  app.get("/dashboards/feedlot-cost", async (req) => runService(app, req, "dashboard.feedlot_cost.view", async (ctx) => { const f = q.parse(req.query); const { start, end } = range(f); const r = await ctx.tx.query("select b.description as batch, (select count(*) from erp.animals a where a.batch_id=b.id and a.status='active')::int animals, coalesce(sum(fd.quantity_kg),0) kg, coalesce(sum(fd.cost),0) cost, (current_date-coalesce(b.entry_date,current_date))::int days from erp.batches b left join erp.feed_deliveries fd on fd.batch_id=b.id and fd.delivery_date between $2 and $3 where b.organization_id=$1 and b.batch_type='feedlot' and b.status='active' and ($4::uuid[] is null or b.farm_id = any($4)) group by b.id, b.description, b.entry_date order by 1", [ctx.orgId, start, end, allowedFarms(ctx)]); return { period: { start, end }, batches: r.rows.map((x) => { const y = x as { animals: number; kg: string; cost: string; days: number }; return { ...y, cost_per_head_day: y.animals && y.days ? (Number(y.cost) / y.animals / y.days).toFixed(2) : null, kg_per_head_day: y.animals && y.days ? (Number(y.kg) / y.animals / y.days).toFixed(2) : null }; }) }; }));
  app.get("/dashboards/feedlot-performance", async (req) => runService(app, req, "dashboard.feedlot_performance.view", async (ctx) => { const r = await ctx.tx.query("select b.description as batch, count(a.id)::int animals, round(avg(a.entry_weight),1) entry_weight, round(avg(a.current_weight),1) current_weight, round(avg(a.current_weight-coalesce(a.entry_weight,a.current_weight)),1) gain, (current_date-coalesce(b.entry_date,current_date))::int days, round(avg(a.current_weight-coalesce(a.entry_weight,a.current_weight))/nullif(current_date-coalesce(b.entry_date,current_date),0),3) gmd from erp.batches b left join erp.animals a on a.batch_id=b.id and a.status='active' where b.organization_id=$1 and b.batch_type='feedlot' and b.status='active' and ($2::uuid[] is null or b.farm_id = any($2)) group by b.id, b.description, b.entry_date order by 1", [ctx.orgId, allowedFarms(ctx)]); return { batches: r.rows }; }));
  app.get("/dashboards/nutrition-stock", async (req) => runService(app, req, "dashboard.nutrition_stock.view", async (ctx) => { const r = await ctx.tx.query("select pr.description as product, sum(sb.quantity) quantity, sum(sb.total_value) value, pr.min_stock, coalesce((select sum(m.quantity) from erp.stock_movements m where m.product_id=pr.id and m.direction=-1 and m.movement_type in ('nutrition','requisition') and m.movement_date >= current_date-30),0) consumed_30d from erp.stock_balances sb join erp.products pr on pr.id=sb.product_id join erp.product_groups g on g.id=pr.group_id join erp.warehouses w on w.id=sb.warehouse_id where sb.organization_id=$1 and (g.name ilike '%pecu%' or g.name ilike '%nutri%' or w.type='formulation') and ($2::uuid[] is null or w.farm_id = any($2)) group by pr.id, pr.description, pr.min_stock order by 1", [ctx.orgId, allowedFarms(ctx)]); return { products: r.rows.map((x) => { const y = x as { quantity: string; consumed_30d: string; min_stock: string | null }; const daily = Number(y.consumed_30d) / 30; return { ...y, days_of_stock: daily > 0 ? Math.floor(Number(y.quantity) / daily) : null, below_min: y.min_stock ? Number(y.quantity) <= Number(y.min_stock) : false }; }) }; }));
  app.get("/dashboards/feed-consumption", async (req) => runService(app, req, "dashboard.feed_consumption.view", async (ctx) => { const f = q.parse(req.query); const { start, end } = range(f); const daily = await ctx.tx.query("select delivery_date, sum(quantity_kg) kg, sum(cost) cost, count(distinct corral_id)::int corrals from erp.feed_deliveries where organization_id=$1 and delivery_date between $2 and $3 and ($4::uuid[] is null or farm_id = any($4)) group by 1 order by 1", [ctx.orgId, start, end, allowedFarms(ctx)]); const byDiet = await ctx.tx.query("select d.name as diet, sum(fd.quantity_kg) kg, sum(fd.cost) cost from erp.feed_deliveries fd left join erp.diets d on d.id=fd.diet_id where fd.organization_id=$1 and fd.delivery_date between $2 and $3 and ($4::uuid[] is null or fd.farm_id = any($4)) group by 1 order by 2 desc", [ctx.orgId, start, end, allowedFarms(ctx)]); return { period: { start, end }, daily: daily.rows, by_diet: byDiet.rows }; }));
}
