import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { D, money, isISODate, todayISO } from "@agro/shared";
import { monthlyDepreciation, depreciationForecast } from "@agro/domain";
import { runService, nextCode, idempotent, audit } from "../lib/service.js";
import { notFound, validation, err } from "../lib/errors.js";
import { farmAllowed, farmScope, farmScopeSql, scopedById, assertFarmVisible, allowedFarms, type ServiceCtx } from "../lib/context.js";
import { pageQuerySchema } from "../lib/pagination.js";
import { wrapListing, hasColumnFilters } from "../lib/column-filters.js";
import { postStock, reverseStock } from "../services/stock-core.js";
import { createTitles } from "../services/financial-core.js";

const dec = z.union([z.number(), z.string()]).transform(String);
const date = z.string().refine(isISODate, "Data inválida");
const uuid = z.string().uuid();
const idem = (req: { headers: Record<string, unknown> }) => req.headers["idempotency-key"] as string | undefined;

/** Listagem paginada; `query` habilita filtros genéricos por coluna (`coluna__operador`, ver lib/column-filters). */
async function list(ctx: ServiceCtx, sql: string, countSql: string, params: unknown[], q: { page: number; pageSize: number }, query?: Record<string, unknown>) {
  if (query && hasColumnFilters(query)) { const w = wrapListing(sql, [...params], query, q); const total = await ctx.tx.query<{ n: string }>(w.countSql, w.params); const r = await ctx.tx.query(w.pageSql, w.params); return { items: r.rows, total: Number(total.rows[0]!.n), page: q.page, pageSize: q.pageSize }; }
  const total = await ctx.tx.query<{ n: string }>(countSql, params);
  const r = await ctx.tx.query(`${sql} limit ${q.pageSize} offset ${(q.page - 1) * q.pageSize}`, params);
  return { items: r.rows, total: Number(total.rows[0]!.n), page: q.page, pageSize: q.pageSize };
}

export default async function fleetHrRoutes(app: FastifyInstance) {
  // ---------- Manutenções ----------
  const maintSchema = z.object({ farm_id: uuid, maintenance_date: date, harvest_id: uuid.optional().nullable(), machines: z.array(z.object({ equipment_id: uuid, hour_meter: dec.optional().nullable(), mileage: dec.optional().nullable(), maintenance_type: z.enum(["employee", "provider"]).optional().nullable(), executor_person_id: uuid.optional().nullable(), hours: dec.optional().nullable(), service_total: dec.default("0"), service_description: z.string().optional().nullable(), items: z.array(z.object({ warehouse_id: uuid.optional().nullable(), product_id: uuid, quantity: dec, unit_value: dec.optional().nullable(), note: z.string().optional().nullable() })).default([]) })).min(1) });
  app.get("/fleet/maintenances", async (req) => runService(app, req, "maintenances.view", async (ctx) => { const q = pageQuerySchema.parse(req.query); const f = req.query as Record<string, string>; const where = ["m.organization_id=$1", "m.deleted_at is null"]; const params: unknown[] = [ctx.orgId]; where.push(...farmScope(ctx, "m", params)); if (f.equipment_id) { params.push(f.equipment_id); where.push(`exists (select 1 from erp.maintenance_machines mm where mm.maintenance_id=m.id and mm.equipment_id=$${params.length})`); } if (f.start_date) { params.push(f.start_date); where.push(`m.maintenance_date>=$${params.length}`); } if (f.end_date) { params.push(f.end_date); where.push(`m.maintenance_date<=$${params.length}`); } const w = where.join(" and "); return list(ctx, `select m.*, u.name as responsible_name, (select string_agg(e.description, ', ') from erp.maintenance_machines mm join erp.equipments e on e.id=mm.equipment_id where mm.maintenance_id=m.id) as machines from erp.maintenances m left join erp.users u on u.id=m.responsible_user_id where ${w} order by m.maintenance_date desc`, `select count(*) n from erp.maintenances m where ${w}`, params, q, req.query as Record<string, unknown>); }));
  app.get("/fleet/maintenances/:id", async (req) => runService(app, req, "maintenances.view", async (ctx) => { const { id } = req.params as { id: string }; const m = await ctx.tx.query("select m.*, u.name as responsible_name from erp.maintenances m left join erp.users u on u.id=m.responsible_user_id where m.id=$1 and m.organization_id=$2" + scopedById(ctx, "m", id).sql, scopedById(ctx, "m", id).params); if (!m.rows[0]) throw notFound(); const machines = await ctx.tx.query("select mm.*, e.description as equipment_name, e.code as equipment_code, p.name as executor_name, (select json_agg(json_build_object('product_id',i.product_id,'product_name',pr.description,'quantity',i.quantity,'unit_value',i.unit_value,'total',i.total,'note',i.note,'warehouse_id',i.warehouse_id)) from erp.maintenance_items i join erp.products pr on pr.id=i.product_id where i.machine_id=mm.id) as items from erp.maintenance_machines mm join erp.equipments e on e.id=mm.equipment_id left join erp.people p on p.id=mm.executor_person_id where mm.maintenance_id=$1", [id]); return { ...m.rows[0], machines: machines.rows }; }));
  app.post("/fleet/maintenances", async (req, reply) => reply.status(201).send(await runService(app, req, "maintenances.create", async (ctx) => {
    const d = maintSchema.parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    return (await idempotent(ctx.tx, ctx.orgId, idem(req), d, async () => {
      const code = await nextCode(ctx.tx, ctx.orgId, "maintenance");
      const r = await ctx.tx.query<{ id: string }>("insert into erp.maintenances(organization_id,farm_id,code,maintenance_date,responsible_user_id,harvest_id,created_by) values ($1,$2,$3,$4,$5,$6,$5) returning id", [ctx.orgId, d.farm_id, code, d.maintenance_date, ctx.user.id, d.harvest_id ?? null]);
      const id = r.rows[0]!.id; let parts = D(0), services = D(0);
      for (const m of d.machines) {
        const mm = await ctx.tx.query<{ id: string }>("insert into erp.maintenance_machines(maintenance_id,equipment_id,hour_meter,mileage,maintenance_type,executor_person_id,hours,service_total,service_description) values ($1,$2,$3,$4,$5,$6,$7,$8,$9) returning id", [id, m.equipment_id, m.hour_meter ?? null, m.mileage ?? null, m.maintenance_type ?? null, m.executor_person_id ?? null, m.hours ?? null, money(m.service_total), m.service_description ?? null]);
        services = services.plus(m.service_total);
        if (m.hour_meter) await ctx.tx.query("update erp.equipments set hour_meter=greatest(coalesce(hour_meter,0),$2) where id=$1", [m.equipment_id, m.hour_meter]);
        for (const it of m.items) {
          let cost = it.unit_value ?? "0";
          if (it.warehouse_id) { const s = await postStock(ctx, { farmId: d.farm_id, warehouseId: it.warehouse_id, productId: it.product_id, movementType: "maintenance", direction: -1, quantity: it.quantity, sourceType: "maintenances", sourceId: id, date: d.maintenance_date, note: `Manutenção ${code}` }); cost = s.unitCost; }
          const t = money(D(it.quantity).mul(cost)); parts = parts.plus(t);
          await ctx.tx.query("insert into erp.maintenance_items(machine_id,warehouse_id,product_id,quantity,unit_value,total,note) values ($1,$2,$3,$4,$5,$6,$7)", [mm.rows[0]!.id, it.warehouse_id ?? null, it.product_id, it.quantity, cost, t, it.note ?? null]);
        }
        // preventivas: atualiza última execução
        await ctx.tx.query("update erp.preventive_maintenances set last_done_date=$2, last_done_value=case trigger_type when 'hours' then coalesce($3::numeric,last_done_value) when 'km' then coalesce($4::numeric,last_done_value) else last_done_value end where equipment_id=$1 and is_active", [m.equipment_id, d.maintenance_date, m.hour_meter ?? null, m.mileage ?? null]);
      }
      await ctx.tx.query("update erp.maintenances set total_parts=$2, total_services=$3 where id=$1", [id, money(parts), money(services)]);
      await audit(ctx.tx, ctx, "maintenances", id, "create", { code });
      return { id, code, total_parts: money(parts), total_services: money(services) };
    })).result;
  })));
  app.post("/fleet/maintenances/:id/cancel", async (req) => runService(app, req, "maintenances.delete", async (ctx) => { const { id } = req.params as { id: string }; const m = await ctx.tx.query<{ status: string; farm_id: string }>("select status, farm_id from erp.maintenances where id=$1 and organization_id=$2 for update", [id, ctx.orgId]); if (!m.rows[0]) throw notFound(); assertFarmVisible(ctx, m.rows[0].farm_id, "Manutenção"); if (m.rows[0].status === "cancelled") throw err("ALREADY_CANCELLED", "Já cancelada"); await reverseStock(ctx, "maintenances", id, todayISO()); await ctx.tx.query("update erp.maintenances set status='cancelled', updated_at=now() where id=$1", [id]); await audit(ctx.tx, ctx, "maintenances", id, "cancel"); return { id, status: "cancelled" }; }));

  // ---------- Abastecimentos ----------
  const supplySchema = z.object({ farm_id: uuid, supply_date: date, equipment_id: uuid, operator_person_id: uuid.optional().nullable(), warehouse_id: uuid.optional().nullable(), product_id: uuid, quantity: dec, unit_value: dec.optional().nullable(), hour_meter: dec.optional().nullable(), mileage: dec.optional().nullable(), cost_center_id: uuid.optional().nullable(), harvest_id: uuid.optional().nullable(), note: z.string().optional().nullable(), origin: z.enum(["manual", "cta_smart", "import"]).default("manual") });
  app.get("/fleet/fuel-supplies", async (req) => runService(app, req, "fuel_supplies.view", async (ctx) => { const q = pageQuerySchema.parse(req.query); const f = req.query as Record<string, string>; const where = ["s.organization_id=$1", "s.deleted_at is null"]; const params: unknown[] = [ctx.orgId]; where.push(...farmScope(ctx, "s", params)); if (f.equipment_id) { params.push(f.equipment_id); where.push(`s.equipment_id=$${params.length}`); } if (f.product_id) { params.push(f.product_id); where.push(`s.product_id=$${params.length}`); } if (f.start_date) { params.push(f.start_date); where.push(`s.supply_date>=$${params.length}`); } if (f.end_date) { params.push(f.end_date); where.push(`s.supply_date<=$${params.length}`); } if (f.origin) { params.push(f.origin); where.push(`s.origin=$${params.length}`); } const w = where.join(" and "); const res = await list(ctx, `select s.*, e.description as equipment_name, e.code as equipment_code, p.description as product_name, op.name as operator_name, w.description as warehouse_name from erp.fuel_supplies s join erp.equipments e on e.id=s.equipment_id join erp.products p on p.id=s.product_id left join erp.people op on op.id=s.operator_person_id left join erp.warehouses w on w.id=s.warehouse_id where ${w} order by s.supply_date desc, s.created_at desc`, `select count(*) n from erp.fuel_supplies s where ${w}`, params, q); const tot = await ctx.tx.query<{ q: string; t: string }>(`select coalesce(sum(s.quantity),0) q, coalesce(sum(s.total),0) t from erp.fuel_supplies s where ${w} and s.status='confirmed'`, params); return { ...res, totals: { quantity: tot.rows[0]!.q, total: tot.rows[0]!.t } }; }));
  // Detalhe de um abastecimento — usado por /frota/abastecimentos/:id
  app.get("/fleet/fuel-supplies/:id", async (req) => runService(app, req, "fuel_supplies.view", async (ctx) => {
    const { id } = req.params as { id: string };
    const r = await ctx.tx.query("select s.*, e.description as equipment_name, e.code as equipment_code, p.description as product_name, op.name as operator_name, w.description as warehouse_name, f.name as farm_name, cc.name as cost_center_name, hv.description as harvest_name from erp.fuel_supplies s join erp.equipments e on e.id=s.equipment_id join erp.products p on p.id=s.product_id left join erp.people op on op.id=s.operator_person_id left join erp.warehouses w on w.id=s.warehouse_id join erp.farms f on f.id=s.farm_id left join erp.cost_centers cc on cc.id=s.cost_center_id left join erp.harvests hv on hv.id=s.harvest_id where s.id=$1 and s.organization_id=$2 and s.deleted_at is null" + scopedById(ctx, "s", id).sql, scopedById(ctx, "s", id).params);
    if (!r.rows[0]) throw notFound("Abastecimento");
    return r.rows[0];
  }));
  app.post("/fleet/fuel-supplies", async (req, reply) => reply.status(201).send(await runService(app, req, "fuel_supplies.create", async (ctx) => {
    const d = supplySchema.parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    return (await idempotent(ctx.tx, ctx.orgId, idem(req), d, async () => {
      const code = await nextCode(ctx.tx, ctx.orgId, "fuel_supply", 5);
      const r = await ctx.tx.query<{ id: string }>("insert into erp.fuel_supplies(organization_id,farm_id,code,supply_date,equipment_id,operator_person_id,warehouse_id,product_id,quantity,hour_meter,mileage,cost_center_id,harvest_id,origin,note,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) returning id", [ctx.orgId, d.farm_id, code, d.supply_date, d.equipment_id, d.operator_person_id ?? null, d.warehouse_id ?? null, d.product_id, d.quantity, d.hour_meter ?? null, d.mileage ?? null, d.cost_center_id ?? null, d.harvest_id ?? null, d.origin, d.note ?? null, ctx.user.id]);
      let cost = d.unit_value ?? "0";
      if (d.warehouse_id) { const s = await postStock(ctx, { farmId: d.farm_id, warehouseId: d.warehouse_id, productId: d.product_id, movementType: "fuel_supply", direction: -1, quantity: d.quantity, costCenterId: d.cost_center_id, harvestId: d.harvest_id, sourceType: "fuel_supplies", sourceId: r.rows[0]!.id, date: d.supply_date, note: `Abastecimento ${code}` }); cost = s.unitCost; }
      const total = money(D(d.quantity).mul(cost));
      await ctx.tx.query("update erp.fuel_supplies set unit_value=$2, total=$3 where id=$1", [r.rows[0]!.id, cost, total]);
      if (d.hour_meter) await ctx.tx.query("update erp.equipments set hour_meter=greatest(coalesce(hour_meter,0),$2) where id=$1", [d.equipment_id, d.hour_meter]);
      await audit(ctx.tx, ctx, "fuel_supplies", r.rows[0]!.id, "create", { code });
      return { id: r.rows[0]!.id, code, total };
    })).result;
  })));
  app.post("/fleet/fuel-supplies/:id/cancel", async (req) => runService(app, req, "fuel_supplies.delete", async (ctx) => { const { id } = req.params as { id: string }; const s = await ctx.tx.query<{ status: string; farm_id: string }>("select status, farm_id from erp.fuel_supplies where id=$1 and organization_id=$2 for update", [id, ctx.orgId]); if (!s.rows[0]) throw notFound(); assertFarmVisible(ctx, s.rows[0].farm_id, "Abastecimento"); if (s.rows[0].status === "cancelled") throw err("ALREADY_CANCELLED", "Já cancelado"); await reverseStock(ctx, "fuel_supplies", id, todayISO()); await ctx.tx.query("update erp.fuel_supplies set status='cancelled' where id=$1", [id]); return { id, status: "cancelled" }; }));
  // Transferência de máquinas entre fazendas
  app.get("/fleet/equipment-transfers", async (req) => runService(app, req, "equipment_transfers.view", async (ctx) => { const r = await ctx.tx.query("select t.*, e.description as equipment_name, fo.name as origin_farm_name, fd.name as destination_farm_name, u.name as created_by_name from erp.equipment_transfers t join erp.equipments e on e.id=t.equipment_id join erp.farms fo on fo.id=t.origin_farm_id join erp.farms fd on fd.id=t.destination_farm_id left join erp.users u on u.id=t.created_by where t.organization_id=$1 and ($2::uuid[] is null or t.origin_farm_id = any($2) or t.destination_farm_id = any($2)) order by t.transfer_date desc limit 200", [ctx.orgId, allowedFarms(ctx)]); return { items: r.rows, total: r.rowCount }; }));
  app.post("/fleet/equipment-transfers", async (req, reply) => reply.status(201).send(await runService(app, req, "equipment_transfers.create", async (ctx) => { const d = z.object({ equipment_id: uuid, destination_farm_id: uuid, transfer_date: date, note: z.string().optional().nullable() }).parse(req.body); const e = await ctx.tx.query<{ farm_id: string }>("select farm_id from erp.equipments where id=$1 and organization_id=$2 for update", [d.equipment_id, ctx.orgId]); if (!e.rows[0]) throw notFound("Bem"); assertFarmVisible(ctx, e.rows[0].farm_id, "Bem"); if (!farmAllowed(ctx, d.destination_farm_id)) throw validation("Sem acesso à fazenda destino"); if (e.rows[0].farm_id === d.destination_farm_id) throw validation("Bem já está na fazenda destino"); const code = await nextCode(ctx.tx, ctx.orgId, "equipment_transfer"); const r = await ctx.tx.query<{ id: string }>("insert into erp.equipment_transfers(organization_id,code,transfer_date,equipment_id,origin_farm_id,destination_farm_id,note,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8) returning id", [ctx.orgId, code, d.transfer_date, d.equipment_id, e.rows[0].farm_id, d.destination_farm_id, d.note ?? null, ctx.user.id]); await ctx.tx.query("update erp.equipments set farm_id=$2, updated_at=now() where id=$1", [d.equipment_id, d.destination_farm_id]); await audit(ctx.tx, ctx, "equipments", d.equipment_id, "transfer", d); return { id: r.rows[0]!.id, code }; })));
  // Preventivas vencidas / revisões pendentes (monitoramento)
  app.get("/fleet/alerts", async (req) => runService(app, req, "preventive_maintenances.view", async (ctx) => { const prev = await ctx.tx.query("select pm.*, e.description as equipment_name, e.hour_meter as current_value, case pm.trigger_type when 'days' then (current_date - coalesce(pm.last_done_date, e.acquisition_date, current_date)) >= pm.interval_value else coalesce(e.hour_meter,0) - coalesce(pm.last_done_value,0) >= pm.interval_value end as due from erp.preventive_maintenances pm join erp.equipments e on e.id=pm.equipment_id where pm.organization_id=$1 and pm.is_active and pm.deleted_at is null and ($2::uuid[] is null or e.farm_id = any($2)) order by e.description", [ctx.orgId, allowedFarms(ctx)]); const rev = await ctx.tx.query("select r.*, e.description as equipment_name from erp.scheduled_reviews r join erp.equipments e on e.id=r.equipment_id where r.organization_id=$1 and r.status='scheduled' and r.deleted_at is null and ($2::uuid[] is null or e.farm_id = any($2)) order by r.scheduled_date", [ctx.orgId, allowedFarms(ctx)]); return { preventives: prev.rows, reviews: rev.rows }; }));

  // ---------- Depreciação ----------
  app.post("/assets/depreciations/run", async (req, reply) => reply.status(201).send(await runService(app, req, "depreciations.create", async (ctx) => {
    const d = z.object({ period_month: date, farm_id: uuid.optional().nullable() }).parse(req.body);
    const month = d.period_month.slice(0, 7) + "-01"; if (d.farm_id && !farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    return (await idempotent(ctx.tx, ctx.orgId, idem(req), d, async () => {
      const eqs = await ctx.tx.query<{ id: string; acquisition_value: string; residual_percent: string | null; life_years: string | null; depreciation_type: string | null; depreciated_value: string; acquisition_date: string | null }>("select id, acquisition_value, residual_percent, life_years, depreciation_type, depreciated_value, acquisition_date from erp.equipments where organization_id=$1 and has_depreciation and status='active' and deleted_at is null and ($2::uuid[] is null or farm_id = any($2)) and (acquisition_date is null or acquisition_date <= ($3::date + interval '1 month' - interval '1 day')) for update", [ctx.orgId, allowedFarms(ctx, d.farm_id ?? null), month]);
      let count = 0, total = D(0);
      for (const e of eqs.rows) {
        if (!e.life_years || D(e.life_years).lte(0)) continue;
        const calc = monthlyDepreciation({ acquisitionValue: e.acquisition_value, residualPercent: e.residual_percent, lifeYears: e.life_years, type: (e.depreciation_type as "with_residual") ?? "without_residual" });
        const remaining = D(calc.depreciableValue).minus(e.depreciated_value); if (remaining.lte(0)) continue;
        const amount = D(calc.monthly).gt(remaining) ? remaining : D(calc.monthly);
        const ins = await ctx.tx.query("insert into erp.depreciations(organization_id,equipment_id,period_month,amount,accumulated,created_by) values ($1,$2,$3,$4,$5,$6) on conflict (equipment_id,period_month) do nothing returning id", [ctx.orgId, e.id, month, money(amount), money(D(e.depreciated_value).plus(amount)), ctx.user.id]);
        if (ins.rowCount) { await ctx.tx.query("update erp.equipments set depreciated_value=depreciated_value+$2, residual_value=$3, depreciable_value=$4 where id=$1", [e.id, money(amount), calc.residualValue, calc.depreciableValue]); count++; total = total.plus(amount); }
      }
      await audit(ctx.tx, ctx, "depreciations", month, "run", { count, total: money(total) });
      return { period_month: month, count, total: money(total) };
    })).result;
  })));
  app.get("/assets/depreciations", async (req) => runService(app, req, "depreciations.view", async (ctx) => { const q = pageQuerySchema.parse(req.query); const f = req.query as Record<string, string>; const where = ["d.organization_id=$1"]; const params: unknown[] = [ctx.orgId]; if (f.equipment_id) { params.push(f.equipment_id); where.push(`d.equipment_id=$${params.length}`); } if (f.period_month) { params.push(f.period_month.slice(0, 7) + "-01"); where.push(`d.period_month=$${params.length}`); } where.push(...farmScope(ctx, "e", params)); const w = where.join(" and "); return list(ctx, `select d.*, e.code as equipment_code, e.description as equipment_name, e.acquisition_value, f.name as farm_name from erp.depreciations d join erp.equipments e on e.id=d.equipment_id join erp.farms f on f.id=e.farm_id where ${w} order by d.period_month desc, e.description`, `select count(*) n from erp.depreciations d join erp.equipments e on e.id=d.equipment_id where ${w}`, params, q, req.query as Record<string, unknown>); }));
  app.get("/assets/depreciation-forecast", async (req) => runService(app, req, "depreciation_forecast.view", async (ctx) => { const f = req.query as Record<string, string>; const months = Math.min(Number(f.months ?? 12), 120); const from = (f.from ?? todayISO()).slice(0, 7) + "-01"; const eqs = await ctx.tx.query<{ id: string; code: string; description: string; acquisition_value: string; residual_percent: string | null; life_years: string | null; depreciation_type: string | null; depreciated_value: string }>("select id, code, description, acquisition_value, residual_percent, life_years, depreciation_type, depreciated_value from erp.equipments where organization_id=$1 and has_depreciation and status='active' and deleted_at is null and ($2::uuid[] is null or farm_id = any($2)) order by description", [ctx.orgId, allowedFarms(ctx)]); return { items: eqs.rows.filter((e) => e.life_years && D(e.life_years).gt(0)).map((e) => { const c = monthlyDepreciation({ acquisitionValue: e.acquisition_value, residualPercent: e.residual_percent, lifeYears: e.life_years!, type: (e.depreciation_type as "with_residual") ?? "without_residual" }); return { equipment_id: e.id, code: e.code, description: e.description, monthly: c.monthly, depreciable: c.depreciableValue, depreciated: e.depreciated_value, forecast: depreciationForecast(c.depreciableValue, e.depreciated_value, c.monthly, from, months) }; }) }; }));

  // ---------- Gestão pessoal: adiantamentos e apuração mensal ----------
  app.get("/hr/advances", async (req) => runService(app, req, "salary_advances.view", async (ctx) => { const q = pageQuerySchema.parse(req.query); const f = req.query as Record<string, string>; const where = ["a.organization_id=$1", "a.deleted_at is null"]; const params: unknown[] = [ctx.orgId]; if (f.person_id) { params.push(f.person_id); where.push(`a.person_id=$${params.length}`); } if (f.status) { params.push(f.status); where.push(`a.status=$${params.length}`); } if (f.start_date) { params.push(f.start_date); where.push(`a.advance_date>=$${params.length}`); } if (f.end_date) { params.push(f.end_date); where.push(`a.advance_date<=$${params.length}`); } where.push(...farmScope(ctx, "a", params)); const w = where.join(" and "); return list(ctx, `select a.*, p.name as person_name, f.name as farm_name, t.status as title_status, t.balance as title_balance from erp.salary_advances a join erp.people p on p.id=a.person_id join erp.farms f on f.id=a.farm_id left join erp.financial_titles t on t.id=a.title_id where ${w} order by a.advance_date desc`, `select count(*) n from erp.salary_advances a where ${w}`, params, q, req.query as Record<string, unknown>); }));
  app.post("/hr/advances", async (req, reply) => reply.status(201).send(await runService(app, req, "salary_advances.create", async (ctx) => {
    const d = z.object({ farm_id: uuid, advance_date: date, person_id: uuid, amount: dec, installments: z.number().int().min(1).max(12).default(1), note: z.string().optional().nullable(), due_date: date.optional(), financial_category_id: uuid.optional(), cost_center_id: uuid.optional() }).parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    return (await idempotent(ctx.tx, ctx.orgId, idem(req), d, async () => {
      const code = await nextCode(ctx.tx, ctx.orgId, "salary_advance");
      const r = await ctx.tx.query<{ id: string }>("insert into erp.salary_advances(organization_id,farm_id,code,advance_date,person_id,amount,installments,note,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9) returning id", [ctx.orgId, d.farm_id, code, d.advance_date, d.person_id, money(d.amount), d.installments, d.note ?? null, ctx.user.id]);
      const cat = d.financial_category_id ?? (await ctx.tx.query<{ id: string }>("select id from erp.financial_categories where organization_id=$1 and nature='expense' and kind='analytic' and (name ilike '%salár%' or name ilike '%folha%') and deleted_at is null limit 1", [ctx.orgId])).rows[0]?.id;
      const cc = d.cost_center_id ?? (await ctx.tx.query<{ id: string }>("select coalesce(e.cost_center_id,(select id from erp.cost_centers where organization_id=$1 and kind='analytic' and deleted_at is null order by code limit 1)) as id from erp.employee_profiles e where e.person_id=$2", [ctx.orgId, d.person_id])).rows[0]?.id;
      if (!cat || !cc) throw validation("Informe categoria financeira e centro de custo");
      const t = await createTitles(ctx, { farmId: d.farm_id, direction: "payable", number: `ADT-${code}`, personId: d.person_id, paymentType: "advance", amount: money(d.amount), emissionDate: d.advance_date, dueDate: d.due_date ?? d.advance_date, note: `Adiantamento salarial ${code}`, apportionment: [{ financialCategoryId: cat, costCenterId: cc, percentage: "100" }], sourceType: "salary_advances", sourceId: r.rows[0]!.id, plan: d.installments > 1 ? { installments: d.installments, first_due_date: d.due_date ?? d.advance_date, mode: "interval", interval_days: 30, has_down_payment: false } : null });
      await ctx.tx.query("update erp.salary_advances set title_id=$2 where id=$1", [r.rows[0]!.id, t.ids[0]]);
      await audit(ctx.tx, ctx, "salary_advances", r.rows[0]!.id, "create", { code });
      return { id: r.rows[0]!.id, code, title_ids: t.ids };
    })).result;
  })));
  // Apuração mensal: consolida salário base + eventos fixos + registros de eventos + faltas
  app.get("/hr/earnings", async (req) => runService(app, req, "earnings.view", async (ctx) => { const r = await ctx.tx.query("select e.*, f.name as farm_name, (select count(distinct person_id) from erp.earning_lines l where l.earning_id=e.id)::int as employees from erp.earnings e join erp.farms f on f.id=e.farm_id where e.organization_id=$1 and ($2::uuid[] is null or e.farm_id = any($2)) order by e.reference_month desc", [ctx.orgId, allowedFarms(ctx)]); return { items: r.rows, total: r.rowCount }; }));
  app.get("/hr/earnings/:id", async (req) => runService(app, req, "earnings.view", async (ctx) => { const { id } = req.params as { id: string }; const e = await ctx.tx.query("select * from erp.earnings where id=$1 and organization_id=$2" + scopedById(ctx, "farm_id", id).sql, scopedById(ctx, "farm_id", id).params); if (!e.rows[0]) throw notFound(); const lines = await ctx.tx.query("select l.*, p.name as person_name from erp.earning_lines l join erp.people p on p.id=l.person_id where l.earning_id=$1 order by p.name, l.condition desc", [id]); return { ...e.rows[0], lines: lines.rows }; }));
  app.post("/hr/earnings/calculate", async (req, reply) => reply.status(201).send(await runService(app, req, "earnings.create", async (ctx) => {
    const d = z.object({ farm_id: uuid, reference_month: date }).parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda"); const month = d.reference_month.slice(0, 7) + "-01";
    const existing = await ctx.tx.query<{ id: string; status: string }>("select id, status from erp.earnings where organization_id=$1 and farm_id=$2 and reference_month=$3", [ctx.orgId, d.farm_id, month]);
    if (existing.rows[0] && existing.rows[0].status !== "open") throw err("ALREADY_CONFIRMED", "Apuração já fechada");
    const code = existing.rows[0] ? null : await nextCode(ctx.tx, ctx.orgId, "earnings");
    const id = existing.rows[0]?.id ?? (await ctx.tx.query<{ id: string }>("insert into erp.earnings(organization_id,farm_id,code,reference_month,created_by) values ($1,$2,$3,$4,$5) returning id", [ctx.orgId, d.farm_id, code, month, ctx.user.id])).rows[0]!.id;
    await ctx.tx.query("delete from erp.earning_lines where earning_id=$1", [id]);
    const emps = await ctx.tx.query<{ person_id: string; base_salary: string | null; hour_value: string | null; monthly_hours: number | null }>("select e.person_id, coalesce(e.base_salary, jf.base_salary) as base_salary, coalesce(e.hour_value, jf.hour_value) as hour_value, jf.monthly_hours from erp.employee_profiles e join erp.people p on p.id=e.person_id left join erp.job_functions jf on jf.id=e.function_id where p.organization_id=$1 and e.is_active and p.deleted_at is null and (e.dismissal_date is null or e.dismissal_date >= $2)", [ctx.orgId, month]);
    let earn = D(0), ded = D(0);
    for (const e of emps.rows) {
      const base = D(e.base_salary ?? 0); if (base.gt(0)) { await ctx.tx.query("insert into erp.earning_lines(earning_id,person_id,description,condition,amount) values ($1,$2,'Salário base','add',$3)", [id, e.person_id, money(base)]); earn = earn.plus(base); }
      const fixed = await ctx.tx.query<{ name: string; condition: string; amount: string }>("select ev.name, ev.condition, ee.amount from erp.employee_events ee join erp.hr_events ev on ev.id=ee.event_id where ee.person_id=$1 and ee.is_active and ev.is_active and ev.method='fixed'", [e.person_id]);
      for (const f of fixed.rows) { await ctx.tx.query("insert into erp.earning_lines(earning_id,person_id,description,condition,amount) values ($1,$2,$3,$4,$5)", [id, e.person_id, f.name, f.condition, money(f.amount)]); if (f.condition === "add") earn = earn.plus(f.amount); else ded = ded.plus(f.amount); }
      const inf = await ctx.tx.query<{ name: string; condition: string; amount: string; event_id: string }>("select ev.name, ev.condition, sum(b.amount*b.quantity) as amount, ev.id as event_id from erp.bonuses b join erp.hr_events ev on ev.id=b.event_id where b.person_id=$1 and b.deleted_at is null and date_trunc('month',b.reference_month)=$2::date group by ev.id, ev.name, ev.condition", [e.person_id, month]);
      for (const f of inf.rows) { await ctx.tx.query("insert into erp.earning_lines(earning_id,person_id,event_id,description,condition,amount) values ($1,$2,$3,$4,$5,$6)", [id, e.person_id, f.event_id, f.name, f.condition, money(f.amount)]); if (f.condition === "add") earn = earn.plus(f.amount); else ded = ded.plus(f.amount); }
      const abs = await ctx.tx.query<{ n: string }>("select count(*) n from erp.absences where person_id=$1 and deleted_at is null and kind in ('absence') and date_trunc('month',absence_date)=$2::date", [e.person_id, month]);
      const days = Number(abs.rows[0]!.n); if (days > 0 && base.gt(0)) { const disc = base.div(30).mul(days).toDecimalPlaces(2); await ctx.tx.query("insert into erp.earning_lines(earning_id,person_id,description,condition,amount) values ($1,$2,$3,'subtract',$4)", [id, e.person_id, `Faltas (${days} dia(s))`, money(disc)]); ded = ded.plus(disc); }
      const adv = await ctx.tx.query<{ amount: string }>("select coalesce(sum(t.balance),0) amount from erp.salary_advances a join erp.financial_titles t on t.id=a.title_id where a.person_id=$1 and a.status='open' and date_trunc('month',t.due_date)=$2::date", [e.person_id, month]);
      if (D(adv.rows[0]!.amount).gt(0)) { await ctx.tx.query("insert into erp.earning_lines(earning_id,person_id,description,condition,amount) values ($1,$2,'Adiantamento salarial','subtract',$3)", [id, e.person_id, money(adv.rows[0]!.amount)]); ded = ded.plus(adv.rows[0]!.amount); }
    }
    await ctx.tx.query("update erp.earnings set total_earnings=$2, total_deductions=$3, total_net=$4, updated_at=now() where id=$1", [id, money(earn), money(ded), money(earn.minus(ded))]);
    await audit(ctx.tx, ctx, "earnings", id, "calculate", { employees: emps.rowCount });
    return { id, employees: emps.rowCount, total_earnings: money(earn), total_deductions: money(ded), total_net: money(earn.minus(ded)) };
  })));
  app.post("/hr/earnings/:id/generate-financial", async (req) => runService(app, req, "earnings.generate_financial", async (ctx) => {
    const { id } = req.params as { id: string }; const d = z.object({ due_date: date, financial_category_id: uuid, cost_center_id: uuid }).parse(req.body);
    const e = await ctx.tx.query<{ status: string; farm_id: string; reference_month: string; code: string }>("select status, farm_id, reference_month, code from erp.earnings where id=$1 and organization_id=$2 for update", [id, ctx.orgId]); if (!e.rows[0]) throw notFound(); assertFarmVisible(ctx, e.rows[0].farm_id, "Apuração"); if (e.rows[0].status === "financial_generated") throw err("ALREADY_CONFIRMED", "Financeiro já gerado");
    const per = await ctx.tx.query<{ person_id: string; net: string }>("select person_id, sum(case when condition='add' then amount else -amount end) net from erp.earning_lines where earning_id=$1 group by person_id", [id]);
    const ids: string[] = [];
    for (const p of per.rows) { if (D(p.net).lte(0)) continue; const t = await createTitles(ctx, { farmId: e.rows[0].farm_id, direction: "payable", number: `FOLHA-${e.rows[0].code}`, personId: p.person_id, amount: money(p.net), emissionDate: todayISO(), dueDate: d.due_date, note: `Folha ${e.rows[0].reference_month.slice(0, 7)}`, apportionment: [{ financialCategoryId: d.financial_category_id, costCenterId: d.cost_center_id, percentage: "100" }], sourceType: "earnings", sourceId: id }); ids.push(...t.ids); }
    await ctx.tx.query("update erp.earnings set status='financial_generated', updated_at=now() where id=$1", [id]);
    await audit(ctx.tx, ctx, "earnings", id, "generate_financial", { titles: ids.length });
    return { id, title_ids: ids };
  }));
  app.post("/hr/earnings/:id/close", async (req) => runService(app, req, "earnings.edit", async (ctx) => { const { id } = req.params as { id: string }; const cp: unknown[] = [id, ctx.orgId]; await ctx.tx.query("update erp.earnings set status='closed', updated_at=now() where id=$1 and organization_id=$2 and status='open'" + farmScopeSql(ctx, "farm_id", cp), cp); return { id, status: "closed" }; }));

  // ---------- Ordens de serviço ----------
  const osSchema = z.object({ farm_id: uuid, order_date: date, harvest_id: uuid.optional().nullable(), activity_id: uuid.optional().nullable(), operation_id: uuid.optional().nullable(), cost_center_id: uuid.optional().nullable(), responsible_person_id: uuid.optional().nullable(), team_id: uuid.optional().nullable(), description: z.string().optional().nullable(), planned_start: date.optional().nullable(), planned_end: date.optional().nullable(), lines: z.array(z.object({ section: z.enum(["labor", "machine", "input", "production", "ppe"]), person_id: uuid.optional().nullable(), equipment_id: uuid.optional().nullable(), product_id: uuid.optional().nullable(), warehouse_id: uuid.optional().nullable(), quantity: dec.default("0"), unit_value: dec.default("0"), hours: dec.optional().nullable(), note: z.string().optional().nullable() })).default([]) });
  app.get("/service-orders", async (req) => runService(app, req, "service_orders.view", async (ctx) => { const q = pageQuerySchema.parse(req.query); const f = req.query as Record<string, string>; const where = ["o.organization_id=$1", "o.deleted_at is null"]; const params: unknown[] = [ctx.orgId]; where.push(...farmScope(ctx, "o", params)); if (f.status) { params.push(f.status); where.push(`o.status=$${params.length}`); } if (f.mine === "1") { params.push(ctx.user.id); where.push(`o.created_by=$${params.length}`); } if (f.late === "1") where.push("o.planned_end < current_date and o.status in ('open','in_progress')"); if (f.start_date) { params.push(f.start_date); where.push(`o.order_date>=$${params.length}`); } if (f.end_date) { params.push(f.end_date); where.push(`o.order_date<=$${params.length}`); } const w = where.join(" and "); return list(ctx, `select o.*, a.name as activity_name, op.name as operation_name, p.name as responsible_name, t.name as team_name from erp.service_orders o left join erp.activities a on a.id=o.activity_id left join erp.operations op on op.id=o.operation_id left join erp.people p on p.id=o.responsible_person_id left join erp.teams t on t.id=o.team_id where ${w} order by o.order_date desc`, `select count(*) n from erp.service_orders o where ${w}`, params, q, req.query as Record<string, unknown>); }));
  app.get("/service-orders/:id", async (req) => runService(app, req, "service_orders.view", async (ctx) => { const { id } = req.params as { id: string }; const o = await ctx.tx.query("select o.*, a.name as activity_name, op.name as operation_name, p.name as responsible_name, t.name as team_name, cc.name as cost_center_name from erp.service_orders o left join erp.activities a on a.id=o.activity_id left join erp.operations op on op.id=o.operation_id left join erp.people p on p.id=o.responsible_person_id left join erp.teams t on t.id=o.team_id left join erp.cost_centers cc on cc.id=o.cost_center_id where o.id=$1 and o.organization_id=$2" + scopedById(ctx, "o", id).sql, scopedById(ctx, "o", id).params); if (!o.rows[0]) throw notFound(); const lines = await ctx.tx.query("select l.*, p.name as person_name, e.description as equipment_name, pr.description as product_name from erp.service_order_lines l left join erp.people p on p.id=l.person_id left join erp.equipments e on e.id=l.equipment_id left join erp.products pr on pr.id=l.product_id where l.order_id=$1 order by l.section", [id]); return { ...o.rows[0], lines: lines.rows }; }));
  app.post("/service-orders", async (req, reply) => reply.status(201).send(await runService(app, req, "service_orders.create", async (ctx) => { const d = osSchema.parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda"); const code = await nextCode(ctx.tx, ctx.orgId, "service_order"); const r = await ctx.tx.query<{ id: string }>("insert into erp.service_orders(organization_id,farm_id,code,order_date,harvest_id,activity_id,operation_id,cost_center_id,responsible_person_id,team_id,description,planned_start,planned_end,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning id", [ctx.orgId, d.farm_id, code, d.order_date, d.harvest_id ?? null, d.activity_id ?? null, d.operation_id ?? null, d.cost_center_id ?? null, d.responsible_person_id ?? null, d.team_id ?? null, d.description ?? null, d.planned_start ?? null, d.planned_end ?? null, ctx.user.id]); await saveLines(ctx, r.rows[0]!.id, d.lines); return { id: r.rows[0]!.id, code }; })));
  app.put("/service-orders/:id", async (req) => runService(app, req, "service_orders.edit", async (ctx) => { const { id } = req.params as { id: string }; const d = osSchema.parse(req.body); const cur = await ctx.tx.query<{ status: string; farm_id: string }>("select status, farm_id from erp.service_orders where id=$1 and organization_id=$2 for update", [id, ctx.orgId]); if (!cur.rows[0]) throw notFound(); assertFarmVisible(ctx, cur.rows[0].farm_id, "OS"); if (["finished", "evaluated", "cancelled"].includes(cur.rows[0].status)) throw err("INVALID_STATUS_TRANSITION", "OS encerrada"); await ctx.tx.query("update erp.service_orders set order_date=$3, harvest_id=$4, activity_id=$5, operation_id=$6, cost_center_id=$7, responsible_person_id=$8, team_id=$9, description=$10, planned_start=$11, planned_end=$12, updated_at=now() where id=$1 and organization_id=$2", [id, ctx.orgId, d.order_date, d.harvest_id ?? null, d.activity_id ?? null, d.operation_id ?? null, d.cost_center_id ?? null, d.responsible_person_id ?? null, d.team_id ?? null, d.description ?? null, d.planned_start ?? null, d.planned_end ?? null]); await saveLines(ctx, id, d.lines); return { id }; }));
  async function saveLines(ctx: ServiceCtx, id: string, lines: z.infer<typeof osSchema>["lines"]) {
    await ctx.tx.query("delete from erp.service_order_lines where order_id=$1", [id]);
    const tot: Record<string, ReturnType<typeof D>> = { labor: D(0), machine: D(0), input: D(0), production: D(0), ppe: D(0) };
    for (const l of lines) { const t = D(l.quantity).mul(l.unit_value); tot[l.section] = tot[l.section]!.plus(t); await ctx.tx.query("insert into erp.service_order_lines(order_id,section,person_id,equipment_id,product_id,warehouse_id,quantity,unit_value,total,hours,note) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)", [id, l.section, l.person_id ?? null, l.equipment_id ?? null, l.product_id ?? null, l.warehouse_id ?? null, l.quantity, l.unit_value, money(t), l.hours ?? null, l.note ?? null]); }
    const inputs = tot.input!.plus(tot.ppe!);
    await ctx.tx.query("update erp.service_orders set labor_total=$2, machines_total=$3, inputs_total=$4, total=$5 where id=$1", [id, money(tot.labor!), money(tot.machine!), money(inputs), money(tot.labor!.plus(tot.machine!).plus(inputs))]);
  }
  app.post("/service-orders/:id/status", async (req) => runService(app, req, "service_orders.edit", async (ctx) => {
    const { id } = req.params as { id: string }; const d = z.object({ status: z.enum(["in_progress", "finished", "cancelled"]) }).parse(req.body);
    const cur = await ctx.tx.query<{ status: string; farm_id: string; order_date: string; code: string }>("select status, farm_id, order_date, code from erp.service_orders where id=$1 and organization_id=$2 for update", [id, ctx.orgId]); if (!cur.rows[0]) throw notFound(); assertFarmVisible(ctx, cur.rows[0].farm_id, "OS");
    const allowed: Record<string, string[]> = { open: ["in_progress", "cancelled"], in_progress: ["finished", "cancelled"] };
    if (!allowed[cur.rows[0].status]?.includes(d.status)) throw err("INVALID_STATUS_TRANSITION", `De ${cur.rows[0].status} para ${d.status}`);
    if (d.status === "finished") { // baixa insumos/EPIs do estoque ao finalizar
      const ins = await ctx.tx.query<{ product_id: string; warehouse_id: string | null; quantity: string }>("select product_id, warehouse_id, quantity from erp.service_order_lines where order_id=$1 and section in ('input','ppe') and product_id is not null", [id]);
      for (const l of ins.rows) if (l.warehouse_id && D(l.quantity).gt(0)) await postStock(ctx, { farmId: cur.rows[0].farm_id, warehouseId: l.warehouse_id, productId: l.product_id, movementType: "requisition", direction: -1, quantity: l.quantity, sourceType: "service_orders", sourceId: id, date: todayISO(), note: `OS ${cur.rows[0].code}` });
    }
    await ctx.tx.query("update erp.service_orders set status=$2, started_at=case when $2='in_progress' then now() else started_at end, finished_at=case when $2='finished' then now() else finished_at end, updated_at=now() where id=$1", [id, d.status]);
    await audit(ctx.tx, ctx, "service_orders", id, d.status); return { id, status: d.status };
  }));
  app.post("/service-orders/:id/rate", async (req) => runService(app, req, "service_orders.rate", async (ctx) => { const { id } = req.params as { id: string }; const d = z.object({ rating: z.number().int().min(1).max(5), rating_note: z.string().optional().nullable() }).parse(req.body); const rp: unknown[] = [id, ctx.orgId, d.rating, d.rating_note ?? null]; const u = await ctx.tx.query("update erp.service_orders set rating=$3, rating_note=$4, status='evaluated', updated_at=now() where id=$1 and organization_id=$2 and status='finished'" + farmScopeSql(ctx, "farm_id", rp) + " returning id", rp); if (!u.rowCount) throw err("INVALID_STATUS_TRANSITION", "Somente OS finalizadas podem ser avaliadas"); return { id, rating: d.rating }; }));
  app.get("/service-orders-monitoring", async (req) => runService(app, req, "service_orders.monitor", async (ctx) => { const r = await ctx.tx.query("select status, count(*)::int as n, coalesce(sum(total),0) as total from erp.service_orders where organization_id=$1 and deleted_at is null and ($2::uuid[] is null or farm_id = any($2)) group by status", [ctx.orgId, allowedFarms(ctx)]); const late = await ctx.tx.query("select id, code, description, planned_end, status from erp.service_orders where organization_id=$1 and status in ('open','in_progress') and planned_end < current_date and deleted_at is null and ($2::uuid[] is null or farm_id = any($2)) order by planned_end", [ctx.orgId, allowedFarms(ctx)]); return { by_status: r.rows, late: late.rows }; }));
}
