import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { D, money, isISODate, todayISO } from "@agro/shared";
import { gmd, withdrawalUntil, expectedBirth, ageMonths, evolveCategory } from "@agro/domain";
import { runService, nextCode, idempotent, audit, requirePermission } from "../lib/service.js";
import { notFound, validation, err } from "../lib/errors.js";
import { farmAllowed, farmScope, scopedById, assertFarmVisible, allowedFarms, type ServiceCtx } from "../lib/context.js";
import { pageQuerySchema } from "../lib/pagination.js";
import { wrapListing, hasColumnFilters } from "../lib/column-filters.js";
import { postStock } from "../services/stock-core.js";
import { createTitles } from "../services/financial-core.js";

const dec = z.union([z.number(), z.string()]).transform(String);
const date = z.string().refine(isISODate, "Data inválida");
const uuid = z.string().uuid();
const idem = (req: { headers: Record<string, unknown> }) => req.headers["idempotency-key"] as string | undefined;

async function paged(ctx: ServiceCtx, sql: string, countSql: string, params: unknown[], q: { page: number; pageSize: number }, query?: Record<string, unknown>) {
  if (query && hasColumnFilters(query)) { const w = wrapListing(sql, [...params], query, q); const total = await ctx.tx.query<{ n: string }>(w.countSql, w.params); const r = await ctx.tx.query(w.pageSql, w.params); return { items: r.rows, total: Number(total.rows[0]!.n), page: q.page, pageSize: q.pageSize }; }
  const total = await ctx.tx.query<{ n: string }>(countSql, params);
  const r = await ctx.tx.query(`${sql} limit ${q.pageSize} offset ${(q.page - 1) * q.pageSize}`, params);
  return { items: r.rows, total: Number(total.rows[0]!.n), page: q.page, pageSize: q.pageSize };
}
async function animalCode(ctx: ServiceCtx, entity: string) { return nextCode(ctx.tx, ctx.orgId, entity, 5); }
/** Código único por organização na tabela (a unicidade é por tabela, não por tipo): sequência única por tabela; pula códigos já usados por sequências antigas por tipo. */
async function uniqueCode(ctx: ServiceCtx, table: "animal_handlings", entity: string) {
  for (let i = 0; i < 10000; i++) { const code = await animalCode(ctx, entity); const ex = await ctx.tx.query(`select 1 from erp.${table} where organization_id=$1 and code=$2`, [ctx.orgId, code]); if (!ex.rowCount) return code; }
  throw new Error("Não foi possível gerar código único");
}

export default async function livestockRoutes(app: FastifyInstance) {
  // ---------- Animais ----------
  app.get("/livestock/animals", async (req) => runService(app, req, "animals.view", async (ctx) => {
    const q = pageQuerySchema.parse(req.query); const f = req.query as Record<string, string>;
    const where = ["a.organization_id=$1", "a.deleted_at is null"]; const params: unknown[] = [ctx.orgId];
    const add = (s: string, v: unknown) => { params.push(v); where.push(s.replace("?", `$${params.length}`)); };
    if (f.farm_id) add("a.farm_id=?", f.farm_id); else if (ctx.farmId) add("a.farm_id=?", ctx.farmId);
    if (ctx.membership.farmIds.length) add("a.farm_id = any(?::uuid[])", ctx.membership.farmIds);
    if (f.status) add("a.status=?", f.status); else where.push("a.status='active'");
    if (f.batch_id) add("a.batch_id=?", f.batch_id); if (f.category_id) add("a.category_id=?", f.category_id); if (f.breed_id) add("a.breed_id=?", f.breed_id); if (f.sex) add("a.sex=?", f.sex);
    if (f.search) add("exists (select 1 from erp.animal_identifications i where i.animal_id=a.id and i.value ilike ?)", `%${f.search}%`);
    const w = where.join(" and ");
    const res = await paged(ctx, `select a.*, c.name as category_name, b.name as breed_name, bt.description as batch_name, f.name as farm_name, (select string_agg(i.value, ', ' order by i.is_primary desc) from erp.animal_identifications i where i.animal_id=a.id) as identifications, (select string_agg(t.name||': '||i.value, '; ') from erp.animal_identifications i join erp.identification_types t on t.id=i.identification_type_id where i.animal_id=a.id) as identifications_detail from erp.animals a join erp.animal_categories c on c.id=a.category_id left join erp.breeds b on b.id=a.breed_id left join erp.batches bt on bt.id=a.batch_id join erp.farms f on f.id=a.farm_id where ${w} order by a.entry_date desc, a.created_at desc`, `select count(*) n from erp.animals a where ${w}`, params, q, req.query as Record<string, unknown>);
    const tot = await ctx.tx.query<{ weight: string; value: string }>(`select coalesce(sum(a.current_weight),0) weight, coalesce(sum(a.unit_value),0) value from erp.animals a where ${w}`, params);
    return { ...res, totals: { weight: tot.rows[0]!.weight, value: tot.rows[0]!.value } };
  }));
  app.get("/livestock/animals/:id", async (req) => runService(app, req, "animals.view", async (ctx) => {
    const { id } = req.params as { id: string };
    const a = await ctx.tx.query("select a.*, c.name as category_name, b.name as breed_name, bt.description as batch_name, f.name as farm_name, s.name as species_name, m.id as mother_id_ref, pr.name as origin_provider_name from erp.animals a join erp.animal_categories c on c.id=a.category_id left join erp.breeds b on b.id=a.breed_id left join erp.batches bt on bt.id=a.batch_id join erp.farms f on f.id=a.farm_id join erp.animal_species s on s.id=a.species_id left join erp.animals m on m.id=a.mother_id left join erp.people pr on pr.id=a.origin_provider_id where a.id=$1 and a.organization_id=$2 and a.deleted_at is null" + scopedById(ctx, "a", id).sql, scopedById(ctx, "a", id).params); if (!a.rows[0]) throw notFound("Animal");
    const ids = await ctx.tx.query("select i.*, t.name as type_name from erp.animal_identifications i join erp.identification_types t on t.id=i.identification_type_id where i.animal_id=$1", [id]);
    const weighings = await ctx.tx.query("select w.weighing_date, wi.weight, wi.previous_weight, wi.gmd from erp.weighing_items wi join erp.weighings w on w.id=wi.weighing_id where wi.animal_id=$1 order by w.weighing_date", [id]);
    const handlings = await ctx.tx.query("select h.handling_type, h.handling_date, h.code, p.description as product_name, hi.dose, h.withdrawal_until from erp.animal_handling_items hi join erp.animal_handlings h on h.id=hi.handling_id left join erp.products p on p.id=h.product_id where hi.animal_id=$1 order by h.handling_date desc", [id]);
    const movements = await ctx.tx.query("select m.movement_type, m.movement_date, m.code, mi.weight, mi.unit_value from erp.animal_movement_items mi join erp.animal_movements m on m.id=mi.movement_id where mi.animal_id=$1 order by m.movement_date desc", [id]);
    const matings = await ctx.tx.query("select m.*, s.name as sire_name from erp.matings m left join erp.breeding_sires s on s.id=m.sire_id where m.dam_id=$1 order by m.mating_date desc", [id]);
    const children = await ctx.tx.query("select a.id, a.birth_date, a.sex, c.name as category_name, (select string_agg(i.value, ', ') from erp.animal_identifications i where i.animal_id=a.id) as identifications from erp.animals a join erp.animal_categories c on c.id=a.category_id where a.mother_id=$1 or a.father_id=$1", [id]);
    const costs = await ctx.tx.query<{ total: string }>("select coalesce(sum(hi.quantity * coalesce(h.unit_value,0)),0) total from erp.animal_handling_items hi join erp.animal_handlings h on h.id=hi.handling_id where hi.animal_id=$1", [id]);
    return { ...a.rows[0], identifications: ids.rows, weighings: weighings.rows, handlings: handlings.rows, movements: movements.rows, matings: matings.rows, children: children.rows, handling_cost: costs.rows[0]!.total };
  }));
  const animalSchema = z.object({ farm_id: uuid, species_id: uuid, category_id: uuid, breed_id: uuid.optional().nullable(), batch_id: uuid.optional().nullable(), sex: z.enum(["M", "F"]).optional().nullable(), entry_date: date, birth_date: date.optional().nullable(), reproductive_stage: z.enum(["lactation", "multiparous", "heifer", "nulliparous", "primiparous"]).optional().nullable(), reproductive_status: z.enum(["pregnant", "empty", "calved"]).optional().nullable(), current_weight: dec.optional().nullable(), price_kg_alive: dec.optional().nullable(), price_arroba_alive: dec.optional().nullable(), unit_value: dec.optional().nullable(), mother_ref: z.string().optional().nullable(), father_ref: z.string().optional().nullable(), fur_description: z.string().optional().nullable(), birth_forecast: date.optional().nullable(), proprietary_id: uuid.optional().nullable(), origin_provider_id: uuid.optional().nullable(), note: z.string().optional().nullable(), depreciation: z.record(z.string(), z.unknown()).optional().nullable(), identifications: z.array(z.object({ identification_type_id: uuid, value: z.string().min(1), is_primary: z.boolean().default(false) })).default([]), quantity: z.number().int().min(1).default(1), type: z.enum(["individual", "unidentified"]).default("individual") });
  app.post("/livestock/animals", async (req, reply) => reply.status(201).send(await runService(app, req, "animals.create", async (ctx) => {
    const d = animalSchema.parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    return (await idempotent(ctx.tx, ctx.orgId, idem(req), d, async () => {
      if (d.type === "unidentified") { const r = await ctx.tx.query<{ id: string }>("insert into erp.herd_lots(organization_id,farm_id,batch_id,species_id,category_id,breed_id,quantity,average_weight,unit_value,entry_date) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id", [ctx.orgId, d.farm_id, d.batch_id ?? null, d.species_id, d.category_id, d.breed_id ?? null, d.quantity, d.current_weight ?? null, d.unit_value ?? null, d.entry_date]); return { herd_lot_id: r.rows[0]!.id, quantity: d.quantity }; }
      if (!d.identifications.length) throw validation("Animal individual exige ao menos uma identificação");
      const mother = d.mother_ref ? (await ctx.tx.query<{ animal_id: string }>("select animal_id from erp.animal_identifications where organization_id=$1 and value=$2 limit 1", [ctx.orgId, d.mother_ref])).rows[0]?.animal_id ?? null : null;
      const father = d.father_ref ? (await ctx.tx.query<{ animal_id: string }>("select animal_id from erp.animal_identifications where organization_id=$1 and value=$2 limit 1", [ctx.orgId, d.father_ref])).rows[0]?.animal_id ?? null : null;
      const a = await ctx.tx.query<{ id: string }>("insert into erp.animals(organization_id,farm_id,species_id,category_id,breed_id,batch_id,sex,entry_date,birth_date,reproductive_stage,reproductive_status,current_weight,entry_weight,price_kg_alive,price_arroba_alive,unit_value,ua,mother_id,father_id,mother_ref,father_ref,fur_description,birth_forecast,proprietary_id,origin_provider_id,note,depreciation,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27) returning id", [ctx.orgId, d.farm_id, d.species_id, d.category_id, d.breed_id ?? null, d.batch_id ?? null, d.sex ?? null, d.entry_date, d.birth_date ?? null, d.reproductive_stage ?? null, d.reproductive_status ?? null, d.current_weight ?? null, d.price_kg_alive ?? null, d.price_arroba_alive ?? null, d.unit_value ?? null, d.current_weight ? D(d.current_weight).div(450).toFixed(3) : null, mother, father, d.mother_ref ?? null, d.father_ref ?? null, d.fur_description ?? null, d.birth_forecast ?? null, d.proprietary_id ?? null, d.origin_provider_id ?? null, d.note ?? null, JSON.stringify(d.depreciation ?? {}), ctx.user.id]);
      for (const [i, ident] of d.identifications.entries()) await ctx.tx.query("insert into erp.animal_identifications(animal_id,organization_id,identification_type_id,value,is_primary) values ($1,$2,$3,$4,$5)", [a.rows[0]!.id, ctx.orgId, ident.identification_type_id, ident.value, ident.is_primary || i === 0]);
      await audit(ctx.tx, ctx, "animals", a.rows[0]!.id, "create");
      return { id: a.rows[0]!.id };
    })).result;
  })));
  app.put("/livestock/animals/:id", async (req) => runService(app, req, "animals.edit", async (ctx) => {
    const { id } = req.params as { id: string }; const d = animalSchema.partial().parse(req.body);
    const cur = await ctx.tx.query<{ farm_id: string }>("select farm_id from erp.animals where id=$1 and organization_id=$2 and deleted_at is null for update", [id, ctx.orgId]); if (!cur.rows[0]) throw notFound("Animal"); assertFarmVisible(ctx, cur.rows[0].farm_id, "Animal");
    await ctx.tx.query("update erp.animals set category_id=coalesce($3,category_id), breed_id=coalesce($4,breed_id), batch_id=coalesce($5,batch_id), sex=coalesce($6,sex), birth_date=coalesce($7,birth_date), reproductive_stage=coalesce($8,reproductive_stage), reproductive_status=coalesce($9,reproductive_status), current_weight=coalesce($10,current_weight), price_arroba_alive=coalesce($11,price_arroba_alive), unit_value=coalesce($12,unit_value), fur_description=coalesce($13,fur_description), birth_forecast=coalesce($14,birth_forecast), proprietary_id=coalesce($15,proprietary_id), note=coalesce($16,note), updated_at=now() where id=$1 and organization_id=$2", [id, ctx.orgId, d.category_id ?? null, d.breed_id ?? null, d.batch_id ?? null, d.sex ?? null, d.birth_date ?? null, d.reproductive_stage ?? null, d.reproductive_status ?? null, d.current_weight ?? null, d.price_arroba_alive ?? null, d.unit_value ?? null, d.fur_description ?? null, d.birth_forecast ?? null, d.proprietary_id ?? null, d.note ?? null]);
    if (d.identifications) { await ctx.tx.query("delete from erp.animal_identifications where animal_id=$1", [id]); for (const [i, ident] of d.identifications.entries()) await ctx.tx.query("insert into erp.animal_identifications(animal_id,organization_id,identification_type_id,value,is_primary) values ($1,$2,$3,$4,$5)", [id, ctx.orgId, ident.identification_type_id, ident.value, ident.is_primary || i === 0]); }
    return { id };
  }));
  app.get("/livestock/herd-lots", async (req) => runService(app, req, "animals.view", async (ctx) => { const r = await ctx.tx.query("select h.*, c.name as category_name, b.name as breed_name, bt.description as batch_name, f.name as farm_name from erp.herd_lots h join erp.animal_categories c on c.id=h.category_id left join erp.breeds b on b.id=h.breed_id left join erp.batches bt on bt.id=h.batch_id join erp.farms f on f.id=h.farm_id where h.organization_id=$1 and h.quantity>0 and ($2::uuid[] is null or h.farm_id = any($2)) order by f.name, c.name", [ctx.orgId, allowedFarms(ctx)]); return { items: r.rows, total: r.rowCount, total_quantity: r.rows.reduce((a, x) => a + (x as { quantity: number }).quantity, 0) }; }));
  // Localiza animal (busca por identificação em todas as fazendas)
  app.get("/livestock/locate", async (req) => runService(app, req, "locate_animals.view", async (ctx) => { const { search } = req.query as { search?: string }; if (!search) return { items: [] }; const r = await ctx.tx.query("select a.id, a.status, i.value as identification, t.name as identification_type, f.name as farm_name, bt.description as batch_name, gm.description as module_name, ar.name as area_name, c.name as category_name from erp.animal_identifications i join erp.animals a on a.id=i.animal_id join erp.identification_types t on t.id=i.identification_type_id join erp.farms f on f.id=a.farm_id left join erp.batches bt on bt.id=a.batch_id left join erp.grazing_modules gm on gm.id=bt.grazing_module_id left join erp.areas ar on ar.id=bt.area_id join erp.animal_categories c on c.id=a.category_id where i.organization_id=$1 and i.value ilike $2 and ($3::uuid[] is null or a.farm_id = any($3)) limit 50", [ctx.orgId, `%${search}%`, ctx.membership.farmIds.length ? ctx.membership.farmIds : null]); return { items: r.rows }; }));

  // ---------- Movimentações: compra, venda, nascimento, morte, perda ----------
  const movSchema = z.object({ farm_id: uuid, movement_type: z.enum(["purchase", "sale", "birth", "death", "loss"]), movement_date: date, person_id: uuid.optional().nullable(), batch_id: uuid.optional().nullable(), cause: z.string().optional().nullable(), note: z.string().optional().nullable(), invoice_number: z.string().optional().nullable(), generate_financial: z.boolean().default(false), due_date: date.optional().nullable(), financial_category_id: uuid.optional().nullable(), cost_center_id: uuid.optional().nullable(), items: z.array(z.object({ animal_id: uuid.optional().nullable(), herd_lot_id: uuid.optional().nullable(), category_id: uuid.optional().nullable(), breed_id: uuid.optional().nullable(), sex: z.enum(["M", "F"]).optional().nullable(), quantity: z.number().int().min(1).default(1), weight: dec.optional().nullable(), unit_value: dec.optional().nullable(), identifications: z.array(z.object({ identification_type_id: uuid, value: z.string().min(1) })).optional(), mother_id: uuid.optional().nullable(), father_id: uuid.optional().nullable(), birth_date: date.optional().nullable() })).min(1) });
  app.get("/livestock/movements", async (req) => runService(app, req, "animal_sales.view", async (ctx) => { const q = pageQuerySchema.parse(req.query); const f = req.query as Record<string, string>; const where = ["m.organization_id=$1", "m.deleted_at is null"]; const params: unknown[] = [ctx.orgId]; if (f.movement_type) { params.push(f.movement_type); where.push(`m.movement_type=$${params.length}`); } where.push(...farmScope(ctx, "m", params)); if (f.start_date) { params.push(f.start_date); where.push(`m.movement_date>=$${params.length}`); } if (f.end_date) { params.push(f.end_date); where.push(`m.movement_date<=$${params.length}`); } if (f.person_id) { params.push(f.person_id); where.push(`m.person_id=$${params.length}`); } const w = where.join(" and "); return paged(ctx, `select m.*, p.name as person_name, b.description as batch_name, f.name as farm_name, u.name as created_by_name from erp.animal_movements m left join erp.people p on p.id=m.person_id left join erp.batches b on b.id=m.batch_id join erp.farms f on f.id=m.farm_id left join erp.users u on u.id=m.created_by where ${w} order by m.movement_date desc, m.created_at desc`, `select count(*) n from erp.animal_movements m where ${w}`, params, q, req.query as Record<string, unknown>); }));
  app.get("/livestock/movements/:id", async (req) => runService(app, req, "animal_sales.view", async (ctx) => { const { id } = req.params as { id: string }; const m = await ctx.tx.query("select m.*, p.name as person_name, b.description as batch_name, f.name as farm_name from erp.animal_movements m left join erp.people p on p.id=m.person_id left join erp.batches b on b.id=m.batch_id join erp.farms f on f.id=m.farm_id where m.id=$1 and m.organization_id=$2" + scopedById(ctx, "m", id).sql, scopedById(ctx, "m", id).params); if (!m.rows[0]) throw notFound(); const items = await ctx.tx.query("select mi.*, c.name as category_name, (select string_agg(i.value, ', ') from erp.animal_identifications i where i.animal_id=mi.animal_id) as identifications from erp.animal_movement_items mi left join erp.animal_categories c on c.id=coalesce(mi.new_category_id, mi.category_id) where mi.movement_id=$1", [id]); return { ...m.rows[0], items: items.rows }; }));
  app.post("/livestock/movements", async (req, reply) => reply.status(201).send(await runService(app, req, "animal_sales.create", async (ctx) => {
    const d = movSchema.parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    const permMap = { purchase: "animal_purchases.create", sale: "animal_sales.create", birth: "animal_births.create", death: "animal_deaths.create", loss: "animal_losses.create" } as const;
    const { requirePermission } = await import("../lib/service.js"); requirePermission(ctx, permMap[d.movement_type]);
    return (await idempotent(ctx.tx, ctx.orgId, idem(req), d, async () => {
      const code = await animalCode(ctx, `animal_${d.movement_type}`);
      const r = await ctx.tx.query<{ id: string }>("insert into erp.animal_movements(organization_id,farm_id,code,movement_type,movement_date,person_id,batch_id,cause,note,invoice_number,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning id", [ctx.orgId, d.farm_id, code, d.movement_type, d.movement_date, d.person_id ?? null, d.batch_id ?? null, d.cause ?? null, d.note ?? null, d.invoice_number ?? null, ctx.user.id]);
      const id = r.rows[0]!.id; let qty = 0, weight = D(0), value = D(0);
      const species = (await ctx.tx.query<{ id: string }>("select id from erp.animal_species where organization_id is null order by name limit 1")).rows[0]!.id;
      for (const it of d.items) {
        const total = money(D(it.unit_value ?? 0).mul(it.quantity)); value = value.plus(total); weight = weight.plus(D(it.weight ?? 0).mul(it.quantity)); qty += it.quantity;
        let animalId = it.animal_id ?? null;
        if (d.movement_type === "purchase" || d.movement_type === "birth") {
          if (!it.category_id) throw validation("Categoria obrigatória para entrada de animais");
          if (it.identifications?.length) {
            const a = await ctx.tx.query<{ id: string }>("insert into erp.animals(organization_id,farm_id,species_id,category_id,breed_id,batch_id,sex,entry_date,birth_date,current_weight,entry_weight,unit_value,mother_id,father_id,origin_provider_id,status,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10,$11,$12,$13,$14,'active',$15) returning id", [ctx.orgId, d.farm_id, species, it.category_id, it.breed_id ?? null, d.batch_id ?? null, it.sex ?? null, d.movement_date, it.birth_date ?? (d.movement_type === "birth" ? d.movement_date : null), it.weight ?? null, it.unit_value ?? null, it.mother_id ?? null, it.father_id ?? null, d.movement_type === "purchase" ? d.person_id ?? null : null, ctx.user.id]);
            animalId = a.rows[0]!.id;
            for (const [i, ident] of it.identifications.entries()) await ctx.tx.query("insert into erp.animal_identifications(animal_id,organization_id,identification_type_id,value,is_primary) values ($1,$2,$3,$4,$5)", [animalId, ctx.orgId, ident.identification_type_id, ident.value, i === 0]);
            if (d.movement_type === "birth" && it.mother_id) await ctx.tx.query("update erp.animals set reproductive_status='calved' where id=$1", [it.mother_id]);
          } else {
            const hl = await ctx.tx.query<{ id: string }>("insert into erp.herd_lots(organization_id,farm_id,batch_id,species_id,category_id,breed_id,quantity,average_weight,unit_value,entry_date) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id", [ctx.orgId, d.farm_id, d.batch_id ?? null, species, it.category_id, it.breed_id ?? null, it.quantity, it.weight ?? null, it.unit_value ?? null, d.movement_date]);
            await ctx.tx.query("insert into erp.animal_movement_items(movement_id,herd_lot_id,category_id,quantity,weight,unit_value,total) values ($1,$2,$3,$4,$5,$6,$7)", [id, hl.rows[0]!.id, it.category_id, it.quantity, it.weight ?? null, it.unit_value ?? null, total]); continue;
          }
        } else {
          const newStatus = d.movement_type === "sale" ? "sold" : d.movement_type === "death" ? "dead" : "lost";
          if (animalId) { const a = await ctx.tx.query<{ status: string }>("select status from erp.animals where id=$1 and organization_id=$2 for update", [animalId, ctx.orgId]); if (!a.rows[0]) throw notFound("Animal"); if (a.rows[0].status !== "active") throw err("ANIMAL_NOT_ACTIVE", "Animal não está ativo no rebanho"); await ctx.tx.query("update erp.animals set status=$2, exit_date=$3, updated_at=now() where id=$1", [animalId, newStatus, d.movement_date]); }
          else if (it.herd_lot_id) { const hl = await ctx.tx.query<{ quantity: number }>("select quantity from erp.herd_lots where id=$1 and organization_id=$2 for update", [it.herd_lot_id, ctx.orgId]); if (!hl.rows[0] || hl.rows[0].quantity < it.quantity) throw err("INSUFFICIENT_STOCK", "Quantidade do lote insuficiente"); await ctx.tx.query("update erp.herd_lots set quantity=quantity-$2, updated_at=now() where id=$1", [it.herd_lot_id, it.quantity]); }
          else throw validation("Informe o animal ou o lote sem identificação");
        }
        await ctx.tx.query("insert into erp.animal_movement_items(movement_id,animal_id,herd_lot_id,category_id,quantity,weight,unit_value,total) values ($1,$2,$3,$4,$5,$6,$7,$8)", [id, animalId, it.herd_lot_id ?? null, it.category_id ?? null, it.quantity, it.weight ?? null, it.unit_value ?? null, total]);
      }
      await ctx.tx.query("update erp.animal_movements set quantity=$2, total_weight=$3, total_value=$4 where id=$1", [id, qty, weight.toFixed(2), money(value)]);
      let titleIds: string[] = [];
      if (d.generate_financial && (d.movement_type === "purchase" || d.movement_type === "sale") && value.gt(0)) {
        if (!d.person_id) throw validation("Fornecedor/cliente obrigatório para gerar financeiro");
        const cat = d.financial_category_id ?? (await ctx.tx.query<{ id: string }>("select id from erp.financial_categories where organization_id=$1 and nature=$2 and kind='analytic' and deleted_at is null and (name ilike '%animais%' or name ilike '%boi%' or name ilike '%bezerro%') order by code limit 1", [ctx.orgId, d.movement_type === "purchase" ? "expense" : "income"])).rows[0]?.id ?? (await ctx.tx.query<{ id: string }>("select id from erp.financial_categories where organization_id=$1 and nature=$2 and kind='analytic' and deleted_at is null order by code limit 1", [ctx.orgId, d.movement_type === "purchase" ? "expense" : "income"])).rows[0]?.id;
        const cc = d.cost_center_id ?? (await ctx.tx.query<{ id: string }>("select id from erp.cost_centers where organization_id=$1 and kind='analytic' and deleted_at is null order by code limit 1", [ctx.orgId])).rows[0]?.id;
        if (!cat || !cc) throw validation("Cadastre categoria financeira e centro de custo");
        const t = await createTitles(ctx, { farmId: d.farm_id, direction: d.movement_type === "purchase" ? "payable" : "receivable", number: d.invoice_number ?? `ANI-${code}`, personId: d.person_id, amount: money(value), emissionDate: d.movement_date, dueDate: d.due_date ?? d.movement_date, note: `${d.movement_type === "purchase" ? "Compra" : "Venda"} de animais ${code} (${qty} cab.)`, apportionment: [{ financialCategoryId: cat, costCenterId: cc, percentage: "100" }], sourceType: "animal_movements", sourceId: id });
        titleIds = t.ids; await ctx.tx.query("update erp.animal_movements set financial_title_id=$2 where id=$1", [id, t.ids[0]]);
      }
      if (d.movement_type === "purchase" && qty > 0) { const pcode = await animalCode(ctx, "processing"); await ctx.tx.query("insert into erp.processings(organization_id,farm_id,code,processing_date,purchase_movement_id,pre_batch_id,expected_quantity,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8)", [ctx.orgId, d.farm_id, pcode, d.movement_date, id, d.batch_id ?? null, qty, ctx.user.id]); await ctx.tx.query("insert into erp.notifications(organization_id,kind,title,route) values ($1,'processing_pending',$2,$3)", [ctx.orgId, `Você tem animais a serem processados no processamento nº ${pcode}`, `/pecuaria/processamentos`]); }
      await audit(ctx.tx, ctx, "animal_movements", id, "create", { code, type: d.movement_type, qty });
      return { id, code, quantity: qty, total_value: money(value), title_ids: titleIds };
    })).result;
  })));
  app.post("/livestock/movements/:id/cancel", async (req) => runService(app, req, "animal_sales.delete", async (ctx) => {
    const { id } = req.params as { id: string }; const m = await ctx.tx.query<{ status: string; movement_type: string; farm_id: string }>("select status, movement_type, farm_id from erp.animal_movements where id=$1 and organization_id=$2 for update", [id, ctx.orgId]); if (!m.rows[0]) throw notFound(); assertFarmVisible(ctx, m.rows[0].farm_id, "Movimentação"); if (m.rows[0].status === "cancelled") throw err("ALREADY_CANCELLED", "Já cancelado");
    const paid = await ctx.tx.query("select 1 from erp.financial_titles where source_type='animal_movements' and source_id=$1 and paid_amount>0", [id]); if (paid.rowCount) throw err("CONFLICT", "Títulos com baixa");
    const items = await ctx.tx.query<{ animal_id: string | null; herd_lot_id: string | null; quantity: number }>("select animal_id, herd_lot_id, quantity from erp.animal_movement_items where movement_id=$1", [id]);
    for (const it of items.rows) {
      if (["sale", "death", "loss"].includes(m.rows[0].movement_type)) { if (it.animal_id) await ctx.tx.query("update erp.animals set status='active', exit_date=null where id=$1", [it.animal_id]); if (it.herd_lot_id) await ctx.tx.query("update erp.herd_lots set quantity=quantity+$2 where id=$1", [it.herd_lot_id, it.quantity]); }
      else { if (it.animal_id) await ctx.tx.query("update erp.animals set deleted_at=now(), status='inventoried' where id=$1", [it.animal_id]); if (it.herd_lot_id) await ctx.tx.query("update erp.herd_lots set quantity=greatest(quantity-$2,0) where id=$1", [it.herd_lot_id, it.quantity]); }
    }
    await ctx.tx.query("update erp.financial_titles set status='cancelled' where source_type='animal_movements' and source_id=$1", [id]);
    await ctx.tx.query("update erp.animal_movements set status='cancelled', updated_at=now() where id=$1", [id]); await ctx.tx.query("update erp.processings set status='cancelled' where purchase_movement_id=$1", [id]);
    await audit(ctx.tx, ctx, "animal_movements", id, "cancel"); return { id, status: "cancelled" };
  }));

  // ---------- Transferências: animais/lote, agrupar lotes, lote/fazenda, animal/fazenda, lote/módulo/área ----------
  app.post("/livestock/transfers/animals-to-batch", async (req, reply) => reply.status(201).send(await runService(app, req, "animal_batch_transfer.create", async (ctx) => {
    const d = z.object({ farm_id: uuid, movement_date: date, animal_ids: z.array(uuid).min(1), destination_batch_id: uuid, note: z.string().optional().nullable() }).parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    const b = await ctx.tx.query<{ status: string; farm_id: string }>("select status, farm_id from erp.batches where id=$1 and organization_id=$2", [d.destination_batch_id, ctx.orgId]); if (!b.rows[0]) throw notFound("Lote"); if (b.rows[0].status !== "active") throw err("BATCH_CLOSED", "Lote encerrado");
    const code = await animalCode(ctx, "animal_batch_transfer");
    const r = await ctx.tx.query<{ id: string }>("insert into erp.animal_movements(organization_id,farm_id,code,movement_type,movement_date,destination_batch_id,quantity,note,created_by) values ($1,$2,$3,'batch_transfer',$4,$5,$6,$7,$8) returning id", [ctx.orgId, d.farm_id, code, d.movement_date, d.destination_batch_id, d.animal_ids.length, d.note ?? null, ctx.user.id]);
    for (const a of d.animal_ids) { const u = await ctx.tx.query("update erp.animals set batch_id=$2, updated_at=now() where id=$1 and organization_id=$3 and status='active' returning id", [a, d.destination_batch_id, ctx.orgId]); if (!u.rowCount) throw err("ANIMAL_NOT_ACTIVE", `Animal ${a} inativo`); await ctx.tx.query("insert into erp.animal_movement_items(movement_id,animal_id,quantity) values ($1,$2,1)", [r.rows[0]!.id, a]); }
    return { id: r.rows[0]!.id, code, moved: d.animal_ids.length };
  })));
  app.post("/livestock/transfers/group-batches", async (req, reply) => reply.status(201).send(await runService(app, req, "batch_grouping.create", async (ctx) => {
    const d = z.object({ farm_id: uuid, movement_date: date, source_batch_ids: z.array(uuid).min(1), destination_batch_id: uuid, close_sources: z.boolean().default(true) }).parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    const code = await animalCode(ctx, "animal_batch_transfer"); let n = 0;
    const r = await ctx.tx.query<{ id: string }>("insert into erp.animal_movements(organization_id,farm_id,code,movement_type,movement_date,destination_batch_id,created_by) values ($1,$2,$3,'batch_transfer',$4,$5,$6) returning id", [ctx.orgId, d.farm_id, code, d.movement_date, d.destination_batch_id, ctx.user.id]);
    for (const s of d.source_batch_ids) { if (s === d.destination_batch_id) continue; const u = await ctx.tx.query("update erp.animals set batch_id=$2 where batch_id=$1 and organization_id=$3 and status='active' returning id", [s, d.destination_batch_id, ctx.orgId]); n += u.rowCount ?? 0; await ctx.tx.query("update erp.herd_lots set batch_id=$2 where batch_id=$1", [s, d.destination_batch_id]); if (d.close_sources) await ctx.tx.query("update erp.batches set status='closed', exit_date=$2 where id=$1", [s, d.movement_date]); }
    await ctx.tx.query("update erp.animal_movements set quantity=$2 where id=$1", [r.rows[0]!.id, n]); return { id: r.rows[0]!.id, code, moved: n };
  })));
  app.post("/livestock/transfers/batch-to-module-area", async (req, reply) => reply.status(201).send(await runService(app, req, "batch_module_area_transfer.create", async (ctx) => {
    const d = z.object({ farm_id: uuid, movement_date: date, batch_id: uuid, grazing_module_id: uuid.optional().nullable(), area_id: uuid.optional().nullable(), corral_id: uuid.optional().nullable(), note: z.string().optional().nullable() }).parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    const code = await animalCode(ctx, "batch_area_transfer");
    const u = await ctx.tx.query("update erp.batches set grazing_module_id=$2, area_id=$3, corral_id=$4, updated_at=now() where id=$1 and organization_id=$5 returning id", [d.batch_id, d.grazing_module_id ?? null, d.area_id ?? null, d.corral_id ?? null, ctx.orgId]); if (!u.rowCount) throw notFound("Lote");
    const n = (await ctx.tx.query<{ n: string }>("select count(*) n from erp.animals where batch_id=$1 and status='active'", [d.batch_id])).rows[0]!.n;
    const r = await ctx.tx.query<{ id: string }>("insert into erp.animal_movements(organization_id,farm_id,code,movement_type,movement_date,batch_id,destination_module_id,destination_area_id,quantity,note,created_by) values ($1,$2,$3,'module_area_transfer',$4,$5,$6,$7,$8,$9,$10) returning id", [ctx.orgId, d.farm_id, code, d.movement_date, d.batch_id, d.grazing_module_id ?? null, d.area_id ?? null, Number(n), d.note ?? null, ctx.user.id]);
    return { id: r.rows[0]!.id, code };
  })));
  app.post("/livestock/transfers/to-farm", async (req, reply) => reply.status(201).send(await runService(app, req, "batch_farm_transfer.create", async (ctx) => {
    const d = z.object({ farm_id: uuid, destination_farm_id: uuid, movement_date: date, batch_id: uuid.optional().nullable(), animal_ids: z.array(uuid).optional(), destination_batch_id: uuid.optional().nullable(), note: z.string().optional().nullable() }).parse(req.body);
    if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda"); if (d.farm_id === d.destination_farm_id) throw validation("Fazenda destino deve ser diferente");
    const code = await animalCode(ctx, "farm_transfer");
    const r = await ctx.tx.query<{ id: string }>("insert into erp.animal_movements(organization_id,farm_id,code,movement_type,movement_date,batch_id,destination_farm_id,destination_batch_id,note,status,created_by) values ($1,$2,$3,'farm_transfer',$4,$5,$6,$7,$8,'pending',$9) returning id", [ctx.orgId, d.farm_id, code, d.movement_date, d.batch_id ?? null, d.destination_farm_id, d.destination_batch_id ?? null, d.note ?? null, ctx.user.id]);
    const ids = d.animal_ids?.length ? d.animal_ids : (await ctx.tx.query<{ id: string }>("select id from erp.animals where batch_id=$1 and status='active' and organization_id=$2", [d.batch_id, ctx.orgId])).rows.map((x) => x.id);
    for (const a of ids) await ctx.tx.query("insert into erp.animal_movement_items(movement_id,animal_id,quantity) values ($1,$2,1)", [r.rows[0]!.id, a]);
    await ctx.tx.query("update erp.animal_movements set quantity=$2 where id=$1", [r.rows[0]!.id, ids.length]);
    await ctx.tx.query("insert into erp.notifications(organization_id,kind,title,route) values ($1,'batch_transfer','Você possui uma transferência de lote a ser processada.','/pecuaria?tab=rebanho&sub=transferencias&type=farm_transfer')", [ctx.orgId]);
    return { id: r.rows[0]!.id, code, animals: ids.length, status: "pending" };
  })));
  // Processar transferência na fazenda destino (aceite)
  app.post("/livestock/transfers/:id/process", async (req) => runService(app, req, "batch_farm_transfer.process", async (ctx) => {
    const { id } = req.params as { id: string }; const d = z.object({ destination_batch_id: uuid.optional().nullable() }).parse(req.body ?? {});
    const m = await ctx.tx.query<{ status: string; destination_farm_id: string; destination_batch_id: string | null; batch_id: string | null }>("select status, destination_farm_id, destination_batch_id, batch_id from erp.animal_movements where id=$1 and organization_id=$2 and movement_type='farm_transfer' for update", [id, ctx.orgId]); if (!m.rows[0]) throw notFound(); if (m.rows[0].status !== "pending") throw err("ALREADY_CONFIRMED", "Transferência já processada");
    if (!farmAllowed(ctx, m.rows[0].destination_farm_id)) throw err("PERMISSION_DENIED", "Sem acesso à fazenda destino");
    const dest = d.destination_batch_id ?? m.rows[0].destination_batch_id;
    const u = await ctx.tx.query("update erp.animals set farm_id=$2, batch_id=$3, updated_at=now() where id in (select animal_id from erp.animal_movement_items where movement_id=$1 and animal_id is not null) returning id", [id, m.rows[0].destination_farm_id, dest]);
    if (m.rows[0].batch_id && !u.rowCount) await ctx.tx.query("update erp.herd_lots set farm_id=$2, batch_id=$3 where batch_id=$1", [m.rows[0].batch_id, m.rows[0].destination_farm_id, dest]);
    await ctx.tx.query("update erp.animal_movements set status='confirmed', updated_at=now() where id=$1", [id]);
    await audit(ctx.tx, ctx, "animal_movements", id, "process"); return { id, status: "confirmed", animals: u.rowCount };
  }));
  // Evolução de rebanho (categoria por idade), executa para animais ativos
  app.post("/livestock/evolution/run", async (req, reply) => reply.status(201).send(await runService(app, req, "herd_evolution.create", async (ctx) => {
    const d = z.object({ farm_id: uuid, movement_date: date.default(todayISO()) }).parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    const cats = (await ctx.tx.query<{ id: string; min_age_months: number | null; max_age_months: number | null; sex: "M" | "F" | null; next_category_id: string | null }>("select id, min_age_months, max_age_months, sex, next_category_id from erp.animal_categories where organization_id is null or organization_id=$1", [ctx.orgId])).rows.map((c) => ({ id: c.id, minAgeMonths: c.min_age_months, maxAgeMonths: c.max_age_months, sex: c.sex, nextCategoryId: c.next_category_id }));
    const animals = await ctx.tx.query<{ id: string; category_id: string; sex: "M" | "F" | null; birth_date: string }>("select id, category_id, sex, birth_date from erp.animals where organization_id=$1 and farm_id=$2 and status='active' and birth_date is not null and deleted_at is null", [ctx.orgId, d.farm_id]);
    const code = await animalCode(ctx, "evolution"); let n = 0;
    const r = await ctx.tx.query<{ id: string }>("insert into erp.animal_movements(organization_id,farm_id,code,movement_type,movement_date,created_by) values ($1,$2,$3,'evolution',$4,$5) returning id", [ctx.orgId, d.farm_id, code, d.movement_date, ctx.user.id]);
    for (const a of animals.rows) { const next = evolveCategory(cats, { categoryId: a.category_id, sex: a.sex, ageMonths: ageMonths(a.birth_date, d.movement_date) }); if (!next) continue; await ctx.tx.query("update erp.animals set category_id=$2, updated_at=now() where id=$1", [a.id, next]); await ctx.tx.query("insert into erp.animal_movement_items(movement_id,animal_id,category_id,new_category_id,quantity) values ($1,$2,$3,$4,1)", [r.rows[0]!.id, a.id, a.category_id, next]); n++; }
    await ctx.tx.query("update erp.animal_movements set quantity=$2 where id=$1", [r.rows[0]!.id, n]);
    return { id: r.rows[0]!.id, code, evolved: n };
  })));

  // ---------- Manejo: pesagem, nutrição/sanitário/desmama/apartação ----------
  app.get("/livestock/weighings", async (req) => runService(app, req, "weighings.view", async (ctx) => { const q = pageQuerySchema.parse(req.query); const f = req.query as Record<string, string>; const where = ["w.organization_id=$1", "w.deleted_at is null"]; const params: unknown[] = [ctx.orgId]; where.push(...farmScope(ctx, "w", params)); if (f.batch_id) { params.push(f.batch_id); where.push(`w.batch_id=$${params.length}`); } if (f.start_date) { params.push(f.start_date); where.push(`w.weighing_date>=$${params.length}`); } if (f.end_date) { params.push(f.end_date); where.push(`w.weighing_date<=$${params.length}`); } const w = where.join(" and "); return paged(ctx, `select w.*, b.description as batch_name, (select round(avg(wi.gmd),3) from erp.weighing_items wi where wi.weighing_id=w.id) as avg_gmd from erp.weighings w left join erp.batches b on b.id=w.batch_id where ${w} order by w.weighing_date desc`, `select count(*) n from erp.weighings w where ${w}`, params, q, req.query as Record<string, unknown>); }));
  // Detalhe de uma pesagem (itens com identificação do animal, peso anterior e GMD) — usado por /pecuaria/pesagens/:id
  app.get("/livestock/weighings/:id", async (req) => runService(app, req, "weighings.view", async (ctx) => {
    const { id } = req.params as { id: string };
    const w = await ctx.tx.query("select w.*, b.description as batch_name, f.name as farm_name, u.name as created_by_name from erp.weighings w left join erp.batches b on b.id=w.batch_id join erp.farms f on f.id=w.farm_id left join erp.users u on u.id=w.created_by where w.id=$1 and w.organization_id=$2 and w.deleted_at is null" + scopedById(ctx, "w", id).sql, scopedById(ctx, "w", id).params);
    if (!w.rows[0]) throw notFound("Pesagem");
    const items = await ctx.tx.query("select wi.*, (select string_agg(i.value, ', ' order by i.is_primary desc) from erp.animal_identifications i where i.animal_id=wi.animal_id) as identifications, c.name as category_name from erp.weighing_items wi join erp.animals a on a.id=wi.animal_id left join erp.animal_categories c on c.id=a.category_id where wi.weighing_id=$1 order by wi.weight desc", [id]);
    return { ...w.rows[0], items: items.rows };
  }));
  app.post("/livestock/weighings", async (req, reply) => reply.status(201).send(await runService(app, req, "weighings.create", async (ctx) => {
    const d = z.object({ farm_id: uuid, weighing_date: date, batch_id: uuid.optional().nullable(), responsible: z.string().optional().nullable(), note: z.string().optional().nullable(), items: z.array(z.object({ animal_id: uuid, weight: dec })).min(1) }).parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    return (await idempotent(ctx.tx, ctx.orgId, idem(req), d, async () => {
      const code = await animalCode(ctx, "weighing");
      const r = await ctx.tx.query<{ id: string }>("insert into erp.weighings(organization_id,farm_id,code,weighing_date,batch_id,responsible,note,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8) returning id", [ctx.orgId, d.farm_id, code, d.weighing_date, d.batch_id ?? null, d.responsible ?? null, d.note ?? null, ctx.user.id]);
      let total = D(0);
      for (const it of d.items) {
        const prev = await ctx.tx.query<{ weight: string; weighing_date: string }>("select wi.weight, w.weighing_date from erp.weighing_items wi join erp.weighings w on w.id=wi.weighing_id where wi.animal_id=$1 and w.weighing_date < $2 order by w.weighing_date desc limit 1", [it.animal_id, d.weighing_date]);
        const p = prev.rows[0] ?? (await ctx.tx.query<{ weight: string | null; weighing_date: string }>("select entry_weight as weight, entry_date as weighing_date from erp.animals where id=$1", [it.animal_id])).rows[0];
        const g = p?.weight ? gmd(p.weight, p.weighing_date, it.weight, d.weighing_date) : null;
        await ctx.tx.query("insert into erp.weighing_items(weighing_id,animal_id,weight,previous_weight,gmd) values ($1,$2,$3,$4,$5)", [r.rows[0]!.id, it.animal_id, it.weight, p?.weight ?? null, g]);
        await ctx.tx.query("update erp.animals set current_weight=$2, ua=$3, updated_at=now() where id=$1 and organization_id=$4", [it.animal_id, it.weight, D(it.weight).div(450).toFixed(3), ctx.orgId]);
        total = total.plus(it.weight);
      }
      await ctx.tx.query("update erp.weighings set animals_count=$2, total_weight=$3 where id=$1", [r.rows[0]!.id, d.items.length, total.toFixed(2)]);
      await audit(ctx.tx, ctx, "weighings", r.rows[0]!.id, "create", { code });
      return { id: r.rows[0]!.id, code, animals: d.items.length, total_weight: total.toFixed(2), average: total.div(d.items.length).toFixed(2) };
    })).result;
  })));
  const handlingSchema = z.object({ farm_id: uuid, handling_type: z.enum(["nutrition", "sanitary", "weaning", "separation", "pasture"]), handling_date: date, batch_id: uuid.optional().nullable(), product_id: uuid.optional().nullable(), warehouse_id: uuid.optional().nullable(), dose: dec.optional().nullable(), responsible: z.string().optional().nullable(), note: z.string().optional().nullable(), items: z.array(z.object({ animal_id: uuid.optional().nullable(), herd_lot_id: uuid.optional().nullable(), quantity: dec.default("1"), new_batch_id: uuid.optional().nullable(), new_category_id: uuid.optional().nullable() })).min(1) });
  app.get("/livestock/handlings", async (req) => runService(app, req, "nutritions.view", async (ctx) => { const q = pageQuerySchema.parse(req.query); const f = req.query as Record<string, string>; const where = ["h.organization_id=$1", "h.deleted_at is null"]; const params: unknown[] = [ctx.orgId]; if (f.handling_type) { params.push(f.handling_type); where.push(`h.handling_type=$${params.length}`); } where.push(...farmScope(ctx, "h", params)); if (f.batch_id) { params.push(f.batch_id); where.push(`h.batch_id=$${params.length}`); } if (f.start_date) { params.push(f.start_date); where.push(`h.handling_date>=$${params.length}`); } if (f.end_date) { params.push(f.end_date); where.push(`h.handling_date<=$${params.length}`); } const w = where.join(" and "); return paged(ctx, `select h.*, b.description as batch_name, p.description as product_name from erp.animal_handlings h left join erp.batches b on b.id=h.batch_id left join erp.products p on p.id=h.product_id where ${w} order by h.handling_date desc`, `select count(*) n from erp.animal_handlings h where ${w}`, params, q, req.query as Record<string, unknown>); }));
  // Detalhe de um manejo (nutrição, sanitário, desmama, apartação, pastagem) — permissão de visualização do próprio tipo
  app.get("/livestock/handlings/:id", async (req) => runService(app, req, null, async (ctx) => {
    const { id } = req.params as { id: string };
    const h = await ctx.tx.query<{ handling_type: string }>("select h.*, b.description as batch_name, p.description as product_name, w.description as warehouse_name, f.name as farm_name, u.name as created_by_name from erp.animal_handlings h left join erp.batches b on b.id=h.batch_id left join erp.products p on p.id=h.product_id left join erp.warehouses w on w.id=h.warehouse_id join erp.farms f on f.id=h.farm_id left join erp.users u on u.id=h.created_by where h.id=$1 and h.organization_id=$2 and h.deleted_at is null" + scopedById(ctx, "h", id).sql, scopedById(ctx, "h", id).params);
    if (!h.rows[0]) throw notFound("Manejo");
    const viewPerm: Record<string, string> = { nutrition: "nutritions.view", sanitary: "sanitaries.view", weaning: "weanings.view", separation: "separations.view", pasture: "pastures.view", locate: "locate_animals.view" };
    requirePermission(ctx, viewPerm[h.rows[0].handling_type] ?? "nutritions.view");
    const items = await ctx.tx.query("select hi.*, (select string_agg(i.value, ', ' order by i.is_primary desc) from erp.animal_identifications i where i.animal_id=hi.animal_id) as identifications, c.name as category_name, hc.name as herd_lot_category, nb.description as new_batch_name, nc.name as new_category_name from erp.animal_handling_items hi left join erp.animals a on a.id=hi.animal_id left join erp.animal_categories c on c.id=a.category_id left join erp.herd_lots hl on hl.id=hi.herd_lot_id left join erp.animal_categories hc on hc.id=hl.category_id left join erp.batches nb on nb.id=hi.new_batch_id left join erp.animal_categories nc on nc.id=hi.new_category_id where hi.handling_id=$1 order by identifications", [id]);
    return { ...h.rows[0], items: items.rows };
  }));
  app.post("/livestock/handlings", async (req, reply) => reply.status(201).send(await runService(app, req, "nutritions.create", async (ctx) => {
    const d = handlingSchema.parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    const permMap = { nutrition: "nutritions.create", sanitary: "sanitaries.create", weaning: "weanings.create", separation: "separations.create", pasture: "pastures.create" } as const; const { requirePermission } = await import("../lib/service.js"); requirePermission(ctx, permMap[d.handling_type]);
    return (await idempotent(ctx.tx, ctx.orgId, idem(req), d, async () => {
      const code = await uniqueCode(ctx, "animal_handlings", "animal_handling");
      const r = await ctx.tx.query<{ id: string }>("insert into erp.animal_handlings(organization_id,farm_id,code,handling_type,handling_date,batch_id,product_id,warehouse_id,responsible,note,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning id", [ctx.orgId, d.farm_id, code, d.handling_type, d.handling_date, d.batch_id ?? null, d.product_id ?? null, d.warehouse_id ?? null, d.responsible ?? null, d.note ?? null, ctx.user.id]);
      const id = r.rows[0]!.id; let qty = D(0); let count = 0;
      for (const it of d.items) {
        const q = d.dose ? D(d.dose).mul(it.quantity) : D(it.quantity); qty = qty.plus(d.product_id ? q : 0); count += Number(it.quantity);
        await ctx.tx.query("insert into erp.animal_handling_items(handling_id,animal_id,herd_lot_id,quantity,dose,new_batch_id,new_category_id) values ($1,$2,$3,$4,$5,$6,$7)", [id, it.animal_id ?? null, it.herd_lot_id ?? null, q.toFixed(4), d.dose ?? null, it.new_batch_id ?? null, it.new_category_id ?? null]);
        if ((d.handling_type === "weaning" || d.handling_type === "separation") && it.animal_id) await ctx.tx.query("update erp.animals set batch_id=coalesce($2,batch_id), category_id=coalesce($3,category_id), updated_at=now() where id=$1", [it.animal_id, it.new_batch_id ?? null, it.new_category_id ?? null]);
      }
      let total = "0.00"; let unit = "0";
      if (d.product_id && d.warehouse_id && qty.gt(0)) { const s = await postStock(ctx, { farmId: d.farm_id, warehouseId: d.warehouse_id, productId: d.product_id, movementType: "nutrition", direction: -1, quantity: qty.toFixed(4), sourceType: "animal_handlings", sourceId: id, date: d.handling_date, note: `${d.handling_type} ${code}` }); unit = s.unitCost; total = money(qty.mul(unit)); }
      const wd = d.product_id && d.handling_type === "sanitary" ? (await ctx.tx.query<{ withdrawal_period_days: number | null }>("select withdrawal_period_days from erp.products where id=$1", [d.product_id])).rows[0]?.withdrawal_period_days ?? null : null;
      await ctx.tx.query("update erp.animal_handlings set quantity=$2, unit_value=$3, total=$4, animals_count=$5, withdrawal_until=$6 where id=$1", [id, qty.toFixed(4), unit, total, count, withdrawalUntil(d.handling_date, wd)]);
      await audit(ctx.tx, ctx, "animal_handlings", id, "create", { code, type: d.handling_type });
      return { id, code, animals: count, total, withdrawal_until: withdrawalUntil(d.handling_date, wd) };
    })).result;
  })));

  // ---------- Processamentos (compra → identificação/processamento dos animais) ----------
  app.get("/livestock/processings", async (req) => runService(app, req, "processings.view", async (ctx) => { const r = await ctx.tx.query("select p.*, m.code as purchase_code, b.description as pre_batch_name, f.name as farm_name from erp.processings p left join erp.animal_movements m on m.id=p.purchase_movement_id left join erp.batches b on b.id=p.pre_batch_id join erp.farms f on f.id=p.farm_id where p.organization_id=$1 and ($2::uuid[] is null or p.farm_id = any($2)) order by p.processing_date desc", [ctx.orgId, allowedFarms(ctx)]); return { items: r.rows, total: r.rowCount }; }));
  app.post("/livestock/processings/:id/process", async (req) => runService(app, req, "processings.process", async (ctx) => {
    const { id } = req.params as { id: string }; const d = z.object({ animals: z.array(z.object({ herd_lot_id: uuid, category_id: uuid, breed_id: uuid.optional().nullable(), sex: z.enum(["M", "F"]).optional().nullable(), weight: dec.optional().nullable(), batch_id: uuid.optional().nullable(), identifications: z.array(z.object({ identification_type_id: uuid, value: z.string().min(1) })).min(1) })).min(1), finish: z.boolean().default(false) }).parse(req.body);
    const p = await ctx.tx.query<{ status: string; farm_id: string; processed_quantity: number; expected_quantity: number }>("select status, farm_id, processed_quantity, expected_quantity from erp.processings where id=$1 and organization_id=$2 for update", [id, ctx.orgId]); if (!p.rows[0]) throw notFound(); assertFarmVisible(ctx, p.rows[0].farm_id, "Processamento"); if (["finished", "cancelled"].includes(p.rows[0].status)) throw err("ALREADY_CONFIRMED", "Processamento encerrado");
    const species = (await ctx.tx.query<{ id: string }>("select id from erp.animal_species where organization_id is null order by name limit 1")).rows[0]!.id; let n = 0;
    for (const a of d.animals) {
      const hl = await ctx.tx.query<{ quantity: number; unit_value: string | null }>("select quantity, unit_value from erp.herd_lots where id=$1 and organization_id=$2 for update", [a.herd_lot_id, ctx.orgId]); if (!hl.rows[0] || hl.rows[0].quantity < 1) throw err("INSUFFICIENT_STOCK", "Lote sem animais a processar");
      await ctx.tx.query("update erp.herd_lots set quantity=quantity-1 where id=$1", [a.herd_lot_id]);
      const an = await ctx.tx.query<{ id: string }>("insert into erp.animals(organization_id,farm_id,species_id,category_id,breed_id,batch_id,sex,entry_date,current_weight,entry_weight,unit_value,created_by) values ($1,$2,$3,$4,$5,$6,$7,current_date,$8,$8,$9,$10) returning id", [ctx.orgId, p.rows[0].farm_id, species, a.category_id, a.breed_id ?? null, a.batch_id ?? null, a.sex ?? null, a.weight ?? null, hl.rows[0].unit_value, ctx.user.id]);
      for (const [i, ident] of a.identifications.entries()) await ctx.tx.query("insert into erp.animal_identifications(animal_id,organization_id,identification_type_id,value,is_primary) values ($1,$2,$3,$4,$5)", [an.rows[0]!.id, ctx.orgId, ident.identification_type_id, ident.value, i === 0]);
      n++;
    }
    const processed = p.rows[0].processed_quantity + n; const finished = d.finish || processed >= p.rows[0].expected_quantity;
    await ctx.tx.query("update erp.processings set processed_quantity=$2, status=$3, updated_at=now() where id=$1", [id, processed, finished ? "finished" : "in_progress"]);
    return { id, processed, status: finished ? "finished" : "in_progress" };
  }));

  // ---------- Reprodução: acasalamentos e diagnóstico ----------
  app.get("/livestock/matings", async (req) => runService(app, req, "matings.view", async (ctx) => { const q = pageQuerySchema.parse(req.query); const f = req.query as Record<string, string>; const where = ["m.organization_id=$1"]; const params: unknown[] = [ctx.orgId]; if (ctx.membership.farmIds.length || ctx.farmId) { const fp: unknown[] = []; const sc = farmScope(ctx, "a", fp); params.push(...fp); where.push(`exists (select 1 from erp.animals a where a.id=m.dam_id and ${sc.map((c) => c.replace(/\$(\d+)/g, (_m, n) => `$${params.length - fp.length + Number(n)}`)).join(" and ")})`); } if (f.season_id) { params.push(f.season_id); where.push(`m.season_id=$${params.length}`); } if (f.result) { params.push(f.result); where.push(`m.result=$${params.length}`); } const w = where.join(" and "); return paged(ctx, `select m.*, s.name as season_name, si.name as sire_name, si.sire_type, (select string_agg(i.value, ', ') from erp.animal_identifications i where i.animal_id=m.dam_id) as dam_identification, p.name as inseminator_name from erp.matings m join erp.breeding_seasons s on s.id=m.season_id left join erp.breeding_sires si on si.id=m.sire_id left join erp.people p on p.id=m.inseminator_person_id where ${w} order by m.mating_date desc`, `select count(*) n from erp.matings m where ${w}`, params, q, req.query as Record<string, unknown>); }));
  app.post("/livestock/matings", async (req, reply) => reply.status(201).send(await runService(app, req, "matings.create", async (ctx) => {
    const d = z.object({ season_id: uuid, dam_ids: z.array(uuid).min(1), sire_id: uuid.optional().nullable(), protocol_id: uuid.optional().nullable(), mating_type: z.enum(["natural", "ai", "fta", "embryo_transfer"]), mating_date: date, inseminator_person_id: uuid.optional().nullable(), note: z.string().optional().nullable() }).parse(req.body);
    const s = await ctx.tx.query<{ status: string }>("select status from erp.breeding_seasons where id=$1 and organization_id=$2", [d.season_id, ctx.orgId]); if (!s.rows[0]) throw notFound("Estação"); if (s.rows[0].status !== "open") throw err("INVALID_STATUS_TRANSITION", "Estação de monta encerrada");
    const ids: string[] = [];
    for (const dam of d.dam_ids) { const a = await ctx.tx.query<{ sex: string | null; status: string }>("select sex, status from erp.animals where id=$1 and organization_id=$2", [dam, ctx.orgId]); if (!a.rows[0] || a.rows[0].status !== "active") throw err("ANIMAL_NOT_ACTIVE", "Matriz inativa"); if (a.rows[0].sex === "M") throw validation("Matriz deve ser fêmea"); const r = await ctx.tx.query<{ id: string }>("insert into erp.matings(organization_id,season_id,dam_id,sire_id,protocol_id,mating_type,mating_date,inseminator_person_id,result,expected_birth,note,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,'pending',$9,$10,$11) returning id", [ctx.orgId, d.season_id, dam, d.sire_id ?? null, d.protocol_id ?? null, d.mating_type, d.mating_date, d.inseminator_person_id ?? null, expectedBirth(d.mating_date), d.note ?? null, ctx.user.id]); ids.push(r.rows[0]!.id); if (d.sire_id && d.mating_type !== "natural") await ctx.tx.query("update erp.breeding_sires set doses=greatest(coalesce(doses,0)-1,0) where id=$1", [d.sire_id]); }
    return { ids };
  })));
  app.post("/livestock/matings/:id/diagnosis", async (req) => runService(app, req, "pregnancy_diagnosis.create", async (ctx) => { const { id } = req.params as { id: string }; const d = z.object({ result: z.enum(["pregnant", "empty"]), diagnosis_date: date }).parse(req.body); const m = await ctx.tx.query<{ dam_id: string; mating_date: string }>("update erp.matings set result=$3, diagnosis_date=$4 where id=$1 and organization_id=$2 returning dam_id, mating_date", [id, ctx.orgId, d.result, d.diagnosis_date]); if (!m.rows[0]) throw notFound(); await ctx.tx.query("update erp.animals set reproductive_status=$2, birth_forecast=$3 where id=$1", [m.rows[0].dam_id, d.result, d.result === "pregnant" ? expectedBirth(m.rows[0].mating_date) : null]); return { id, result: d.result }; }));
  app.get("/livestock/reproduction/overview", async (req) => runService(app, req, "advanced_reproductive.view", async (ctx) => { const r = await ctx.tx.query("select s.id, s.name, s.start_date, s.end_date, s.status, count(m.id)::int as matings, count(*) filter (where m.result='pregnant')::int as pregnant, count(*) filter (where m.result='empty')::int as empty, count(*) filter (where m.result='pending')::int as pending from erp.breeding_seasons s left join erp.matings m on m.season_id=s.id where s.organization_id=$1 and s.deleted_at is null and ($2::uuid[] is null or s.farm_id = any($2)) group by s.id order by s.start_date desc", [ctx.orgId, allowedFarms(ctx)]); return { seasons: r.rows.map((x) => ({ ...(x as Record<string, unknown>), pregnancy_rate: (x as { matings: number; pregnant: number }).matings ? ((x as { pregnant: number }).pregnant / (x as { matings: number }).matings * 100).toFixed(1) : null })) }; }));

  // ---------- Confinamento: batelada, trato, leitura de cocho, mapa ----------
  app.post("/feedlot/diet-batches", async (req, reply) => reply.status(201).send(await runService(app, req, "diet_batches.create", async (ctx) => {
    const d = z.object({ farm_id: uuid, batch_date: date, diet_id: uuid, warehouse_id: uuid, equipment_id: uuid.optional().nullable(), quantity_kg: dec }).parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda");
    return (await idempotent(ctx.tx, ctx.orgId, idem(req), d, async () => {
      const items = await ctx.tx.query<{ product_id: string; percentage: string }>("select product_id, percentage from erp.diet_items where diet_id=$1", [d.diet_id]); if (!items.rowCount) throw validation("Dieta sem ingredientes");
      const code = await animalCode(ctx, "diet_batch");
      const r = await ctx.tx.query<{ id: string }>("insert into erp.diet_batches(organization_id,farm_id,code,batch_date,diet_id,warehouse_id,equipment_id,quantity_kg,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9) returning id", [ctx.orgId, d.farm_id, code, d.batch_date, d.diet_id, d.warehouse_id, d.equipment_id ?? null, d.quantity_kg, ctx.user.id]);
      let total = D(0);
      for (const it of items.rows) { const q = D(d.quantity_kg).mul(it.percentage).div(100).toFixed(4); const s = await postStock(ctx, { farmId: d.farm_id, warehouseId: d.warehouse_id, productId: it.product_id, movementType: "nutrition", direction: -1, quantity: q, sourceType: "diet_batches", sourceId: r.rows[0]!.id, date: d.batch_date, note: `Batelada ${code}` }); const t = money(D(q).mul(s.unitCost)); total = total.plus(t); await ctx.tx.query("insert into erp.diet_batch_items(diet_batch_id,product_id,quantity_kg,unit_cost,total_cost) values ($1,$2,$3,$4,$5)", [r.rows[0]!.id, it.product_id, q, s.unitCost, t]); }
      await ctx.tx.query("update erp.diet_batches set total_cost=$2 where id=$1", [r.rows[0]!.id, money(total)]);
      await ctx.tx.query("update erp.diets set cost_per_kg=$2 where id=$1", [d.diet_id, total.div(d.quantity_kg).toFixed(6)]);
      return { id: r.rows[0]!.id, code, total_cost: money(total), cost_per_kg: total.div(d.quantity_kg).toFixed(6) };
    })).result;
  })));
  app.get("/feedlot/diet-batches", async (req) => runService(app, req, "diet_batches.view", async (ctx) => { const r = await ctx.tx.query("select b.*, d.name as diet_name from erp.diet_batches b join erp.diets d on d.id=b.diet_id where b.organization_id=$1 and ($2::uuid[] is null or b.farm_id = any($2)) order by b.batch_date desc limit 200", [ctx.orgId, allowedFarms(ctx)]); return { items: r.rows }; }));
  app.post("/feedlot/deliveries", async (req, reply) => reply.status(201).send(await runService(app, req, "feed_deliveries.create", async (ctx) => { const d = z.object({ farm_id: uuid, delivery_date: date, delivery_time: z.string().optional().nullable(), diet_batch_id: uuid.optional().nullable(), diet_id: uuid.optional().nullable(), corral_id: uuid.optional().nullable(), batch_id: uuid.optional().nullable(), quantity_kg: dec }).parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda"); const cost = d.diet_batch_id ? (await ctx.tx.query<{ c: string }>("select total_cost/nullif(quantity_kg,0) c from erp.diet_batches where id=$1", [d.diet_batch_id])).rows[0]?.c : d.diet_id ? (await ctx.tx.query<{ c: string }>("select cost_per_kg c from erp.diets where id=$1", [d.diet_id])).rows[0]?.c : "0"; const r = await ctx.tx.query<{ id: string }>("insert into erp.feed_deliveries(organization_id,farm_id,delivery_date,delivery_time,diet_batch_id,diet_id,corral_id,batch_id,quantity_kg,cost,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning id", [ctx.orgId, d.farm_id, d.delivery_date, d.delivery_time ?? null, d.diet_batch_id ?? null, d.diet_id ?? null, d.corral_id ?? null, d.batch_id ?? null, d.quantity_kg, money(D(d.quantity_kg).mul(cost ?? 0)), ctx.user.id]); return { id: r.rows[0]!.id }; })));
  app.get("/feedlot/deliveries", async (req) => runService(app, req, "feed_deliveries.view", async (ctx) => { const f = req.query as Record<string, string>; const r = await ctx.tx.query("select d.*, c.name as corral_name, b.description as batch_name, di.name as diet_name from erp.feed_deliveries d left join erp.feedlot_corrals c on c.id=d.corral_id left join erp.batches b on b.id=d.batch_id left join erp.diets di on di.id=d.diet_id where d.organization_id=$1 and ($2::date is null or d.delivery_date>=$2) and ($3::date is null or d.delivery_date<=$3) and ($4::uuid[] is null or d.farm_id = any($4)) order by d.delivery_date desc, d.delivery_time desc limit 500", [ctx.orgId, f.start_date ?? null, f.end_date ?? null, allowedFarms(ctx)]); return { items: r.rows }; }));
  app.post("/feedlot/trough-readings", async (req, reply) => reply.status(201).send(await runService(app, req, "trough_readings.create", async (ctx) => { const d = z.object({ farm_id: uuid, reading_date: date, corral_id: uuid, score: z.number().int().min(-1).max(4), leftover_kg: dec.optional().nullable(), note: z.string().optional().nullable() }).parse(req.body); if (!farmAllowed(ctx, d.farm_id)) throw validation("Sem acesso à fazenda"); const r = await ctx.tx.query<{ id: string }>("insert into erp.trough_readings(organization_id,farm_id,reading_date,corral_id,score,leftover_kg,note,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8) on conflict (corral_id,reading_date) do update set score=excluded.score, leftover_kg=excluded.leftover_kg, note=excluded.note returning id", [ctx.orgId, d.farm_id, d.reading_date, d.corral_id, d.score, d.leftover_kg ?? null, d.note ?? null, ctx.user.id]); return { id: r.rows[0]!.id }; })));
  app.get("/feedlot/map", async (req) => runService(app, req, "feedlot_map.view", async (ctx) => { const r = await ctx.tx.query("select y.name as yard, s.name as sector, c.id as corral_id, c.code, c.name, c.capacity, coalesce((select count(*) from erp.animals a join erp.batches b on b.id=a.batch_id where b.corral_id=c.id and a.status='active'),0)::int + coalesce((select sum(h.quantity) from erp.herd_lots h join erp.batches b on b.id=h.batch_id where b.corral_id=c.id),0)::int as occupancy, (select string_agg(b.description, ', ') from erp.batches b where b.corral_id=c.id and b.status='active') as batches, (select score from erp.trough_readings t where t.corral_id=c.id order by reading_date desc limit 1) as last_trough_score from erp.feedlot_corrals c join erp.feedlot_sectors s on s.id=c.sector_id join erp.feedlot_yards y on y.id=s.yard_id where c.organization_id=$1 and c.deleted_at is null and ($2::uuid[] is null or y.farm_id = any($2)) order by y.code, s.code, c.code", [ctx.orgId, allowedFarms(ctx)]); return { corrals: r.rows.map((x) => ({ ...(x as Record<string, unknown>), occupancy_rate: (x as { capacity: number }).capacity ? ((x as { occupancy: number }).occupancy / (x as { capacity: number }).capacity * 100).toFixed(1) : null })) }; }));
}
