"use client";
import * as React from "react";
import { useQuery } from "@tanstack/react-query";
import { api, qs } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { brl, num, dateBR, todayISO, monthStartISO } from "@/lib/utils";
import { Button, Card, CardHeader, CardBody, Field, Input, Spinner } from "@/components/ui";
import { RefSelect } from "@/components/ui/ref-select";
import { SimpleTable, useCreate, useFarmDefault, type Row } from "@/features/docs/shared";
export function FeedDeliveriesPanel() {
  const { can } = useAuth(); const farm = useFarmDefault(); const [range, setRange] = React.useState({ start_date: monthStartISO(), end_date: todayISO() });
  const q = useQuery({ queryKey: ["deliveries", range], queryFn: () => api<{ items: Row[] }>(`/api/feedlot/deliveries${qs(range)}`) });
  const [f, setF] = React.useState({ farm_id: "", delivery_date: todayISO(), delivery_time: "", diet_batch_id: "", diet_id: "", corral_id: "", batch_id: "", quantity_kg: "" }); React.useEffect(() => { setF((o) => ({ ...o, farm_id: o.farm_id || farm })); }, [farm]);
  const create = useCreate("/api/feedlot/deliveries", () => { setF({ ...f, quantity_kg: "" }); void q.refetch(); });
  return <div className="space-y-3">{can("feed_deliveries.create") && <Card><CardHeader title="Trato (fornecimento de dieta)" subtitle="Registra o fornecido por curral/lote; custo pela batelada ou pelo custo/kg da dieta." /><CardBody><div className="grid grid-cols-12 gap-2"><Field label="Fazenda" span={2}><RefSelect resource="farms" value={f.farm_id} onChange={(v) => setF({ ...f, farm_id: v ?? "" })} /></Field><Field label="Data" span={2}><Input type="date" value={f.delivery_date} onChange={(e) => setF({ ...f, delivery_date: e.target.value })} /></Field><Field label="Hora" span={1}><Input type="time" value={f.delivery_time} onChange={(e) => setF({ ...f, delivery_time: e.target.value })} /></Field><Field label="Dieta" span={3}><RefSelect resource="diets" value={f.diet_id} onChange={(v) => setF({ ...f, diet_id: v ?? "" })} /></Field><Field label="Curral" span={2}><RefSelect resource="feedlot_corrals" value={f.corral_id} onChange={(v) => setF({ ...f, corral_id: v ?? "" })} /></Field><Field label="Lote" span={2}><RefSelect resource="batches" value={f.batch_id} onChange={(v) => setF({ ...f, batch_id: v ?? "" })} /></Field><Field label="Kg fornecidos" required span={2}><Input type="number" step="0.01" value={f.quantity_kg} onChange={(e) => setF({ ...f, quantity_kg: e.target.value })} /></Field><div className="col-span-2 flex items-end"><Button size="sm" loading={create.isPending} disabled={!f.quantity_kg || !(f.diet_id || f.diet_batch_id)} onClick={() => create.mutate({ ...f, delivery_time: f.delivery_time || null, diet_batch_id: f.diet_batch_id || null, diet_id: f.diet_id || null, corral_id: f.corral_id || null, batch_id: f.batch_id || null })}>Registrar</Button></div></div></CardBody></Card>}
    <Card><CardHeader title="Tratos registrados" actions={<div className="flex gap-2"><Input type="date" value={range.start_date} onChange={(e) => setRange({ ...range, start_date: e.target.value })} /><Input type="date" value={range.end_date} onChange={(e) => setRange({ ...range, end_date: e.target.value })} /></div>} /><CardBody>{q.isLoading ? <Spinner /> : <SimpleTable rows={q.data?.items ?? []} cols={[{ key: "delivery_date", label: "Data", render: (r) => `${dateBR(r["delivery_date"] as string)} ${r["delivery_time"] ?? ""}` }, { key: "corral_name", label: "Curral" }, { key: "batch_name", label: "Lote" }, { key: "diet_name", label: "Dieta" }, { key: "quantity_kg", label: "Kg", align: "right", render: (r) => num(r["quantity_kg"] as string, 2) }, { key: "total_cost", label: "Custo", align: "right", render: (r) => brl(r["total_cost"] as string) }]} />}</CardBody></Card></div>;
}
