/**
 * Códigos de erro de domínio. Usados pela API (mapeados para HTTP) e pelo frontend (mensagens pt-BR).
 */
export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  CONFLICT: "CONFLICT",
  ALREADY_CONFIRMED: "ALREADY_CONFIRMED",
  ALREADY_CANCELLED: "ALREADY_CANCELLED",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  PAYMENT_EXCEEDS_BALANCE: "PAYMENT_EXCEEDS_BALANCE",
  CONCURRENCY_CONFLICT: "CONCURRENCY_CONFLICT",
  IDEMPOTENT_REPLAY: "IDEMPOTENT_REPLAY",
  PERIOD_FROZEN: "PERIOD_FROZEN",
  APPORTIONMENT_MISMATCH: "APPORTIONMENT_MISMATCH",
  INSTALLMENTS_MISMATCH: "INSTALLMENTS_MISMATCH",
  DUPLICATE_DOCUMENT: "DUPLICATE_DOCUMENT",
  PRODUCT_NOT_STOCK_CONTROLLED: "PRODUCT_NOT_STOCK_CONTROLLED",
  WAREHOUSE_FARM_MISMATCH: "WAREHOUSE_FARM_MISMATCH",
  SAME_WAREHOUSE_TRANSFER: "SAME_WAREHOUSE_TRANSFER",
  ANIMAL_NOT_ACTIVE: "ANIMAL_NOT_ACTIVE",
  BATCH_CLOSED: "BATCH_CLOSED",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const errorHttpStatus: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 422,
  NOT_FOUND: 404,
  PERMISSION_DENIED: 403,
  UNAUTHENTICATED: 401,
  CONFLICT: 409,
  ALREADY_CONFIRMED: 409,
  ALREADY_CANCELLED: 409,
  INVALID_STATUS_TRANSITION: 409,
  INSUFFICIENT_STOCK: 409,
  PAYMENT_EXCEEDS_BALANCE: 409,
  CONCURRENCY_CONFLICT: 409,
  IDEMPOTENT_REPLAY: 200,
  PERIOD_FROZEN: 409,
  APPORTIONMENT_MISMATCH: 422,
  INSTALLMENTS_MISMATCH: 422,
  DUPLICATE_DOCUMENT: 409,
  PRODUCT_NOT_STOCK_CONTROLLED: 422,
  WAREHOUSE_FARM_MISMATCH: 422,
  SAME_WAREHOUSE_TRANSFER: 422,
  ANIMAL_NOT_ACTIVE: 409,
  BATCH_CLOSED: 409,
  ACCOUNT_INACTIVE: 409,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500
};

export class DomainError extends Error {
  readonly code: ErrorCode;
  readonly details: unknown;
  constructor(code: ErrorCode, message?: string, details?: unknown) {
    super(message ?? code);
    this.name = "DomainError";
    this.code = code;
    this.details = details;
  }
  get httpStatus(): number {
    return errorHttpStatus[this.code];
  }
  toJSON() {
    return { code: this.code, message: this.message, details: this.details };
  }
}

export const isDomainError = (e: unknown): e is DomainError => e instanceof DomainError;
