// Mapa de paridade: slug da rota de referência (sem /admin/) → tela nossa, status e observação.
// Status: NÃO INICIADO | MAPEADO | EM IMPLEMENTAÇÃO | IMPLEMENTADO | TESTADO | BLOQUEADO | NÃO APLICÁVEL | MELHORADO
const I = "IMPLEMENTADO", T = "TESTADO", M = "MAPEADO", E = "EM IMPLEMENTAÇÃO", N = "NÃO INICIADO", X = "NÃO APLICÁVEL", B = "BLOQUEADO", U = "MELHORADO";
const cad = (k, extra = {}) => ({ ours: `/cadastros/${k}`, status: I, ...extra });
export const SCREENS = {
  home: { ours: "/", status: T, note: "Painel com previsto x realizado, custo por centro, resultado operacional e alertas (e2e + integração)" },
  "financial-dashboard": { ours: "/dashboards/financeiro", status: I }, "livestock-dashboard": { ours: "/dashboards/pecuaria", status: T }, "cash-book-dashboard": { ours: "/dashboards/livro-caixa", status: I }, "supply-dashboard": { ours: "/dashboards/suprimentos", status: I }, "depreciation-dashboard": { ours: "/dashboards/depreciacoes", status: I }, "assets-dashboard": { ours: "/dashboards/ativos", status: I }, "user-analysis-dashboard": { ours: "/dashboards/usuarios", status: I }, "rainfall-dashboard": { ours: "/dashboards/pluviometria", status: I }, "feedlot-dashboard": { ours: "/dashboards/confinamento", status: I }, "feedlot-cost-dashboard": { ours: "/dashboards/confinamento-custos", status: I }, "feedlot-performance-dashboard": { ours: "/dashboards/confinamento-desempenho", status: I }, "nutrition-stock-dashboard": { ours: "/dashboards/estoque-nutricao", status: I }, "feed-consumption-dashboard": { ours: "/dashboards/consumo-racao", status: I },
  employees: { ours: "/cadastros/people?is_employee=true", status: U, note: "Cadastro único de pessoas com papéis (funcionário/fornecedor/cliente/proprietário/transportadora) + perfil de funcionário; evita duplicidade da referência" },
  users: { ours: "/admin/usuarios", status: T, note: "Sem limite de licença por usuário (referência bloqueava 'limite de usuários'); vínculo perfil × fazendas" },
  invoices: { ours: "/estoque/documentos-fiscais", status: T, note: "Importação de XML NF-e, itens, estoque e títulos em transação única" },
  dfe: { ours: "/estoque/dfe", status: E, note: "Fila de DFe e manifestação registradas localmente; consulta automática à SEFAZ (certificado A1) não integrada" },
  foods: { ours: "/estoque/formulacoes", status: I },
  expenses: { ours: "/financeiro/contas-a-pagar", status: T }, incomes: { ours: "/financeiro/contas-a-receber", status: T }, movements: { ours: "/financeiro/movimentos", status: T },
  "ofx-imports": { ours: "/financeiro/ofx", status: T, note: "Parser OFX com teste unitário; conciliação por vínculo ou criação de movimento" }, "ofx-report": { ours: "/financeiro/ofx/relatorio", status: I },
  nfe: { ours: "/fiscal", status: N, note: "Emissão de NF-e exige certificado digital e homologação SEFAZ — fora do escopo desta entrega" }, nfses: { ours: "/fiscal", status: N, note: "Consulta de NFS-e recebidas depende de integração municipal" },
  costcenters: cad("cost_centers", { status: T, note: "Árvore hierárquica com 'criar descendente'" }), farms: cad("farms"), harvests: cad("harvests"), addressings: cad("addressings"), products: cad("products", { status: T }), warehouses: cad("warehouses"),
  openingbalances: { ours: "/estoque/estoque-inicial", status: T }, apportionments: cad("apportionment_categories"), roles: { ours: "/admin/perfis", status: T, note: "Árvore de permissões por recurso × ação; autorização aplicada no servidor" },
  people: cad("people"), proprietaries: { ours: "/cadastros/people?is_proprietary=true", status: U, note: "Papel no cadastro único de pessoas" }, providers: { ours: "/cadastros/people?is_provider=true", status: U, note: "Papel no cadastro único de pessoas" }, clients: { ours: "/cadastros/people?is_client=true", status: U, note: "Papel no cadastro único de pessoas" },
  authorizers: cad("authorizers", { status: T }), accounts: cad("bank_accounts", { status: T }), "open-movements": { ours: "/financeiro/saldo-inicial", status: I }, financialcategories: cad("financial_categories", { status: T }),
  issue: { ours: "/fiscal", status: N, note: "Emissor NF-e (certificado) — gap fiscal" }, "issue-dfe-sync-time": { ours: "/fiscal", status: N, note: "Depende do emissor/SEFAZ" }, "issue-nfse-sync-time": { ours: "/fiscal", status: N, note: "Depende de integração municipal" },
  "tax-rules": cad("tax_rules"), contador: { ours: "/cadastros/people", status: M, note: "Contador é uma pessoa com papel; envio de arquivos ao contador não implementado" }, natureoperations: cad("nature_operations"), "additional-info": cad("additional_infos"), "plan-accounts": cad("chart_accounts"),
  operations: cad("operations"), activities: cad("activities"), "parameter-weights": cad("weight_parameters"), fodder: cad("fodders"),
  animals: { ours: "/pecuaria/animais", status: T }, "animal-retroactive-costs": { ours: "", status: N, note: "Custo retroativo de animais: coluna existe no custeio por lote, tela de lançamento não construída" },
  grazing: cad("grazing_modules"), troughs: cad("troughs"), batches: cad("batches"), "batch-grazing": { ours: "/pecuaria/transferencias/lote-modulo-area", status: U, note: "Lote/Módulo e Lote/Área unificados em uma transferência com histórico" }, "batch-area": { ours: "/pecuaria/transferencias/lote-modulo-area", status: U, note: "Unificado com Lote/Módulo" },
  equipments: cad("equipments", { status: T }), depreciations: { ours: "/frota/depreciacoes", status: T }, "depreciation-forecast": { ours: "/frota/previsao-depreciacao", status: T },
  "tenant-parameters": { ours: "/admin/parametros", status: I },
  "supply-status": { ours: "/suprimentos/sla", status: I }, "my-proccesses": { ours: "/suprimentos/mine", status: T }, "request-purchase": { ours: "/suprimentos/request", status: T }, "rejected-requests": { ours: "/suprimentos/rejected", status: I }, "request-quotation": { ours: "/suprimentos/quotation", status: T }, "request-authorization": { ours: "/suprimentos/authorization", status: T }, "request-buy": { ours: "/suprimentos/buy", status: T }, "request-receipts": { ours: "/suprimentos/receipts", status: T },
  "input-entries": { ours: "/estoque/entradas", status: T }, "dfe-drafts": { ours: "/estoque/aprovacao-notas", status: I }, "provider-launch-profiles": cad("provider_launch_profiles"), "stock-writeoffs": { ours: "/estoque/baixas", status: I }, requisitions: { ours: "/estoque/requisicoes", status: T }, devolution: { ours: "/estoque/devolucoes", status: T }, "stock-corrections": { ours: "/estoque/correcoes", status: I },
  "warehouse-transfer": { ours: "/estoque/transferencias?kind=warehouse", status: T }, "warehouse-transfer-between-farms": { ours: "/estoque/transferencias?kind=farm", status: T }, stocks: { ours: "/estoque/saldo", status: T }, "food-beats": { ours: "/estoque/batidas", status: I },
  events: cad("hr_events"), functions: cad("job_functions"), teams: cad("teams"), absences: cad("absences", { status: T }), advances: { ours: "/gestao-pessoal/adiantamentos", status: T }, bonuses: cad("bonuses"), employeeevents: cad("employee_events"), earnings: { ours: "/gestao-pessoal/apuracao", status: T },
  "document-types": cad("document_types"), "document-managements": cad("documents", { note: "Arquivos via Supabase Storage pendentes de projeto Supabase" }),
  "animals-management": { ours: "/pecuaria/animais", status: T }, "inventoried-animals": { ours: "", status: N, note: "Inventário físico de animais (conferência) não construído" }, "planning-livestock": cad("livestock_plannings"),
  "evolution-animals": { ours: "/pecuaria/transferencias/evolucao", status: I }, "grouper-batches": { ours: "/pecuaria/transferencias/agrupar-lotes", status: I },
  "movement-sales": { ours: "/pecuaria/movimentacoes/sale", status: T }, "movement-purchases": { ours: "/pecuaria/movimentacoes/purchase", status: T }, "birth-animals": { ours: "/pecuaria/movimentacoes/birth", status: I }, "death-animals": { ours: "/pecuaria/movimentacoes/death", status: I }, "loss-animals": { ours: "/pecuaria/movimentacoes/loss", status: I },
  processing: { ours: "/pecuaria/processamentos", status: T }, "purchase-lots": { ours: "/pecuaria/processamentos", status: M, note: "Pré-lotes representados pelos lotes por contagem (herd_lots) da compra; sem tela própria" },
  weighings: { ours: "/pecuaria/pesagens", status: T }, nutritions: { ours: "/pecuaria/manejo/nutrition", status: I }, sanitaries: { ours: "/pecuaria/manejo/sanitary", status: T }, weanings: { ours: "/pecuaria/manejo/weaning", status: I }, separations: { ours: "/pecuaria/manejo/separation", status: I }, "locate-animals": { ours: "/pecuaria/localizar", status: I }, pastures: { ours: "/pecuaria/manejo/pasture", status: I },
  "advanced-reproductive": { ours: "/pecuaria/reproducao", status: I }, "breeding-seasons": cad("breeding_seasons"), "breeding-batch": { ours: "/pecuaria/reproducao/acasalamentos", status: M, note: "Lotes de reprodução por estação: filtro por lote no picker de matrizes; sem entidade própria" }, "bull-seed-season": cad("breeding_sires"), "protocols-season": cad("breeding_protocols"), "breeding-matings": { ours: "/pecuaria/reproducao/acasalamentos", status: I },
  "feedlot-yards": cad("feedlot_yards"), "feedlot-sectors": cad("feedlot_sectors"), "feedlot-corrals": cad("feedlot_corrals"), diets: cad("diets"), "feeding-phases": cad("feeding_phases"), "diet-beats": { ours: "/confinamento/bateladas", status: I }, "diet-beat-supplies": { ours: "/confinamento/trato", status: I }, "trough-readings": { ours: "/confinamento/leitura-cocho", status: I }, "feedlot-map": { ours: "/confinamento/mapa", status: I },
  rainfalls: cad("rainfalls"), budgets: { ours: "/vendas/budgets", status: T }, orders: { ours: "/vendas/orders", status: T }, sales: { ours: "/vendas/sales", status: T },
  "my-service-orders": { ours: "/os?mine=1", status: I }, "service-orders": { ours: "/os", status: I }, "monitoring-service-orders": { ours: "/os/monitoramento", status: I }, "rating-service-orders": { ours: "/os", status: U, note: "Avaliação feita no detalhe da OS finalizada (sem tela separada)" },
  "cash-flow": { ours: "/financeiro/fluxo", status: T }, contracts: cad("contracts"), "budget-plannings": { ours: "/financeiro/previsao-orcamentaria", status: I }, "financial-freezes": cad("financial_freezes", { status: T, note: "Congelamento aplicado no servidor (PERIOD_FROZEN) para títulos, baixas e movimentos" }), "movement-sheets": { ours: "", status: N, note: "Planilha de movimentos (importação em massa) não construída; exportação disponível" },
  maintenances: { ours: "/frota/manutencoes", status: I }, supplies: { ours: "/frota/abastecimentos", status: T }, "maintenance-preventives": { ours: "/cadastros/preventive_maintenances", status: I, note: "Alertas em /frota/alertas" }, "scheduled-reviews": cad("scheduled_reviews", { note: "Alertas em /frota/alertas" }), "equipment-transfer": { ours: "/frota/transferencias", status: I },
  xml: { ours: "/estoque/documentos-fiscais/new", status: I, note: "Importação do XML NF-e no lançamento do documento" }, mdfe: { ours: "/fiscal", status: N, note: "MDF-e depende de emissão fiscal" }, "cash-book": { ours: "/dashboards/livro-caixa", status: E, note: "Dados do livro caixa capturados (contas 'livro caixa', dedutibilidade); geração do arquivo LCDPR não implementada" }, "sped-fiscal": { ours: "/fiscal", status: N, note: "SPED EFD ICMS/IPI depende de emissão fiscal" }, "double-entry-accountings": { ours: "/fiscal/partida-dobrada", status: I },
  "integration-dominios": { ours: "/integracoes/exportacoes", status: N, note: "Integração contábil Domínio não construída; exportação CSV/XLSX disponível" }, "integration-cta-smart": { ours: "/frota/abastecimentos", status: N, note: "Campo 'origem' preparado (cta_smart); importação automática não construída" }, "cta-smart-supplies": { ours: "/frota/abastecimentos", status: N, note: "Idem CTA Smart" }, "financial-export": { ours: "/integracoes/exportacoes", status: I },
  "employees/report": { ours: "/integracoes/exportacoes", status: I }
};
// Relatórios de referência (slug) → chave do nosso runner (/relatorios/<key>) ou tela; status.
export const REPORTS = {
  "ofx-report": ["/financeiro/ofx/relatorio", I], addressings: ["/cadastros/addressings", I], "cash-flow": ["/financeiro/fluxo", T],
  "equipment-report": ["equipment", I], "accumulated-depreciation-report": ["accumulated_depreciation", I], "herd-composition-report": ["herd_composition", I], "costing-livestock-area-report": ["costing_livestock_area", I], "weighing-batch-report": ["weighing_animal", I], "accumulated-weighing-batch-report": ["weighing_batch", I], "feedlot-weighing-performance-report": ["feedlot_weighing", I], "nutrition-report": ["nutrition_batch", I], "sanitaries-batch-report": ["sanitary_batch", I], "management-batch-report": ["management_batch", I], "category-animal-report": ["category_animal", I], "report-transfer-batch-grazing-area": ["transfer_batch_area", I], "animals-report": ["animals", I], "application-management-report": ["application_management", I], "animal-movements-report": ["animal_movements", I], "weaning-report": ["weaning", I], "birth-report": ["birth", I], "death-animals-report": ["death", I], "animal-record-report": ["animal_record", I], "pregnant-cows-report": ["pregnant_cows", I], "animals-sales/report": ["animal_sales", I], "animals-purchases/report": ["animal_purchases", I], "evolution-animals-report": ["herd_evolution", I], "identification-animals-sisbovs-report": ["sisbov_identification", I], "death-animals-sisbovs-report": ["sisbov_death", I], "birth-animals-sisbovs-report": ["sisbov_birth", I], "costing-batch-report": ["costing_batch", I], "costing-grazing-report": ["costing_module", I], "costing-animal-report": ["costing_animal", I], "total-cost-of-reproduction-report": ["reproduction_cost", I], "batch-profitability-report": ["batch_profitability", I], "reproductive-history-report": ["reproductive_history", I], "animal-family-tree-report": ["family_tree", I], "bull-reproductive-efficiency-report": ["bull_efficiency", I], "animal-movement-analysis-report": ["batch_movement_analysis", I], "receiver-cow-productivity-report": ["receiver_productivity", I], "animals-per-batch-report": ["animals_per_batch", I], "animal-batch-history-report": ["animal_batch_history", I], "feedlot-batch-control-report": ["feedlot_batch_control", I], "feedlot-planned-consumption-report": ["feedlot_planned_consumption", I], "feedlot-summary-activity-report": ["feedlot_activity", I], "rainfall-report": ["rainfall", I],
  "receipt-schedule-report": ["receipt_schedule", I], "expenses-report": ["payables", I], "paid-expenses-report": ["paid", T], "incomes-report": ["receivables", I], "paid-incomes-report": ["received", I], "received-interest-report": ["received_interest", I], "paid-interest-report": ["paid_interest", I], "bank-statement-report": ["bank_statement", T], "ledger-report": ["ledger", I], "ledger-category-report": ["ledger_category", I], "rec-prev-real-report": ["rec_prev_real", I], "pag-prev-real-report": ["pag_prev_real", I], "budget-planning-predicted-report": ["budget_predicted", I], "cash-flow-by-category-report": ["cash_flow_category", I], "cash-flow-forecast-report": ["cash_flow_forecast", I], "financial-movement-report": ["financial_movement", I], "fiscal-difference-report": ["fiscal_difference", I], "income-statement": ["income_statement", I], "accumulated-income-statement": ["accumulated_income_statement", I], dre: ["dre", I], "dre-annual": ["dre_annual", I], "receipt-cashflow-report": ["receipt_cashflow", I], "cashflow-product-report": ["cashflow_product", I], "cost-center-report": ["cost_center", I], "cost-calculation-report": ["cost_calculation", I], "financings-report": ["financings", I], "advance-titles-report": ["advance_titles", I], "account-reconciliation-report": ["account_reconciliation", I], "cost-centers-unified-report": ["cost_centers_unified", I], "tax-accounts": ["tax_accounts", E, "API /financial/tax-accounts pronta; sem tela dedicada (usar Contas a Pagar com filtro tributo)"], "accounts-payable-receivable-report": ["payable_receivable", I], "provider-balance-report": ["provider_balance", I],
  "stock-movement-report": ["stock_movement", I], "requisitions-report": ["requisitions", I], "stock-writeoffs-report": ["stock_writeoffs", I], "dfe-report": ["dfe", I], "food-beat-report": ["feed_batch_cost", I], "stocks-abc-report": ["stocks_abc", I], "receipts-report": ["receipts", I], "stocks-consolidated-report": ["stocks_consolidated", T], "stocks-lot-provider": ["stocks_lot_provider", I], "products-exit-cost-center-report": ["exits_cost_center", I],
  "supplies-report": ["supplies", I], "savings-report": ["savings", I], "ans-report": ["ans", I], "request-quotation-report": ["quotations", I], "request-purchase-forecast-report": ["purchase_forecast", I], "supply-status-report": ["supply_sla", I], "request-purchase-management-report": ["purchase_management", I],
  "sales-report": ["sales_client", I], "sales-product-report": ["sales_product", I], "sales-client-report": ["sales_client_product", I], "sales-employee-report": ["sales_employee", I], "sales-abc-report": ["/api/sales/abc", E, "API pronta (curva ABC de vendas); sem tela dedicada"],
  "monthly-calculation": ["monthly_calculation", I], "birthdays-report": ["birthdays", I], "logged-hours-report": ["logged_hours", I], "active-employees": ["active_employees", I], "advances/report": ["advances", I],
  "double-entry-accounting-report": ["journal_entries", I], "nfe-report": ["", N, "Depende de emissão de NF-e"], "nfe-product-report": ["nfe_product", E, "Faturamento por produto calculado a partir das vendas confirmadas (sem NF-e emitida)"], "cash-book-report": ["cash_book", I],
  "equipment-machines-report": ["machines", I], "equipment-machines-supply-report": ["machine_supplies", I], "equipment-machines-maintenance-report": ["machine_maintenances", I],
  "stocks/report": ["stocks_consolidated", T], "products/report": ["/integracoes/exportacoes", I], "proprietaries/report": ["/integracoes/exportacoes", I], "providers/report": ["/integracoes/exportacoes", I], "clients/report": ["/integracoes/exportacoes", I], "plan-accounts/report": ["/integracoes/exportacoes", I], "teams/report": ["/integracoes/exportacoes", I], "employeeevents/report": ["/integracoes/exportacoes", I], "employees/report": ["/integracoes/exportacoes", I]
};
// Ações de cabeçalho/linha da referência → suporte nosso (por padrão herdam o status da tela).
export const ACTIONS = {
  "Saiba +": [X, "Link de ajuda/marketing do fornecedor"], "Adicionar Novo": [null], Visualizar: [null], Editar: [null], Excluir: [null, "Exclusão lógica (soft delete) com auditoria; documentos transacionais são cancelados com estorno"], Exportar: [null, "CSV/XLSX"], Importar: [E, "Importação CSV disponível apenas para produtos/pessoas (registro importExport); demais cadastros pendentes"], Imprimir: [null, "Impressão do navegador"], "fas fa-print": [null, "Impressão do navegador"],
  Filtrar: [null], "Cria descendente": [null, "Árvore (centro de custo/plano de contas/categoria)"], "Adicionar Área": [null, "Cadastro de áreas vinculado à fazenda"], "Adicionar Multiplas Áreas": [N, "Criação em lote de áreas não construída"],
  "Simular Crédito": [X, "Oferta de crédito do fornecedor (marketing)"], "Baixar Contas": [T, "Baixa em lote (movimento único ou separado)"], "Excluir Contas": [I, "Cancelamento em lote"], "Gerar Boleto": [N, "Emissão de boleto exige convênio bancário"], Documentos: [E, "Anexos via Supabase Storage (pendente de projeto)"], "Gerar Recibo": [I, "Recibo textual imprimível"], Baixar: [T], Duplicar: [I], "Imprimir Comprovante": [I, "Detalhe do movimento imprimível"],
  Conciliar: [I], Manifestar: [E, "Manifestação registrada localmente; envio à SEFAZ não integrado"], "Lançar Despesa em Lote": [E, "Lançamento a partir da DFe via aprovação de notas (individual)"], "Buscar DFe": [N, "Consulta SEFAZ exige certificado"],
  Voltar: [X, "Navegação"], Limpar: [null, "Limpar filtros"], Salvar: [null], "Adicionar novo": [null], "Adicionar Novo Acasalamento": [I], "Novo Lote": [null, "Cadastro de lotes"], "Adicionar Ingrediente": [I, "Itens da formulação/dieta"], "Exportar Excel": [null, "XLSX"], "Relatório Individual": [I, "Ficha do animal"], "Relatório SLA": [I, "/relatorios/supply_sla"], Agrupar: [I], "Transferir Responsável": [T], "Transferir Responsável em Lote": [I, "POST /supply/requests/transfer-batch"], "Acusar ciência": [T], "Voltar Etapa": [I], "Enviar pedido de compras.": [I, "WhatsApp/e-mail via links"], "Gerar financeiro": [T], "Transferir de Lote": [I], "Realizar Pesagem": [T], "Realizar Sanitário": [T], "Status Reprodutivo": [I, "Diagnóstico de gestação"], "Consultar não encerrados": [I, "Filtro de status"], "Apuração Mensal (Grade)": [I], "Download Arquivo": [E, "Anexos via Storage pendentes"], "DFe Recebidas": [E], "Abastecimentos Importados": [N, "CTA Smart"], "Sincronizar Agora": [N, "SEFAZ/NFS-e"], Configuração: [N, "Emissor fiscal"], Certificado: [N, "Certificado digital"], "Dados Fiscais": [N, "Emissor fiscal"], "Importar arquivo KML": [N, "Georreferenciamento"], "Exportar KML": [N, "Georreferenciamento"], "Imprimir mapa": [N, "Georreferenciamento"], "Importar planilha": [N, "Planilha de movimentos"], Proprietario: [U, "Papel de pessoa"], Funcionário: [U, "Papel de pessoa"], Fornecedor: [U, "Papel de pessoa"], Cliente: [U, "Papel de pessoa"], Usuário: [I], Safra: [I],
  Transferir: [I], Aprovar: [T], Reprovar: [T], Cotar: [T], "Ciência": [T], Finalizar: [I], Cancelar: [T], Processar: [T], Avaliar: [I], Iniciar: [I], "Nova Leitura": [I], Calcular: [T], "Gerar Financeiro": [T], Fechar: [I], Lançar: [I], Lançado: [I]
};
