"use client";
import * as React from "react";
import { todayISO } from "@/lib/utils";
import { Button, Card, CardHeader, CardBody, Field, Input, NativeSelect } from "@/components/ui";
import { RefSelect } from "@/components/ui/ref-select";
import { useEmpresaPadrao, useCreate, DocList, colDate, colStatus } from "@/features/docs/shared";
import { AnimalPicker } from "@/features/livestock/shared";
export function TransferToFarm({ batchId, animalIds, onDone, history = true }: { batchId?: string; animalIds?: string[]; onDone?: () => void; history?: boolean } = {}) {
  const empresa = useEmpresaPadrao(); const [f, setF] = React.useState({ empresa_id: "", empresa_destino_id: "", movement_date: todayISO(), batch_id: batchId ?? "", destination_batch_id: "", note: "", mode: animalIds?.length ? "animals" : "batch" }); const [sel, setSel] = React.useState<string[]>(animalIds ?? []);
  React.useEffect(() => { setF((o) => ({ ...o, empresa_id: o.empresa_id || empresa })); }, [empresa]);
  const create = useCreate("/api/livestock/transfers/to-empresa", () => { setSel([]); onDone?.(); });
  return <div className="space-y-3"><Card><CardHeader title="Transferência entre Empresas" subtitle="Cria um movimento pendente; a empresa de destino processa o recebimento (tela do movimento)." actions={<Button size="sm" loading={create.isPending} disabled={!f.empresa_destino_id || (f.mode === "batch" ? !f.batch_id : !sel.length)} onClick={() => create.mutate({ empresa_id: f.empresa_id, empresa_destino_id: f.empresa_destino_id, movement_date: f.movement_date, batch_id: f.mode === "batch" ? f.batch_id : null, animal_ids: f.mode === "animals" ? sel : undefined, destination_batch_id: f.destination_batch_id || null, note: f.note || null })}>Transferir</Button>} /><CardBody className="space-y-3">
    <div className="grid grid-cols-12 gap-2"><Field label="Empresa origem" span={3}><RefSelect resource="empresas" value={f.empresa_id} onChange={(v) => setF({ ...f, empresa_id: v ?? "" })} /></Field><Field label="Empresa destino" required span={3}><RefSelect resource="empresas" value={f.empresa_destino_id} onChange={(v) => setF({ ...f, empresa_destino_id: v ?? "" })} /></Field><Field label="Data" span={2}><Input type="date" value={f.movement_date} onChange={(e) => setF({ ...f, movement_date: e.target.value })} /></Field><Field label="Modo" span={2}><NativeSelect value={f.mode} onChange={(e) => setF({ ...f, mode: e.target.value })}><option value="batch">Lote inteiro</option><option value="animals">Animais selecionados</option></NativeSelect></Field>
      {f.mode === "batch" ? <Field label="Lote" required span={4}><RefSelect resource="batches" value={f.batch_id} onChange={(v) => setF({ ...f, batch_id: v ?? "" })} /></Field> : null}<Field label="Lote destino (opcional)" span={4}><RefSelect resource="batches" value={f.destination_batch_id} onChange={(v) => setF({ ...f, destination_batch_id: v ?? "" })} /></Field><Field label="Observação" span={4}><Input value={f.note} onChange={(e) => setF({ ...f, note: e.target.value })} /></Field></div>
    {f.mode === "animals" && <AnimalPicker selected={sel} onChange={setSel} empresaId={f.empresa_id || undefined} />}
  </CardBody></Card>
  {history && <DocList title="Transferências entre empresas" endpoint="/api/livestock/movements" base="/pecuaria/movimentacoes/farm_transfer" defaultFilters={{ movement_type: "farm_transfer" }} hideNew columns={[{ key: "code", label: "Código" }, colDate("movement_date", "Data"), { key: "empresa_name", label: "Origem" }, { key: "batch_name", label: "Lote" }, { key: "quantity", label: "Cabeças", align: "right" }, colStatus()]} />}</div>;
}
