/** Árvore de navegação do nosso sistema (espelha a estrutura funcional do sistema de referência, com rotas próprias). */
export interface NavItem { label: string; href?: string; perm?: string; children?: NavItem[] }
export const NAV: NavItem[] = [
  { label: "Painel de Controle", href: "/", perm: "dashboard.home.view" },
  { label: "Dashboards", children: [
    { label: "Financeiros", href: "/dashboards/financeiro", perm: "dashboard.financial.view" }, { label: "Livro Caixa", href: "/dashboards/livro-caixa", perm: "dashboard.cash_book.view" }, { label: "Suprimentos", href: "/dashboards/suprimentos", perm: "dashboard.supply.view" },
    { label: "Pecuária de Corte", href: "/dashboards/pecuaria", perm: "dashboard.livestock.view" }, { label: "Depreciações", href: "/dashboards/depreciacoes", perm: "dashboard.depreciation.view" }, { label: "Ativos", href: "/dashboards/ativos", perm: "dashboard.assets.view" },
    { label: "Análise de Usuários", href: "/dashboards/usuarios", perm: "dashboard.user_analysis.view" }, { label: "Pluviometria", href: "/dashboards/pluviometria", perm: "dashboard.rainfall.view" }, { label: "Lotação de Currais", href: "/dashboards/confinamento", perm: "dashboard.feedlot.view" },
    { label: "Custos do Confinamento", href: "/dashboards/confinamento-custos", perm: "dashboard.feedlot_cost.view" }, { label: "Desempenho de Lotes", href: "/dashboards/confinamento-desempenho", perm: "dashboard.feedlot_performance.view" }, { label: "Estoque Nutrição", href: "/dashboards/estoque-nutricao", perm: "dashboard.nutrition_stock.view" }, { label: "Consumo de Ração", href: "/dashboards/consumo-racao", perm: "dashboard.feed_consumption.view" }
  ] },
  { label: "Cadastros Base", children: [
    { label: "Estrutura", children: [
      { label: "Centros de Custo", href: "/cadastros/cost_centers", perm: "cost_centers.view" }, { label: "Fazendas", href: "/cadastros/farms", perm: "farms.view" }, { label: "Safras", href: "/cadastros/harvests", perm: "harvests.view" },
      { label: "Produtos", children: [{ label: "Endereçamentos", href: "/cadastros/addressings", perm: "addressings.view" }, { label: "Produtos", href: "/cadastros/products", perm: "products.view" }, { label: "Grupos/Categorias/Classes", href: "/cadastros/product_groups", perm: "products.view" }, { label: "Unidades de Medida", href: "/cadastros/measurement_units", perm: "products.view" }, { label: "Variedades/Culturas", href: "/cadastros/cultivations", perm: "products.view" }, { label: "Armazéns", href: "/cadastros/warehouses", perm: "warehouses.view" }, { label: "Estoques Iniciais", href: "/estoque/estoque-inicial", perm: "opening_balances.view" }] },
      { label: "Rateios", children: [{ label: "Categorias", href: "/cadastros/apportionment_categories", perm: "apportionments.view" }] }
    ] },
    { label: "Pessoas", children: [
      { label: "Perfil Usuário", href: "/admin/perfis", perm: "roles.view" }, { label: "Pessoas Unificado", href: "/cadastros/people", perm: "people.view" }, { label: "Proprietários", href: "/cadastros/people?is_proprietary=true", perm: "proprietaries.view" }, { label: "Funcionários", href: "/cadastros/people?is_employee=true", perm: "employees.view" },
      { label: "Fornecedores", href: "/cadastros/people?is_provider=true", perm: "providers.view" }, { label: "Clientes", href: "/cadastros/people?is_client=true", perm: "clients.view" }, { label: "Usuários", href: "/admin/usuarios", perm: "users.view" }, { label: "Autorizadores", href: "/cadastros/authorizers", perm: "authorizers.view" }
    ] },
    { label: "Financeiros", children: [{ label: "Contas Bancárias", href: "/cadastros/bank_accounts", perm: "bank_accounts.view" }, { label: "Saldo Inicial", href: "/financeiro/saldo-inicial", perm: "opening_movements.view" }, { label: "Categorias Financeiras", href: "/cadastros/financial_categories", perm: "financial_categories.view" }, { label: "Tipos de Título", href: "/cadastros/title_types", perm: "payables.view" }, { label: "Formas de Pagamento", href: "/cadastros/payment_methods", perm: "sales.view" }] },
    { label: "Fiscais", children: [{ label: "Regras Fiscais", href: "/cadastros/tax_rules", perm: "tax_rules.view" }, { label: "Natureza de Operação", href: "/cadastros/nature_operations", perm: "nature_operations.view" }, { label: "Info. Complementares", href: "/cadastros/additional_infos", perm: "additional_infos.view" }, { label: "Plano de Contas", href: "/cadastros/chart_accounts", perm: "chart_accounts.view" }, { label: "Integrações Fiscais (NFe/DFe/NFSe)", href: "/cadastros/integrations", perm: "integration.dominio.view" }] },
    { label: "Agrícolas", children: [{ label: "Operações", href: "/cadastros/operations", perm: "operations.view" }, { label: "Atividades", href: "/cadastros/activities", perm: "activities.view" }] },
    { label: "Pecuários", children: [{ label: "Parâmetros/Peso", href: "/cadastros/weight_parameters", perm: "weight_parameters.view" }, { label: "Forragem", href: "/cadastros/fodders", perm: "fodders.view" }, { label: "Rebanho", href: "/pecuaria/animais", perm: "animals.view" }, { label: "Espécies/Categorias/Raças", href: "/cadastros/animal_categories", perm: "animals.view" }, { label: "Módulo Pastejo", href: "/cadastros/grazing_modules", perm: "grazing_modules.view" }, { label: "Áreas (Lote/Área)", href: "/cadastros/areas", perm: "batch_area.view" }, { label: "Cochos", href: "/cadastros/troughs", perm: "troughs.view" }, { label: "Lotes Animais", href: "/cadastros/batches", perm: "batches.view" }] },
    { label: "Bens/Ativos", children: [{ label: "Inventário", href: "/cadastros/equipments", perm: "equipments.view" }, { label: "Famílias de Bens", href: "/cadastros/equipment_families", perm: "equipments.view" }, { label: "Depreciação Mensal", href: "/frota/depreciacoes", perm: "depreciations.view" }, { label: "Prev. Depreciação", href: "/frota/previsao-depreciacao", perm: "depreciation_forecast.view" }] },
    { label: "Gerais", children: [{ label: "Parametrizações", href: "/admin/parametros", perm: "tenant_parameters.edit" }] }
  ] },
  { label: "Administrativo", children: [
    { label: "Suprimentos", children: [{ label: "Parâmetros SLA", href: "/suprimentos/sla", perm: "supply_sla.view" }, { label: "Meus Processos", href: "/suprimentos/mine", perm: "purchase_requests.view" }, { label: "Solicitação", href: "/suprimentos/request", perm: "purchase_requests.view" }, { label: "Rejeitados/Cancelados", href: "/suprimentos/rejected", perm: "rejected_requests.view" }, { label: "Cotações", href: "/suprimentos/quotation", perm: "purchase_quotations.view" }, { label: "Autorização", href: "/suprimentos/authorization", perm: "purchase_authorization.view" }, { label: "Compras", href: "/suprimentos/buy", perm: "purchase_buy.view" }, { label: "Recebimentos", href: "/suprimentos/receipts", perm: "purchase_receipts.view" }] },
    { label: "Estoque", children: [
      { label: "Doc. Fiscal/Entrada", href: "/estoque/documentos-fiscais", perm: "invoices.view" }, { label: "Entrada/Insumos", href: "/estoque/entradas", perm: "input_entries.view" }, { label: "DFe Recebidas", href: "/estoque/dfe", perm: "dfe.view" }, { label: "Aprovação de Notas", href: "/estoque/aprovacao-notas", perm: "dfe_drafts.view" }, { label: "Perfis de Lançamento", href: "/cadastros/provider_launch_profiles", perm: "provider_launch_profiles.view" },
      { label: "Baixa de Estoque", href: "/estoque/baixas", perm: "stock_writeoffs.view" }, { label: "Requisição/Saída", href: "/estoque/requisicoes", perm: "requisitions.view" }, { label: "Devolução/Entrada", href: "/estoque/devolucoes", perm: "devolutions.view" }, { label: "Correção de Estoque", href: "/estoque/correcoes", perm: "stock_corrections.view" }, { label: "Trans. Armazém", href: "/estoque/transferencias?kind=warehouse", perm: "warehouse_transfers.view" }, { label: "Trans. Fazendas", href: "/estoque/transferencias?kind=farm", perm: "farm_transfers.view" }, { label: "Saldo Estoque", href: "/estoque/saldo", perm: "stocks.view" },
      { label: "Fábrica", children: [{ label: "Formulação", href: "/estoque/formulacoes", perm: "feed_formulas.view" }, { label: "Batida", href: "/estoque/batidas", perm: "feed_batches.view" }] }
    ] },
    { label: "Gestão Pessoal", children: [{ label: "Eventos", href: "/cadastros/hr_events", perm: "hr_events.view" }, { label: "Funções", href: "/cadastros/job_functions", perm: "job_functions.view" }, { label: "Equipes", href: "/cadastros/teams", perm: "teams.view" }, { label: "Registro/Faltas", href: "/cadastros/absences", perm: "absences.view" }, { label: "Adiant. Salarial", href: "/gestao-pessoal/adiantamentos", perm: "salary_advances.view" }, { label: "Registro/Eventos", href: "/cadastros/bonuses", perm: "bonuses.view" }, { label: "Funcionário X Eventos", href: "/cadastros/employee_events", perm: "employee_events.view" }, { label: "Apuração Mensal", href: "/gestao-pessoal/apuracao", perm: "earnings.view" }] },
    { label: "Gestão Documentos", children: [{ label: "Tipo Documento", href: "/cadastros/document_types", perm: "document_types.view" }, { label: "Documentos", href: "/cadastros/documents", perm: "documents.view" }] }
  ] },
  { label: "Operacional", children: [
    { label: "Pecuária", children: [
      { label: "Gestão Animais", href: "/pecuaria/animais", perm: "animals_management.view" }, { label: "Planejamento", href: "/cadastros/livestock_plannings", perm: "livestock_plannings.view" },
      { label: "Transferências", children: [{ label: "Evolução/Rebanho", href: "/pecuaria/transferencias/evolucao", perm: "herd_evolution.view" }, { label: "Animais/Lote", href: "/pecuaria/transferencias/animais-lote", perm: "animal_batch_transfer.view" }, { label: "Agrupar/Lotes", href: "/pecuaria/transferencias/agrupar-lotes", perm: "batch_grouping.view" }, { label: "Lote/Módulo/Área", href: "/pecuaria/transferencias/lote-modulo-area", perm: "batch_module_area_transfer.view" }, { label: "Lote/Fazenda", href: "/pecuaria/transferencias/lote-fazenda", perm: "batch_farm_transfer.view" }] },
      { label: "Movimentações", children: [{ label: "Vendas", href: "/pecuaria/movimentacoes/sale", perm: "animal_sales.view" }, { label: "Compras", href: "/pecuaria/movimentacoes/purchase", perm: "animal_purchases.view" }, { label: "Nascimentos", href: "/pecuaria/movimentacoes/birth", perm: "animal_births.view" }, { label: "Mortes", href: "/pecuaria/movimentacoes/death", perm: "animal_deaths.view" }, { label: "Perdas", href: "/pecuaria/movimentacoes/loss", perm: "animal_losses.view" }] },
      { label: "Manejo", children: [{ label: "Processamentos", href: "/pecuaria/processamentos", perm: "processings.view" }, { label: "Pesagem", href: "/pecuaria/pesagens", perm: "weighings.view" }, { label: "Nutrição", href: "/pecuaria/manejo/nutrition", perm: "nutritions.view" }, { label: "Sanitário", href: "/pecuaria/manejo/sanitary", perm: "sanitaries.view" }, { label: "Desmama", href: "/pecuaria/manejo/weaning", perm: "weanings.view" }, { label: "Apartação", href: "/pecuaria/manejo/separation", perm: "separations.view" }, { label: "Localiza Animal", href: "/pecuaria/localizar", perm: "locate_animals.view" }, { label: "Pastagem", href: "/pecuaria/manejo/pasture", perm: "pastures.view" },
        { label: "Reprodução", children: [{ label: "Gerenciamento Avançado", href: "/pecuaria/reproducao", perm: "advanced_reproductive.view" }, { label: "Estação de Monta", href: "/cadastros/breeding_seasons", perm: "breeding_seasons.view" }, { label: "Touros/Sêmen/Embrião", href: "/cadastros/breeding_sires", perm: "breeding_sires.view" }, { label: "Protocolos/Estação", href: "/cadastros/breeding_protocols", perm: "breeding_protocols.view" }, { label: "Acasalamento", href: "/pecuaria/reproducao/acasalamentos", perm: "matings.view" }] }] },
      { label: "Confinamento", children: [{ label: "Pátios", href: "/cadastros/feedlot_yards", perm: "feedlot_yards.view" }, { label: "Setores", href: "/cadastros/feedlot_sectors", perm: "feedlot_sectors.view" }, { label: "Currais", href: "/cadastros/feedlot_corrals", perm: "feedlot_corrals.view" }, { label: "Dieta", href: "/cadastros/diets", perm: "diets.view" }, { label: "Fases/Regras Troca", href: "/cadastros/feeding_phases", perm: "feeding_phases.view" }, { label: "Batelada", href: "/confinamento/bateladas", perm: "diet_batches.view" }, { label: "Trato Diário", href: "/confinamento/trato", perm: "feed_deliveries.view" }, { label: "Leitura de Cocho", href: "/confinamento/leitura-cocho", perm: "trough_readings.view" }, { label: "Mapa", href: "/confinamento/mapa", perm: "feedlot_map.view" }] }
    ] },
    { label: "Pluviometria", href: "/cadastros/rainfalls", perm: "rainfalls.view" },
    { label: "Vendas", children: [{ label: "Orçamentos", href: "/vendas/budgets", perm: "budgets.view" }, { label: "Pedidos", href: "/vendas/orders", perm: "orders.view" }, { label: "Vendas", href: "/vendas/sales", perm: "sales.view" }] },
    { label: "Ordens de Serviço", children: [{ label: "Minhas OS", href: "/os?mine=1", perm: "service_orders.view" }, { label: "Lista de OS", href: "/os", perm: "service_orders.view" }, { label: "Monitoramento", href: "/os/monitoramento", perm: "service_orders.monitor" }] }
  ] },
  { label: "Financeiro", children: [
    { label: "Contas a Pagar", href: "/financeiro/contas-a-pagar", perm: "payables.view" }, { label: "Contas a Receber", href: "/financeiro/contas-a-receber", perm: "receivables.view" }, { label: "Mov. Caixa/Bancário", href: "/financeiro/movimentos", perm: "bank_movements.view" }, { label: "Fluxo Bancário", href: "/financeiro/fluxo", perm: "cash_flow.view" },
    { label: "Conciliação", children: [{ label: "Importação OFX", href: "/financeiro/ofx", perm: "ofx_imports.view" }, { label: "Meses Conciliados", href: "/financeiro/ofx/relatorio", perm: "ofx_report.view" }] },
    { label: "Gestão Contratos", href: "/cadastros/contracts", perm: "contracts.view" }, { label: "Prev. Orçamentária", href: "/financeiro/previsao-orcamentaria", perm: "budget_plannings.view" }, { label: "Congelamentos Financeiros", href: "/cadastros/financial_freezes", perm: "financial_freezes.view" }
  ] },
  { label: "Gestão de Frota", children: [{ label: "Manutenções", href: "/frota/manutencoes", perm: "maintenances.view" }, { label: "Abastecimentos", href: "/frota/abastecimentos", perm: "fuel_supplies.view" }, { label: "Manutenções Preventivas", href: "/cadastros/preventive_maintenances", perm: "preventive_maintenances.view" }, { label: "Revisões Agendadas", href: "/cadastros/scheduled_reviews", perm: "scheduled_reviews.view" }, { label: "Alertas de Frota", href: "/frota/alertas", perm: "preventive_maintenances.view" }, { label: "Transferência Máquinas", href: "/frota/transferencias", perm: "equipment_transfers.view" }] },
  { label: "Gestão Fiscal", children: [{ label: "Partida Dobrada", href: "/fiscal/partida-dobrada", perm: "journal_entries.view" }, { label: "Livro Caixa (LCDPR)", href: "/relatorios/cash_book", perm: "report.cash_book.view" }, { label: "NFe / MDFe / SPED", href: "/fiscal", perm: "nfe.view" }] },
  { label: "Relatórios", href: "/relatorios", perm: "report.stock_movement.view" },
  { label: "Integrações", children: [{ label: "Configurações", href: "/cadastros/integrations", perm: "integration.dominio.view" }, { label: "Exportações CSV/XLSX", href: "/integracoes/exportacoes", perm: "integration.csv_export.view" }] },
  { label: "Administração", children: [{ label: "Auditoria", href: "/admin/auditoria", perm: "audit_logs.view" }, { label: "Notificações", href: "/admin/notificacoes" }, { label: "Meu Perfil", href: "/admin/perfil" }] }
];
export function flatNav(items: NavItem[] = NAV, path: string[] = []): { href: string; label: string; path: string[]; perm?: string }[] {
  return items.flatMap((i) => [...(i.href ? [{ href: i.href, label: i.label, path: [...path, i.label], perm: i.perm }] : []), ...(i.children ? flatNav(i.children, [...path, i.label]) : [])]);
}
